### ISSUE TITLE
Merge network-refactor into master

### ISSUE THREAD

**Issue by tli2** [cmu-db/peloton#1002]
I just created a PR for the last bit of network refactor code I wanted to get in for this week. We will be able to merge the whole thing into master as soon as that PR is merged.

Several items before we merge network-refactor though:
- Merge conflicts, probably
- Need to figure out a merge order since this probably conflicts with SSL and all the larger-scale renaming refactors happening after 25th
- If we have some other test cases not run on build, now might be a good time to run them before the new code is in to make sure no serious regression is going on.

@apavlo What do you think?

**Comment by ChTimTsubasa** [comment]
This is addressed.
