### ISSUE TITLE
Formatter script not seeming to work

### ISSUE THREAD

**Issue by tli2** [cmu-db/peloton#1015]
```
MacBook-Pro:formatting Tianyu$ python formatter.py -c ../../src/include/network
12-28-2017 20:31:20 [<module>:170] INFO : Scanning directory ../../src/include/network
12-28-2017 20:31:20 [format_file:115] INFO : clang-format-3.6 -style=file  -i ../../src/include/network/connection_dispatcher_task.h
Traceback (most recent call last):
  File "formatter.py", line 171, in <module>
    format_dir(x, args.update_header, args.clang_format_code)
  File "formatter.py", line 132, in format_dir
    format_file(file_path, update_header, clang_format_code)
  File "formatter.py", line 116, in format_file
    subprocess.call([CLANG_FORMAT, "-style=file", "-i", file_path])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

In addition, the command-line flag -d mentioned in the wiki does not seem to be supported any more.

**Comment by schedutron** [comment]
Is `clang-format-3.6` executing separately as a terminal command on your machine?

**Comment by apavlo** [comment]
There are three outstanding PRs for the formatting script (#994, #993, #991).
I also thought that we agreed to not require an exact version of `clang-format`?

@tcm-marcel Can you figure out what's going on with all the PRs and this problem when you get back?

**Comment by schedutron** [comment]
Even if an exact version is not used, it might happen that even `clang-format` command doesn't work on a person's machine. If one does a fresh install of `clang-format` (latest version), the `clang-format` command *still* won't work on their machine, but `clang-format-3.7` will.

So the formatter script needs to find the correct version/command for `clang-format` installed, but that may not be a trivial task to do.

**Comment by tli2** [comment]
I can confirm that changing the script to use clang-format-3.7 fixes the issue on my machine.

**Comment by tcm-marcel** [comment]
Different versions of clang-format produce different output and even the command line arguments don't seem to be stable among versions. I suggest to call a fixed version from both source validator and formatter.

**Comment by tli2** [comment]
Under new student guide in code style

**Comment by tcm-marcel** [comment]
@haoxianghua just tested this on his Mac and apparently you can't install a specific version of clang-format using brew (and thus validator and formatter don't work). 
@pmenon I can remember it worked for you - which version of clang-format do you use?

**Comment by pmenon** [comment]
@tcm-marcel I use 3.6 by default. Why not have the script discover the clang-format version available by trying a few likely versions?

**Comment by pervazea** [comment]
With the change for #1061, is this now resolved? Is there anything still needing fixes after that change?

**Comment by tcm-marcel** [comment]
It should be resolved.
