### ISSUE TITLE
packages.sh execution fails on Ubuntu 16.04+

### ISSUE THREAD

**Issue by eribeiro** [cmu-db/peloton#1027]
Running `sudo bash packages.sh` fails on Ubuntu 16.04 due to a command rename and deprecated command line option of apt-get.

Ubuntu 16.04+ renamed `cmake3` command to just `cmake`. Also, the apt-get's  `--force-yes` was deprecated and only runs if we remove it (or change it to one of the `--allow` prefixes). After doing those changes it will install the dependencies and successfully proceed the building of Peloton. Didn't check Ubuntu 15+ to see if it builds though. Finally, `cmake` version installed was `3.5.1`, not the latest it seems.

**Comment by apavlo** [comment]
@eribeiro Can you send a PR?

**Comment by eribeiro** [comment]
Sure! :) Gonna send one as soon as possible (afk). :+1:
