### ISSUE TITLE
Make sure that we don't use brackets for #include

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#1038]
I fixed some `#include`'s where we were using the brackets (`<...>`) instead of quotation marks (`"..."`):

https://github.com/cmu-db/peloton/pull/1037/commits/9e72651dcf1ff89c2a9fb117094843fa629a7994

It would nice if the validator script could check this automatically and prevent this from happening. For each `#include` that uses brackets, it can simply check to see whether it's one of our own files and throw an error if it is.

**Comment by tli2** [comment]
Just as an aside that CLion-generated includes are always `<>` for some reason (it is stupid).  This could be one of the reasons people use `<>`.

Also, is there a  style guide on whether to use always `#include "dir/file"` or is `#include file` fine for a file in dir?

**Comment by apavlo** [comment]
I thought that the convention was `<>` for something you expect to be installed in the system and `""` for something that is local to the project?

**Comment by malin1993ml** [comment]
Yes. At least that's the convention that I'm following.

**Comment by schedutron** [comment]
Can I work on adding this to the validator script?

**Comment by tcm-marcel** [comment]
@schedutron Sure, give it a try. Make sure to rebase your repo, as #991 got merged in today. You can then create a PR and I will review it.

**Comment by schedutron** [comment]
Do we need to check only the header files in the `src/include` folder?

**Comment by tcm-marcel** [comment]
All files (header and implementation) must be checked for includes that use brackets `<...>`. If `...` is an existing file in `src/include/...`, an error should be thrown. Maybe check for relatives path both with and without `include/`.

**Comment by schedutron** [comment]
No, I mean the file mentioned in `#include <...>` would be present only in `src/include`, so I was wondering that, for a given `#include <...>` statement, should I check for the file's presence in only `src/include` or other directories as well?

**Comment by tcm-marcel** [comment]
Only in `src/include`, but make sure that the check also works if the include path starts with `include/...` (which is wrong, but otherwise me miss those).

**Comment by tcm-marcel** [comment]
Added in #1054.
