### ISSUE TITLE
Link error when building tests

### ISSUE THREAD

**Issue by amaliujia** [cmu-db/peloton#105]
I pulled the latest version code and compiled code in master branch, but  get the following error:

`libtool: link: cannot find the library ../third_party/gmock/libgmock.la' or unhandled argument ../third_party/gmock/libgmock.la`

However, I can see this library in the Makefile.am in root_dir,

`include $(top_srcdir)/third_party/gmock/Makefile.am`

I used make check.

I have no idea what's wrong. Anyone can help fix this?

**Comment by yingjunwu** [comment]
please perform `make -j` first before running `make check`.

**Comment by yingjunwu** [comment]
@amaliujia does it work?

**Comment by amaliujia** [comment]
It works! Thanks @yingjunwu
