### ISSUE TITLE
Buggy INSERT

### ISSUE THREAD

**Issue by schedutron** [cmu-db/peloton#1069]
If I `CREATE TABLE foo(id int)` and then type the following queries,

```
insert into foo(f) values(5);
insert into foo(f) values(3);
insert into foo(f) values(2);
```
no error is reported. Furthermore, when I run the query `SELECT * FROM foo;`, I get the following weird output:

```
 id 
----
   
   
   
(3 rows)
```

**Comment by pmenon** [comment]
This was fixed in #1063
