### ISSUE TITLE
Duplicate function names "btrim" in src/catalog/catalog.cpp

### ISSUE THREAD

**Issue by nwang57** [cmu-db/peloton#1072]
In `src/catalog/catalog.cpp` on line 1030 there are two "btrim" function names. Looks like a typo.

<img width="756" alt="screen_shot_20180118_at_9 36 25_pm" src="https://user-images.githubusercontent.com/7065997/35159331-e1579dcc-fd07-11e7-8499-27e0f9f06286.png">

**Comment by schedutron** [comment]
Won't they have different signatures?

**Comment by nwang57** [comment]
They do have different signatures but still it looks like a typo for me.

**Comment by pervazea** [comment]
This is not a typo.
It is left as an exercise to the reader to understand why. As a hint, read the specification of the trim group of SQL functions. It does seem though, that the function header documentation for AddBuiltinFunction is not entirely correct.
