### ISSUE TITLE
Trace build fails

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1073]
[ 48%] Building CXX object src/CMakeFiles/peloton.dir/traffic_cop/traffic_cop.cpp.o
In file included from /home/pakhtar/proj/peloton-pa/peloton/src/include/common/internal_types.h:29:0,
                 from /home/pakhtar/proj/peloton-pa/peloton/src/include/catalog/constraint.h:20,
                 from /home/pakhtar/proj/peloton-pa/peloton/src/include/catalog/column.h:15,
                 from /home/pakhtar/proj/peloton-pa/peloton/src/include/traffic_cop/traffic_cop.h:22,
                 from /home/pakhtar/proj/peloton-pa/peloton/src/traffic_cop/traffic_cop.cpp:13:
/home/pakhtar/proj/peloton-pa/peloton/src/traffic_cop/traffic_cop.cpp: In member function ‘void peloton::tcop::TrafficCop::ExecuteStatementPlanGetResult()’:
/home/pakhtar/proj/peloton-pa/peloton/src/traffic_cop/traffic_cop.cpp:215:9: error: ‘is_single_statement_txn_’ was not declared in this scope
         is_single_statement_txn_, init_failure,
         ^
/home/pakhtar/proj/peloton-pa/peloton/src/include/common/logger.h:145:32: note: in definition of macro ‘LOG_TRACE’
   ::fprintf(LOG_OUTPUT_STREAM, __VA_ARGS__);                                  \
                                ^
At global scope:
cc1plus: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/peloton.dir/traffic_cop/traffic_cop.cpp.o] Error

**Comment by schedutron** [comment]
How can I reproduce this issue?

**Comment by pervazea** [comment]
It looks like a trivial fix... I'll take care of it.

**Comment by pranavk** [comment]
Oops. Sorry for stepping on to your toes. Didn't notice this before. I have a fix for this in #1098

**Comment by pervazea** [comment]
No worries.

________________________________

**Comment by pervazea** [comment]
Addressed by #1098
