### ISSUE TITLE
Failure to install peloton on vagrant hosted on Mac

### ISSUE THREAD

**Issue by yjc408** [cmu-db/peloton#1091]
When I installed peloton with vagrant hosted Mac, I got the following error message every time:

../lib/libpeloton.so.0.0.5: undefined reference to `pg_query_free_parse_result'
../lib/libpeloton.so.0.0.5: undefined reference to `pg_query_parse_init'
../lib/libpeloton.so.0.0.5: undefined reference to `pg_query_parse'
../lib/libpeloton.so.0.0.5: undefined reference to `pg_query_parse_finish'

**Comment by poojanilangekar** [comment]
What's the version of CMake on your VM?

**Comment by poojanilangekar** [comment]
The current version builds without any failures. Please make sure you are using a version after [this](https://github.com/cmu-db/peloton/commit/0fc7c2021c8b117f78f2df5c591727a69ca662cc#diff-46454d00238f98e83096b2d44703df7eL150) patch.
