### ISSUE TITLE
CMake version on the Vagrant VM needs to be upgraded

### ISSUE THREAD

**Issue by poojanilangekar** [cmu-db/peloton#1093]
The current version of CMake on the Vagrant VM is cmake-2.6. While Cap'nProto does not build needs a minimum of cmake- 3.1 to be installed.

**Comment by crd477** [comment]
I think the change in https://github.com/cmu-db/peloton/commit/0fc7c2021c8b117f78f2df5c591727a69ca662cc#diff-46454d00238f98e83096b2d44703df7e should have resolved this but I don't have access to Vagrant.  Could you please check?

**Comment by poojanilangekar** [comment]
@crd477 Yes, you are right. This has been solved. Thanks!
