### ISSUE TITLE
Refactor python scripts

### ISSUE THREAD

**Issue by tcm-marcel** [cmu-db/peloton#1094]
As suggested from @pervazea in #1061:

* convert source validator and source formatter to python3
* run Pylint
* remove globals where possible
* put duplicated functions in library
  * Call to clang-format together with finding its correct veesion

**Comment by schedutron** [comment]
Can I work on this one?

**Comment by tcm-marcel** [comment]
Sure. I added two more things to the description.

**Comment by schedutron** [comment]
What happens sometimes is, I edit a source file, and only the edited part isn't formatted well. The validator complains, and then I run the formatter and it formats the entire file. When I push my commits, it's a bit difficult for the reviewers to separate my work from the formatter's cleaning in the diff. Can we somehow add functionality to make the formatter run only on the edited part of a source file?

**Comment by tcm-marcel** [comment]
You can create a first commit with `commit --no-verify` and then format the file in a second commit. This way the reviewer can only use the first commit for the review.

**Comment by schedutron** [comment]
Since the formatter and validator are in different folders, the common library functions have to be put in a package so that both can import them. So should I create a package for the common functions?

**Comment by schedutron** [comment]
Should other Python scripts, like `warning-fixer.py` also be formatted?

**Comment by pervazea** [comment]
FYI, there are accepted coding standards (best practices) for Python, i.e. PEP-8. If you are reformatting the Python code, you should look at and follow PEP-8.

________________________________

**Comment by schedutron** [comment]
@pervazea I know, I have contributed to Python's core documentation :)

I'm using `pylint` here, which uses `PEP-8` as a default configuration. What I want to know here is whether scripts other than the formatter and the validator should also be formatted and ported.

**Comment by pervazea** [comment]
That's good. Thanks.


________________________________

**Comment by apavlo** [comment]
Maybe we should put the formatter and validator in the same folder?

**Comment by schedutron** [comment]
@apavlo Indeed, we can do that, but it may not be a good choice in the long run. I'll try to create a package soon, it simply involves creating a bunch of `__init__.py` files.

**Comment by schedutron** [comment]
@apavlo I've packaged the `script` folder in #1127. Should I also refactor the Python scripts you recently added?

**Comment by tcm-marcel** [comment]
Done in #1127
