### ISSUE TITLE
Move Garbage Collector Thread Setting into SettingsManager

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#1096]
Right now the number of garbage collector threads is hardcoded to one:

https://github.com/cmu-db/peloton/blob/master/src/gc/gc_manager_factory.cpp#L21

We need to move this into the `SettingsManager` so that we can change this more easily:

https://github.com/cmu-db/peloton/blob/master/src/include/settings/settings_manager.h#L29

Eventually we will want to add the ability to dynamically change this parameter and modify the system's configuration through triggers. For now we just need to move it into the `SettingsManager`. We can definite a new parameter called `gc_num_threads` in 'settings.h':

https://github.com/cmu-db/peloton/blob/master/src/include/settings/settings.h

**Comment by pranavk** [comment]
Hi,

I am taking this up unless somebody else is already on it.
