### ISSUE TITLE
New Utility Class for Extracting Information about Query Plan

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#1097]
@saatviks needs to be able to find out what indexes a query will modify without having to actually run it. If it is an INSERT/DELETE, then it will update all tuples. If it is an UPDATE, then it will only affect the indexes that are based on the attributes being modified by the query. The key way this will work is that the function has to be given a `CatalogCache` object, since we want the catalog look-up to be consistent.

We should start building up some utility classes in 'src/include/planner/util' for extracting this information. We can call it `QueryPlanUtil`.

**Comment by pranavk** [comment]
@schedutron  Hmm, I'm also looking into it. Sorry for not updating the status beforehand. Have you already started working on it? If not, do you mind me taking care of this till the weekend ends? :)

Otherwise, no problems at all; you can ignore this message :)
