### ISSUE TITLE
ORDER BY is broken

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1101]
If you run psql_test.sh
(run from the build directory i.e. ../script/testing/psql/psql_test.sh)

the test fails. If you modify the script to leave the psql output file, or run the commands by hand, you can see that the output is not sorted correctly.

**Comment by crd477** [comment]
Is this the cause of the failure in:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fcrdp/detail/jenkins/40/pipeline/18/
for example?

**Comment by apavlo** [comment]
Ugh, we never testing this?

**Comment by pmenon** [comment]
Strange, this is working for me on master.

**Comment by pervazea** [comment]
Prashanth did additional diagnosis using my machine. I'll try to record his findings as accurately as possible below.

The index constructed, is out of order. The plan executed when the test executes "order by", is an index scan. 

Some variations that make this more complicated:

1.  If the table is created with a PRIMARY  KEY, the bug occurs. If you do not create column "id" as a PRIMARY KEY, it works.
1. Prashanth observed that on his machine, a single thread does the work and data is stored in a single tile group. Everything works fine. On my machine, we observed 2 tile groups and the index order is wrong.
1. I tried reducing the number of threads in the thread pool in init.cpp, as Prashanth suggested, for debugging. Peloton segfaults when I do this. I tried 1, 2, 3, 4 threads, with segfaults each time. I would assert that this is not the desired failure mode in response to lack of resources or a configuration error. We'll want to address this later.
1. My machine has 8 cores (4 real, 4 hyperthreads).   Cores can be disabled by setting
/sys/devices/system/cpu/cpuxxx/online e.g. echo 0 |sudo tee /sys/devices/system/cpu/cpu4/online
If I disable the 4 hyperthread cores, leaving my machine as a 4 core machine, everything works. The test passes.

Now... we need to debug why the index has the wrong order.

**Comment by crd477** [comment]
Just for another data point, hyperthreading is enabled on the Jenkins system:
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
...
```
Let me know if you want me to disable it there.

**Comment by pervazea** [comment]
I think we leave hyperthreading on and try to fix the bug ASAP.

________________________________

**Comment by pervazea** [comment]
Running the following SQL, that reproduces the issue: 
CREATE TABLE foo(id integer PRIMARY KEY, year integer);
-- load in the data
INSERT INTO foo VALUES(1, 100);
INSERT INTO foo VALUES(2, 200);
INSERT INTO foo VALUES(3, 300);

With data gathered from DataTable::InsertInIndexes at each instance after INSERT is executed
First time:
Breakpoint 1, peloton::storage::DataTable::InsertInIndexes (
    this=0x7fffb8001840, tuple=0x7ffff1a65890, location=...,
    transaction=0x7fffc0008830, index_entry_ptr=0x7ffff1a65880)
    at /home/pakhtar/proj/master/peloton/src/storage/data_table.cpp:415
415                                     ItemPointer **index_entry_ptr) {

active_indirection_array_id = 0
indirection_offset = 0
$1 = "active indirection array"
$2 = {
  indirections_ = std::unique_ptr<std::array<peloton::ItemPointer, 1000ul>> containing 0x7fffb80256a0,
  indirection_counter_ = {<std::__atomic_base<unsigned long>> = {
      _M_i = 1}, <No data fields>}, oid_ = 13}
$3 = (peloton::ItemPointer *) 0x7fffb80256a0

2018-01-30 16:26:18 [/home/proj/master/peloton/src/storage/data_table.cpp:473:InsertInIndexes] DEBUG - InsertInIndexes: start ScanAllKeys
2018-01-30 16:26:18 [/home/proj/master/peloton/src/storage/data_table.cpp:476:InsertInIndexes] DEBUG - 000: {13, 0}
----
Second INSERT
Breakpoint 1, peloton::storage::DataTable::InsertInIndexes (
    this=0x7fffb8001840, tuple=0x7ffff1a65890, location=...,
    transaction=0x7fffc0007470, index_entry_ptr=0x7ffff1a65880)
    at /home/pakhtar/proj/master/peloton/src/storage/data_table.cpp:415
415                                     ItemPointer **index_entry_ptr) {

active_indirection_array_id = 1
indirection_offset = 0
$4 = "active indirection array"
$5 = {
  indirections_ = std::unique_ptr<std::array<peloton::ItemPointer, 1000ul>> containing 0x7fffb80275f0,
  indirection_counter_ = {<std::__atomic_base<unsigned long>> = {
      _M_i = 1}, <No data fields>}, oid_ = 14}
$6 = (peloton::ItemPointer *) 0x7fffb80275f0
(gdb) c
Continuing.
2018-01-30 16:26:29 [/home/proj/master/peloton/src/storage/data_table.cpp:473:InsertInIndexes] DEBUG - InsertInIndexes: start ScanAllKeys
2018-01-30 16:26:29 [/home/proj/master/peloton/src/storage/data_table.cpp:476:InsertInIndexes] DEBUG - 000: {13, 0}
2018-01-30 16:26:29 [/home/proj/master/peloton/src/storage/data_table.cpp:476:InsertInIndexes] DEBUG - 001: {14, 0}
----
Third INSERT
Breakpoint 1, peloton::storage::DataTable::InsertInIndexes (
    this=0x7fffb8001840, tuple=0x7ffff1a65890, location=...,
    transaction=0x7fffc0008b90, index_entry_ptr=0x7ffff1a65880)
    at /home/pakhtar/proj/master/peloton/src/storage/data_table.cpp:415
415                                     ItemPointer **index_entry_ptr) {

active_indirection_array_id = 0
indirection_offset = 1
$7 = "active indirection array"
$8 = {
  indirections_ = std::unique_ptr<std::array<peloton::ItemPointer, 1000ul>> containing 0x7fffb80256a0,
  indirection_counter_ = {<std::__atomic_base<unsigned long>> = {
      _M_i = 2}, <No data fields>}, oid_ = 13}
$9 = (peloton::ItemPointer *) 0x7fffb80256a8

2018-01-30 16:26:41 [/home/proj/master/peloton/src/storage/data_table.cpp:473:InsertInIndexes] DEBUG - InsertInIndexes: start ScanAllKeys
2018-01-30 16:26:41 [/home/proj/master/peloton/src/storage/data_table.cpp:476:InsertInIndexes] DEBUG - 000: {13, 0}
2018-01-30 16:26:41 [/home/proj/master/peloton/src/storage/data_table.cpp:476:InsertInIndexes] DEBUG - 001: {14, 0}
2018-01-30 16:26:41 [/home/proj/master/peloton/src/storage/data_table.cpp:476:InsertInIndexes] DEBUG - 002: {13, 1}

-----
Should  the active_indirection_array_id change through the test  from 0 -> 1 -> 0?
