### ISSUE TITLE
Wiki contains link to potential malware site

### ISSUE THREAD

**Issue by n3ko1** [cmu-db/peloton#1112]
Hi,

I hope this is the right place to report.

while going through the Wiki I noticed the link "Tips and tricks from an open-source developer" on https://github.com/cmu-db/peloton/wiki/GDB (`http://michael.otacoo.com/manuals/postgresql/`) now leads to a potentially malicious site (heavy ad-ware, at least).

Best
Lucas

**Comment by crd477** [comment]
I modified it to go to the [author's new site](http://paquier.xyz/manuals/postgresql/) instead.

**Comment by apavlo** [comment]
@n3ko1 @crd477 Thank you both!
