### ISSUE TITLE
psql_test.sh failing

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1124]
> ../script/testing/psql/psql_test.sh 
terminate called after throwing an instance of 'peloton::CatalogException'
  what():  Can't find Database postgres to create table
../script/testing/psql/psql_test.sh: line 64:  7025 Aborted                 (core dumped) bin/peloton -port $PELOTON_PORT > /dev/null
***FAIL***

**Comment by pervazea** [comment]
I've run this on PR's  #1101,  #1117 which are both close to master. Not yet run on master but I'm assuming is broken there.

**Comment by crd477** [comment]
I've seen that before too and it appears to me to be an intermittent error.

**Comment by pervazea** [comment]
This particular error is 100%. 

Possibly, this is related to our catalog work. 
We are trying to use database "postgres", which I assume we are now getting from the connection, while previously we had some hard coded notion of "default_database".

**Comment by pervazea** [comment]
This will be addressed in PR #1101, by changing the user to default_database, for the psql_test.sh script.
