### ISSUE TITLE
Error when starting Peloton server

### ISSUE THREAD

**Issue by ZiluTian** [cmu-db/peloton#1129]
Hello, 
I am getting started with Peloton and have some issues when I tried to bring up peloton server. I followed the installation instruction for vagrant. Installation completed successfully with no error. But when I tried to bring up by typing $pelont, I received two error messages complaining about loading root_crt and server certificate, as shown below: 

vagrant@vagrant-ubuntu-trusty-64:~$ peloton -port 5432
2018-02-06 22:03:45 [src/network/peloton_server.cpp:128:SSLInit] ERROR - Exception when loading root_crt!
2018-02-06 22:03:45 [src/network/peloton_server.cpp:137:SSLInit] INFO  - certificate file path /peloton/data/server.crt
2018-02-06 22:03:45 [src/network/peloton_server.cpp:140:SSLInit] ERROR - Exception when loading server certificate!
2018-02-06 22:03:45 [src/network/peloton_server.cpp:267:SetupServer] INFO  - Listening on port 5432

Initially, I thought the errors were fake since the last message seemed to imply the server was running. However, when I brought up the client and attempted to connect by 
$psql "sslmode=disable" -U postgres

I received following error message: 
psql: could not connect to server: No such file or directory. Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I don't think the server is running, despite the "listen" message. But I am not sure why. Any help is greatly appreciated! Thanks! 

Thanks, 
Zilu

**Comment by ZiluTian** [comment]
Also, I noticed the timestamp is wrong. My local machine is 1hr earlier than the timestamp printed out.

**Comment by apavlo** [comment]
You need to connect to it on the right port:

```
psql "sslmode=disable" -U postgres -h localhost -p 15721
```

I will fix the wiki instructions.
