### ISSUE TITLE
Fix Copy() interface to return unique_ptr instead of raw pointers.

### ISSUE THREAD

**Issue by pmenon** [cmu-db/peloton#114]
Fix the interface introduced in #110 to return `unique_ptr` instead of raw pointers. @amaliujia take a look as this is your modification.

**Comment by amaliujia** [comment]
Let's discuss in #110. I left a new comment there.

**Comment by amaliujia** [comment]
Fixed, see #118

**Comment by pmenon** [comment]
Nice job.
