### ISSUE TITLE
Having clause with aggregate expression not supported

### ISSUE THREAD

**Issue by chenboy** [cmu-db/peloton#1146]
Seems like our codegen engine does not support aggregate expression in having clause. When I try to run query `SELECT AVG(a), b FROM test GROUP BY b HAVING AVG(a) = 3.5`, the codegen engine throws an exception 'We don't have a translator for type: AGGREGATE_AVG". 

I'm porting last part of Patrick's capstone project, unnesting sub-query with aggregation, currently I'm blocked by this. Can anyone help me look into this? I think the logic for translating aggregate expression should be similar to transforming tuple value expressions, but I just don't know if we should add transformer for them or just modify the expression tree to use tuple value expression to represent them in the optimizer (which I think is a hack in the old optimizer framework so I get rid of it) ?

The branch I'm working on is [https://github.com/chenboy/peloton/tree/nested_query](https://github.com/chenboy/peloton/tree/nested_query), run `optimizer_sql_test` so you can see the query above being run.

**Comment by pmenon** [comment]
This can probably just be a TVE on the `AVG(a)` output column?

**Comment by chenboy** [comment]
Thanks, I’m going to implement in this way. Just want to make sure this isn’t too hacky.
