### ISSUE TITLE
Copy() in HashRangeExpression is incorrect

### ISSUE THREAD

**Issue by pmenon** [cmu-db/peloton#115]
I don't think the Copy() method in HashRangeExpression is correct. It seems to only copy one of the `N` ranges.  @amaliujia please take a look as this was your modification.

**Comment by amaliujia** [comment]
Sure. I will take a look at it.

**Comment by jarulraj** [comment]
@amaliujia  Is this done ?

**Comment by amaliujia** [comment]
See #135
