### ISSUE TITLE
Refactor CASE expression type

### ISSUE THREAD

**Issue by pmenon** [cmu-db/peloton#116]
Right now, CASE expressions are handled between `CaseExpression` and `OperatorCaseWhenExpression`, where the former relies on the latter throwing exceptions to determine whether when clauses are false.  This is unnecessarily complex.

One solution is to have a single `CaseExpression` class that accepts a list of pairs of expressions as clauses.  The first component of the pair is the "when" condition (either boolean or a value whose type is comparable against the initial expression if one is provided), and the second component is the "then" expression.  An initial idea is something like:

```c++
typedef std::pair<AbstractExpression*, AbstractExpression*> WhenClause;

class CaseExpression {
 public:
  CaseExpression(AbstractExpression* initial, 
                             std::vector<WhenClause> &clauses,
                             AbstractExpression* default);
};
```

Evaluation of a case expression is as simple as iterating over the clauses, evaluating the first component of the pair, and if true, returning the evaluation of the second component of the pair.

**Comment by apavlo** [comment]
@pmenon's assessment and suggested fix is correct.

**Comment by normanyahq** [comment]
Got it. I will take a look.
