### ISSUE TITLE
Multithreaded insert over JDBC doesn't work

### ISSUE THREAD

**Issue by pmenon** [cmu-db/peloton#117]
Concurrently loading a TPC-H dataset using OLTPBench doesn't seem to be working.  Loading the tables serially through OLTPBench does, however, seem to be working.

I haven't dug deep into exactly where the problem is, but figured I'd create a ticket to track the issue.

**Comment by yingjunwu** [comment]
YCSB concurrent insert transaction works. Not sure why it does not work for TPC-H.

btw, at this point of time, single-thread loading will be faster than concurrent loading, as we only have a low-performance b-tree with global mutex utilized to serialize concurrent modifications.

**Comment by jarulraj** [comment]
@pmenon can you add some information on where it is failing ?

**Comment by pmenon** [comment]
Looks like this is a problem with OLTPBench.  The TPC-H loader spawns a per-table thread that's responsible for loading data.  Before actual loading, however, all threads truncate their respective table over a single shared connection. A bad interleaving of begin -> truncate -> commit ends up seg-faulting the system.

I've fixed the issue [here](https://github.com/pmenon/oltpbench/commit/d63b184c5685a8959ba5a5a76fc558c22add8a8b).
