### ISSUE TITLE
Codegen naively generating SSE4.2 intrinsics in some cases

### ISSUE THREAD

**Issue by crd477** [cmu-db/peloton#1171]
I added a bunch of Jenkins worker VMs running our OpenStack cluster last week.  Some of these hypervisors are using older Intel Xeon CPUs (Penryn/Harpertown architecture) which do not have SSE4.2 capabilities.  A new compile-time error appeared when building on these systems.  The error differs slightly between compiler and platform combinations but some artifacts can be seen here:
<http://jenkins.db.cs.cmu.edu:8080/job/crd/job/peloton-crd/job/master/8/consoleText>

The CentOS gcc compiler supplies some particularly helpful information:
```
[CentOS 7/gcc-4.8.5/llvm-3.9.1 (Debug)] /usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/nmmintrin.h:31:3: error: #error "SSE4.2 instruction set not enabled"
[CentOS 7/gcc-4.8.5/llvm-3.9.1 (Debug)]  # error "SSE4.2 instruction set not enabled"
[CentOS 7/gcc-4.8.5/llvm-3.9.1 (Debug)]    ^
```
Adding ```-msse4.2``` to the failing compilation units allows it to finish compiling but this is not the correct fix since it causes several ```make check``` tests to generate:
```Temporary/LastTest.log:LLVM ERROR: Cannot select: intrinsic %llvm.x86.sse42.crc32.64.64 ```

@tcm-marcel says the following:
"I know where the intrinsic comes from, we use it in LLVM code generation
for hashes (see hash.cpp). I don't think we have a workaround for that
if SSE4.2 doesn't exist. (apparently not, because we create it in the IR
and LLVM can't translate it to machine code) But it should be possible
to add a non-SSE version for hashing or choose a different hashing
algorithm."

I suspect this might affect modern AMD CPUs as well but I have not confirmed.  I've removed those Jenkins workers from the pool for the time being since all builds will always fail on those hosts anyway.  In the meantime, I will add more workers on nodes with newer CPUs that have SSE4.2.

**Comment by tcm-marcel** [comment]
@pmenon can you confirm my statement about the CRC intrinsic `%llvm.x86.sse42.crc32.64.64` we use in codegen?

**Comment by pmenon** [comment]
@crd477 @tcm-marcel Correct, we use CRC32 for hashing. We also support Murmur3, but CRC is the default. Considering SSE4.2 is about 10 years old now (I think it was introduced one generation after Penryn), do we want to support older architectures?

**Comment by crd477** [comment]
There's probably not much benefit to supporting older architectures especially if the fix is nontrivial but maybe just add a note to the supported platforms section of the wiki clarifying the requirements.  Perhaps replace, "Please note that it will not compile on 32-bit systems", with, "A 64-bit processor with SSE4.2 support is required", or something?  I've also confirmed (unsurprisingly) that compilation fails on the roadrunner-class nodes in Narwhal, Dual-Core AMD Opteron Processor 2210 HE.

In any case, I've configured our OpenStack cluster to schedule the Jenkins workers only on newer nodes that do have SSE4.2.

**Comment by pmenon** [comment]
I've updated the wiki to list this.

Thanks, @crd477!
