### ISSUE TITLE
Jenkins build fails: PIC error

### ISSUE THREAD

**Issue by tcm-marcel** [cmu-db/peloton#1173]
Jenkins fails in build `Build / Ubuntu Trusty/gcc-4.8.4/llvm-3.7.1 (Debug/Test/LOG_LEVEL_TRACE)` with errors of the following format:

```
/usr/bin/ld.gold: error: <file> requires dynamic R_X86_64_PC32 reloc against <symbol> which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: <file> requires unsupported dynamic reloc 11; recompile with -fPIC
```

* The other builds (gcc4.8 Release and gcc5 Debug + Release) seem not affected. 
* The error occurs on all branches.

**Comment by tcm-marcel** [comment]
Usually we compile everything in peloton as PIC:
https://github.com/cmu-db/peloton/blob/e40dfcbac417c029144fed4af972ce0a1fbdfc45/CMakeLists.txt#L76

**Comment by crd477** [comment]
@tcm-marcel I think it only occurs now after the switch to the ```gold``` linker in #1109.  I can confirm that Fedora 27 also needs the ```-fPIC``` change as hinted at in https://github.com/cmu-db/peloton/pull/1105#issuecomment-369411602
