### ISSUE TITLE
make check fails on Ubuntu Xenial gcc 5.4 Release

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1196]
It has probably been failing for some time. The || true directive was masking these failures.

test/CMakeFiles/optimizer_rule_test.dir/build.make:62: recipe for target 'test/CMakeFiles/optimizer_rule_test.dir/optimizer/optimizer_rule_test.cpp.o' failed

make[3]: *** [test/CMakeFiles/optimizer_rule_test.dir/optimizer/optimizer_rule_test.cpp.o] Error 1
CMakeFiles/Makefile2:7166: recipe for target 'test/CMakeFiles/optimizer_rule_test.dir/all' failed

**Comment by pervazea** [comment]
More specifically, the complain is about:

/usr/include/c++/5/sstream:300:7: error: 'struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs' redeclared with different access

       struct __xfer_bufptrs

       ^

**Comment by tcm-marcel** [comment]
In several test files we have the following line:
https://github.com/cmu-db/peloton/blob/0db1a2a478ce2102451a47c0be14ecb5ecb45e00/test/optimizer/optimizer_rule_test.cpp#L13

This define also overrides all included header files from the libc++. This struct is defined several times inside libc++, but some definitions were not explicitly marked as `private` and once we override they keyword, we and up with several mismatching definitions. 

Some changes in those libc++ header files now lead to this compiler error, so it depends on the version of the header files. 

This define is a ugly hack - is there any better solution than making test cases friends of the classes they test?

**Comment by pmenon** [comment]
@chenboy Can you clean up the tests to remove the `#define` in @tcm-marcel's comments. This is breaking builds on our dev machines as well.

**Comment by pervazea** [comment]
I'm going to try to fix this. Without this, we don't have usable tests on Xenial. This issue is blocking #1194 since Xenial is my development platform.

Discussed options with Marcel. The best option might be to have accessor functions specifically so the tests can get at necessary state. This would require changes to the optimizer classes as well as to the tests. Likely to touch a lot of code.

The next option is to the declare the test classes as friends of the optimizer classes. This is the fix to be attempted.
