### ISSUE TITLE
Deep memcpy needed for peloton_send_dxl()

### ISSUE THREAD

**Issue by mindbergh** [cmu-db/peloton#12]
One memcpy on the whole PlanState struct is not sufficient. Every sub-structs need to be copied as well.

**Comment by jarulraj** [comment]
I think 53414da7 fixes this. Please close this after checking that that's the case.

**Comment by mindbergh** [comment]
We almost fixed the problems.  I tracked the problem and found out that all memory is good except the `RelationData` struct, which is created under another MemoryContext `CacheMemoryContext`. Similarly to what you did at 7915a7e6, I tried to change `CreateCacheMemoryContext()` at `catcache.cpp` to make use of `TopSharedMemoryContext` instead, but system repeatedly crashes upon start. Any suggestions?

**Comment by jarulraj** [comment]
I think we have now solved this problem. We can access all the information in the planstate.
