### ISSUE TITLE
Turn off Fedora builds in Jenkins

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1204]
Fedora builds were enabled in Jenkins, in support of the Tensorflow work. 

1. Tensorflow does not integrate and work (cleanly) as desired, in Fedora. The team is therefore going to abandon Fedora as their platform and switch back, most likely to Ubuntu.

2. We have external contributors (1 known), but no other internal users of Fedora. 

We are therefore going to remove Fedora from the Jenkins builds.

**Comment by crd477** [comment]
Great.  I dislike the rolling release approach that Fedora appears to practice anyway.
