### ISSUE TITLE
Move message_queue to common.

### ISSUE THREAD

**Issue by amaliujia** [cmu-db/peloton#124]
Can @jarulraj move message_queue (https://github.com/cmu-db/peloton/blob/master/src/backend/networking/message_queue.h) to common and rename it?

Such producer-consumer queue is necessary for parallelism and I am using my version too.  Let's create one for everyone who need it.

Can you also add `void Push(const vector<T>& item)` for convenience?

**Comment by jarulraj** [comment]
Feel free to do this and send a PR.

**Comment by yingjunwu** [comment]
I don't find it is necessary to add function like `void Push(const vector<T>& item)`. The semantic is somewhat confusing. Do we need to push a set of items to the queue *atomically*? If yes, then you'd better directly use `queue<std::vector<some_type>>`.

Feel free to comment on my PR #134.
