### ISSUE TITLE
package script exit when executing dnf install invalid package

### ISSUE THREAD

**Issue by Joezc** [cmu-db/peloton#1254]
https://github.com/cmu-db/peloton/blob/3b64df80bc4aff5ec181064087abf1f2100b8034/script/installation/packages.sh#L53

When I was running this script, the script exit when executing this line since I did not install `protobuf` 
on my Fedora before. So, I think this should be edited to be more robust.

**Comment by tcm-marcel** [comment]
We recently decided not to support Fedora for now because of problems with tensorflow.
