### ISSUE TITLE
IndexScanDesc and IndexScanPlan Refactor

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#1300]
We now store a physical pointer of the used index in the `IndexScanDesc` and `IndexScanPlan`. This won't work for "what-if" API because the "fake" index will only have a catalog entry and an OID, but not a pointer to a physical object. The optimizer will crash when generating the `IndexScanPlan` using "what-if" API.

The refactor needs to take the pointer out of the `IndexScanDesc` and `IndexScanPlan`, and replace them with the index OID.

**Comment by apavlo** [comment]
@malin1993ml This is fixed in #1301, right?

**Comment by malin1993ml** [comment]
This issue is fixed in #1301 so I'm closing it. I would add a final comment that we're doing bunch of initialization work in `IndexScanExecutor::DInit()` right now, including generating the `IndexScanPredicate`. We need to do similar work in the LLVM engine as well when we're suppporting index scan in the LLVM engine.
