### ISSUE TITLE
Fix Travis to use gcc5

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1308]
Discontinue use of gcc4.8

**Comment by pmenon** [comment]
Fix Travis **and** Jenkins, yes? Also, modify compile options to explicitly set C++11 standard: `-std=c++11`.

**Comment by pervazea** [comment]
See #1309 for Jenkins, and yes to -std=c++11 (thanks for the correction / reminder)

**Comment by tcm-marcel** [comment]
Should we include other gcc versions in the build? And if yes, in travis or in Jenkins? I would prefer to keep the travis build simple, as it is easier for us the scale the Jenkins builds. 

Adapting the sources to build with clang under Linux is also still open: #1227 (I didn't find time for this yet)

**Comment by pervazea** [comment]
No idea : -)


From what I can see, the docker container for Ubuntu 14.04 only has a single compiler version installed, so no picking is required. What I'm looking to do is to install gcc 5 and use update-alternatives to make gcc 5 the preferred version. This is temporary. Once we update the docker images with dependencies we can have all this pre-configured.


LMK if you think this is wrong or have a better approach.



________________________________

**Comment by crd477** [comment]
On 2018-04-18 18:24, pervazea wrote:
>  From what I can see, the docker container for Ubuntu 14.04 only has a 
> single compiler version installed, so no picking is required.

That is correct.  There are more versions available from the package 
repository but the pre-installed version is whatever the unadorned "g++" 
package refers to: gcc-4.8 in the trusty case, and gcc-5.4 in the xenial 
case.

> What I'm 
> looking to do is to install gcc 5 and use update-alternatives to make 
> gcc 5 the preferred version. This is temporary. Once we update the 
> docker images with dependencies we can have all this pre-configured.
> 

Regarding this and your separate note about updating the docker images 
with all the new dependencies, could you please specify what version(s) 
of the compiler you'd like to have pre-installed?

**Comment by pervazea** [comment]
Superceded by #1309
