### ISSUE TITLE
Packages Script Does Not Check for Protobuf Compilation Errors 

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#1312]
I ran `packages.sh` on my Ubuntu 17.10 machine. It is unable to compile the protobuf dependency but the script just keeps running. There is no indication at the end that the installation failed.

I think you need to check for a non-zero exist code in the `install_protobuf3.4.0` function. 

https://github.com/cmu-db/peloton/blob/master/script/installation/packages.sh#L61

Log is here: [ubuntu-17_10.log](https://github.com/cmu-db/peloton/files/1928960/ubuntu-17_10.log)

**Comment by saatviks** [comment]
Resolved with #1406
