### ISSUE TITLE
Add a column length in ColumnCatalogObject and pg_attribute

### ISSUE THREAD

**Issue by ksaito7** [cmu-db/peloton#1319]
Current catalog::ColumnCatalogObject class and pg_attribute table don't have column length information, although the catalog::Column class has it. Due to this, the checkpoints can't recover the catalog::Column from pg_attribute table.

**Comment by a6802739** [comment]
@ksaito7  I'm new to this project, And I want to try to fix this. One question here is what does the `column_offset` means within `ColumnCatalogObject`?

**Comment by ksaito7** [comment]
@a6802739 This issue has already been implemented in PR #1383 (now reviewing). Could you try other issues?
 `column_offset` means a head location of the column in the table. It seems to be used for storage management to recognize where the column data is in the tuple. For example, assuming that a table has two columns (id interger, value varchar(36)), then id's offset is 0, and value's offset is 4.

**Comment by a6802739** [comment]
@ksaito7  I see, Thanks a lot. Any issue would be fine for me to start, could you just point out another issue which is suitable for a beginner?

**Comment by ksaito7** [comment]
@a6802739 You should choose an issue tagged beginner. Sorry, I don't know which is better. If you want to work for catalog issues, how about  #1414?
