### ISSUE TITLE
What is the correct behavior of a read only txn?

### ISSUE THREAD

**Issue by Nov11** [cmu-db/peloton#1332]
I'm writing a test case for read only txn access mode. 
Suppose x == 0 and two txns run in this order:
```
Txn #1 | Txn #2
----------------
BEGIN  |
W(X,1) |
       | BEGIN R/O
       | R(X) 1st
W(X,2) |
COMMIT | 
       | R(X) 2nd
       | COMMIT
```

I think both of these txns should be able to commit.
Two reads of txn#2 should return the following results. 
Isolation level of txn#1 does not matter.

isolation level of txn#2 | 1st read | 2nd read 
-- | -- | -- 
read committed | 0 | 2 | 
repeatable read | 0 | 0 | 
serializable | 0 | 0

Is my understanding correct?

**Comment by apavlo** [comment]
Yes, this is correct. We currently only support snapshot isolation though so I wouldn't worry about this for your test in #1313.
