### ISSUE TITLE
Change line 7588 in src/index/bwtree_index.cpp to LOG_TRACE

### ISSUE THREAD

**Issue by poojanilangekar** [cmu-db/peloton#1351]
After merging #1190,  the following log message gets printed every epoch:

```[src/index/bwtree_index.cpp:7588:~EpochManager] DEBUG - Clearing the epoch in ~EpochManager()...```

I think this is an overkill and makes the real debug messages get lost. It should be changed to `LOG_TRACE`

**Comment by apavlo** [comment]
Fixed in #1372
