### ISSUE TITLE
Remove Tabs!

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#1416]
This should have been caught in the code review!

https://github.com/cmu-db/peloton/blob/2676275c8ea298cb0fede43e2d9f838a0e6fb57e/src/include/catalog/catalog_cache.h#L53

**Comment by ksaito7** [comment]
Sorry!

**Comment by tli2** [comment]
@ksaito7 https://github.com/cmu-db/peloton/wiki/Formatting this can help you. Also, I remember in CLion you can configure it to automatically format your code (Google C++ style is what we use)

**Comment by ksaito7** [comment]
@til2 Thanks. I will use its script. And I set up my eclipse to use space.
