### ISSUE TITLE
Fatal error under concurrent txns / multiple connections 

### ISSUE THREAD

**Issue by eric-haibin-lin** [cmu-db/peloton#142]
Peloton fails when I have multiple psql connections submitting queries concurrently. 

This is the script I used to submit queries: 

> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> psql < insert.sql &
> 

This is the content of `insert.sql` (only one line) 

> INSERT INTO A1 VALUES(1, 0);

This is the error message I got: 

> psql: FATAL:  could not find relation mapping for relation "pg_tablespace", OID 1213
> psql: FATAL:  could not find relation mapping for relation "pg_proc", OID 1255
> psql: FATAL:  could not find relation mapping for relation "pg_type", OID 1247
> psql: FATAL:  could not find relation mapping for relation "pg_tablespace", OID 1213
> INSERT 0 1
> ERROR:  transaction failed
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> connection to server was lost
> connection to server was lost
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> connection to server was lost
> connection to server was lost
> 

This is what I found in peloton logs (not very informational) 

> 18:17:32,447 [../../src/backend/bridge/dml/mapper/dml_utils.cpp:197:PrepareModifyTableState] INFO  - CMD_INSERT
> 18:17:32,447 [../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:39:TransformModifyTable] INFO  - CMD_INSERT
> 18:17:32,447 [../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:83:TransformInsert] INFO  - Insert into: database oid 12145 table oid 12148: a1
> 2016-04-13 18:17:32.457 EDT   :: FATAL:  invalid syntax in time zone file "Default", line 325
> 2016-04-13 18:17:32.460 EDT yifan yifan :: FATAL:  could not find relation mapping for relation "pg_tablespace", OID 1213
> 2016-04-13 18:17:32.461 EDT yifan yifan :: FATAL:  could not find relation mapping for relation "pg_proc", OID 1255
> 2016-04-13 18:17:32.463 EDT yifan yifan :: FATAL:  could not find relation mapping for relation "pg_type", OID 1247
> 2016-04-13 18:17:32.463 EDT yifan yifan :: FATAL:  could not find relation mapping for relation "pg_tablespace", OID 1213
> 18:17:32,481 [../../src/backend/bridge/dml/mapper/dml_utils.cpp:197:PrepareModifyTableState] INFO  - CMD_INSERT
> 18:17:32,481 [../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:39:TransformModifyTable] INFO  - CMD_INSERT
> 18:17:32,481 [../../src/backend/bridge/dml/mapper/mapper_modify_table.cpp:83:TransformInsert] INFO  - Insert into: database oid 12145 table oid 12148: a1
> 

I can reproduce this problem with the most recent version of peloton using the above script once every ~5 times. Has anyone seen the same issue?

**Comment by jarulraj** [comment]
This problem no longer exists.
