### ISSUE TITLE
Peloton-benchmark performs worse than "weaker" machines

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/peloton#1437]
**Summary**
Benchmark machine has faster CPUs, more CPUs, more memory, but still performs worse on YCSB.

**Details**
- Benchmark machine
  - 32 cores (Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz)
  - YCSB (default): 4-6k
- Comparison machine
  - 8 cores (Intel(R) Core(TM) i7-8550U CPU @ 1.80 GHz)
  - YCSB (default): 8k

Disk space doesn't appear to be an issue.

**Tried without success**
1. Disabling cores on the benchmark machine to also have 8 cores.

This is with a custom branch from @pervazea , however, there's generally been a trend of the benchmark machine reporting poorer numbers.

**Comment by tli2** [comment]
Maybe this has to do with high contention somewhere in our code?

**Comment by mbutrovich** [comment]
If this is single terminal (1 thread), I'm not surprised to see a 6 year-old Sandy Bridge @ 2.2GHz (turbo up to 3.0GHz) getting beaten by a Kaby Lake @ 1.8GHz (turbo up to 4.0GHz) in single-threaded performance.
