### ISSUE TITLE
Peloton performance profiling

### ISSUE THREAD

**Issue by ranxian** [cmu-db/peloton#144]
I have used callgrind to profile Peloton's performance for YCSB and TPCC. If there are something matching your observation (or not), please comment on this.

Major observation
1. Postgres frontend takes big portion of the time  > 50%
2. Peloton IndexScanExecutor::DInit is heavy
3. MVCC (Concurrency Control and Version Chain) is very lightweight, not the bottleneck

I have re-profiled Peloton using debug mode, and there's a discrepancy between what I get now to what I had previously. The breakdown below is not correct, I will update them soon. However the conclusion remains the same: Postsgres frontend is expensive.

Detail stats

TPCC NEW_ORDER
  * ExecutorStart -> InitPlan: 34% (**Postgres frontend** build PlanState tree)
  * exec_bind_message: 18% (**Postgres frontend** Prepare for each JDBC statement, fill up placeholder parameters, etc.)
  * peloton_dml: 16% (**Peloton**)
    * IndexScanExecutor::DInit 6%
    * IndexScanExecutor::Execute 3% (**Real work**)
    * BuildExecutorContext 2%
    * BuildExecutorTree 1.6%
  * BeginTransaction, EndTransaction, CommitTransaction, AbortTransaction: 3% (**Real work**)
  * Other cycles: mostly Postgres frontend

**Comment by tomasic** [comment]
in the front end, can you tell the percentage of time due to planning
versus due to copying between peloton and postgres versus everything else?

On Fri, Apr 15, 2016 at 12:13 PM, Ryan Xian <notifications@github.com>
wrote:

> I have used callgrind to profile Peloton's performance for YCSB and TPCC.
> If there are something matching your observation (or not), please comment
> on this.
>
> Major observation
> 1. Postgres frontend takes big portion of the time > 50%
> 2. Peloton frontend takes another big portion of the > 50%
> 3. Postgres plan cache for prepared statement and Peloton's transform
> cache do work.
> 4. MVCC (Concurrency Control and Version Chain) is very lightweight,
> should not be the bottleneck
>
> Detail stats
>
>    1.
>
>    TPCC NEW_ORDER
>    - ExecutorStart->InitPlan->ExecInitNode : 70%
>       - ExecutorRun: 15%
>          - IndexScanExecutor::Init 6%
>          - UpdateExecutor::Execute 2%
>          - BuildExecutorContext 2%
>          - BuildExecutorTree 1.6%
>       2.
>
>    YCSB READ
>    - ExecutorStart 50%
>       -
>
>       ExecutorRun 35%
>       - PortalRunMulti 10% (Process transaction statement)
>          - PortalRunSelect 20%
>             - IndexScanExecutorInit and Deconstruct: 8%
>             - Executor::Execute: 2%
>             - BuildExecutorContext: 2%
>          -
>
>       CreatePortal 15%
>       3.
>
>    YCSB UPDATE
>    - ExecutorStart 40%
>       - ExecutorRun 60%
>          - BuildExecutorContext 36%
>          - IndexScanExecutor::Init -> 12%
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-db/peloton/issues/144>
>



-- 
Anthony Tomasic
Senior Systems Scientist
Language Technologies Institute
Carnegie Mellon University
http://ideate.cmu.edu/graduate-programs-research/emerging-media/
<http://ideate.cmu.edu/graduate-programs-research/emerging-media/>
http://www.tiramisutransit.com
*http://mcds.cs.cmu.edu <http://mcds.cs.cmu.edu>*
http://www.cs.cmu.edu/~tomasic

**Comment by apavlo** [comment]
I had a meeting today with everyone about this. The decision is that we are going to bite the bullet and start removing Postgres front-end stuff. We think that we can get a new network handler and a preliminary query planner from the class project groups. I think that it would be the same amount of effort to work around these problems so we're just going to start doing it the right way.

We'll discuss more on Tuesday at the team meeting.

**Comment by ranxian** [comment]
I have updated the numbers for profiling TPCC benchmark

**Comment by ranxian** [comment]
@tomasic 
It takes 1/3 of the time for Postgres to build the PlanState tree. Peloton will transform this tree to Peloton's plan tree and execute it. Since Peloton has a cache for such transformation, the copying (if I understand you correctly) will not have too much cost.
However, it **is** expensive to initialize Peloton's executors

**Comment by ranxian** [comment]
I have uploaded the callgrind trace for a 10min run of TPCC NewOrder Transactions. You can use kcachegrind to visualize it

[tpcc-profile-10min.trace.tar.gz](https://github.com/cmu-db/peloton/files/221879/tpcc-profile-10min.trace.tar.gz)

**Comment by tomasic** [comment]
And the plan state is not saved in prepare so we must do something more
extensive?

On Friday, April 15, 2016, Ryan Xian <notifications@github.com> wrote:

> @tomasic <https://github.com/tomasic>
> It takes 1/3 of the time for Postgres to build the PlanState tree. Peloton
> will transform this tree to Peloton's plan tree and execute it. Since
> Peloton has a cache for such transformation, the copying (if I understand
> you correctly) will not have too much cost.
> However, it *is* expensive to initialize Peloton's executors
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-db/peloton/issues/144#issuecomment-210665707>
>


-- 
Anthony Tomasic
Senior Systems Scientist
Language Technologies Institute
Carnegie Mellon University
http://ideate.cmu.edu/graduate-programs-research/emerging-media/
<http://ideate.cmu.edu/graduate-programs-research/emerging-media/>
http://www.tiramisutransit.com
*http://mcds.cs.cmu.edu <http://mcds.cs.cmu.edu>*
http://www.cs.cmu.edu/~tomasic

**Comment by ranxian** [comment]
@tomasic That's correct, the plan state is not cached even for a prepared statement

**Comment by omegaga** [comment]
@tomasic PlanState is a structure containing runtime information, therefore they shouldn't be cached. [This wiki page](https://github.com/cmu-db/peloton/wiki/Query-Plan) discusses some details.

**Comment by mindbergh** [comment]
@apavlo Good to know that we are finally making this move!
