### ISSUE TITLE
Incorrect results with predicate that depends on joined results

### ISSUE THREAD

**Issue by apoms** [cmu-db/peloton#145]
When Peloton transforms a plan from Postgres which has a predicate that can not be pushed down to the scan of a table (such as one that depends on the result of a join), the resulting transformed plan produces incorrect results. See the following pastebin for a test case which shows the problem: http://pastebin.com/JYTEmXuA

This sqlfiddle post shows the correct behavior: http://sqlfiddle.com/#!15/ee9fd/4

**Comment by apavlo** [comment]
I think this is no longer an issue. Closing for now. [Wu Tang](https://www.youtube.com/watch?v=19cjIAK_w1Q).
