### ISSUE TITLE
Repurpose MemSQL machines for Jenkins

### ISSUE THREAD

**Issue by pervazea** [cmu-db/peloton#1458]
In yesterday's meeting of the Peloton team, it was asserted that no-one really uses the MemSQL machines.

Take those machines and re-purpose them. Add them as additional systems for Jenkins to use.

**Comment by crd477** [comment]
Will do.  Are they OK to wipe and reinstall or is there any data that needs to be preserved first?

**Comment by pervazea** [comment]
They are OK to wipe. Please install Ubuntu 18.04 LTS on them. I'll open a separate issue to detail how we start setting things up for Peloton2 (real name to be chosen). Specifying 18.04 because we've agreed to move to the latest versions of many components (including Ubuntu) and deprecate use of older versions. This will simplify the resource / version matrix  considerably.
