### ISSUE TITLE
Data model discussion

### ISSUE THREAD

**Issue by happyjoblzp** [cmu-db/peloton#1459]
As I known, some IMDB, such as Hana/Hyper，use dictionary coding for column. 
The advantages of dictionary coding are the following：
- String conversion to integer, process of integer more efficient
- better compression performance and compression radio
- query process may benefit from dictionary (eg. estimate distinct\count  during join or group by)

Storage structure impact performance.  peloton did not choice dictionary，What is the consideration？

**Comment by apavlo** [comment]
We are in the process of refactoring the code. See last semester's project on adding dictionary compression to Peloton:

https://15721.courses.cs.cmu.edu/spring2018/project-showcase.html
