### ISSUE TITLE
Log files for peloton

### ISSUE THREAD

**Issue by mmmohsen** [cmu-db/peloton#1461]
Hello, 

I'm using a driver to connect to peloton from C code using libpq-fe.h, 
After doing some insert queries the peloton crashes with this error

"""
 server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
"""

and from the terminal I run peloton from ./peloton

I got

"""
terminate called after throwing an instance of 'std::overflow_error'
  what():  ERROR: overflow
Aborted (core dumped)
"""

So is there any log files for peloton so I could determine where the error come from exactly?
or any advice to detect the error.

Operating system: ubuntu 16.04

Thank you a lot in advance,

**Comment by apavlo** [comment]
Compile it in debug mode:

https://github.com/cmu-db/peloton/wiki/Developer-Build

We have only used pqxx to test it.  We haven't tried libpq-fe
