### ISSUE TITLE
Peloton crash on startup when built under ubuntu 17.10 

### ISSUE THREAD

**Issue by thayumanavar77** [cmu-db/peloton#1466]
$ ./bin/peloton 
ASAN:DEADLYSIGNAL
=================================================================
==5655==ERROR: AddressSanitizer: SEGV on unknown address 0x7f47e7f8f128 (pc 0x7f47e2d051bf bp 0x7ffcd6a54150 sp 0x7ffcd6a54150 T0)
==5655==The signal is caused by a WRITE memory access.
    #0 0x7f47e2d051be in _GLOBAL__sub_I_mathlimits.cc (/usr/local/lib/libtensorflow_framework.so+0x3da1be)
    #1 0x7f47ef920ad9  (/lib64/ld-linux-x86-64.so.2+0x10ad9)
    #2 0x7f47ef920bea  (/lib64/ld-linux-x86-64.so.2+0x10bea)
    #3 0x7f47ef910ed9  (/lib64/ld-linux-x86-64.so.2+0xed9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/local/lib/libtensorflow_framework.so+0x3da1be) in _GLOBAL__sub_I_mathlimits.cc
==5655==ABORTING

**Comment by apavlo** [comment]
We are refactoring the code. This repository will be abandoned soon.
