### ISSUE TITLE
Data model and query language like EdgeDB

### ISSUE THREAD

**Issue by ansarizafar** [cmu-db/peloton#1469]
EdgeDB has a better data model and query language than any other relational database management system. Please consider using similar features.

https://edgedb.com/
https://edgedb.com/blog/edgedb-a-new-beginning

**Comment by apavlo** [comment]
@ansarizafar It looks like they just have extended SQL to support graph traversal and write results as JSON. The latter is easy to do, but I don't see how having non-standard SQL extensions is a good thing.

**Comment by ansarizafar** [comment]
The reasons are mentioned in the blog post https://edgedb.com/blog/edgedb-a-new-beginning

> However, relational databases are built on a model that is decades old and which becomes increasingly inadequate for the rapidly transforming software development field. Certainly, PostgreSQL is being constantly improved with features like advanced JSON support, query parallelization, and a JIT compiler to boost the performance of complex queries even further. However, the way applications interface with a relational database did not change meaningfully. We still use slow ORMs, struggle with schema migrations and write poor ad-hoc SQL queries.

> Most software engineers don’t think in tables. Our programming languages are built around higher-level abstractions like types and objects. If you have two objects A and B and want to reference one from another, you would just write A.b = B. To do the same in a relational database, you would need to deal with foreign keys, joins, and sometimes intermediate tables, essentially working directly at a much lower level of abstraction. This inconsistency between relational databases and modern programming languages has been known for a while, and even has a name: object-relational impedance mismatch. It is the reason why ORMs are so popular and why there is so much interest around technologies like GraphQL. The problem with these solutions is that they attempt to bridge the gap from the application side, and either sacrifice the expressive power of the underlying database, or implement an overly complex mapping which largely defeats the purpose. While the industry seems to be obsessed with solving the problems of scale, there are no serious attempts to solve the object-relational mismatch on the database side.
