### ISSUE TITLE
Could not install peloton:error: ‘new’ of type ‘peloton::storage::TupleHeader’ with extended alignment 64 [-Werror=aligned-new=]  

### ISSUE THREAD

**Issue by peijialing** [cmu-db/peloton#1481]
When I was trying to install packages using sudo bash packages.sh, I get the following info:
`Err:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
  Could not connect to us.archive.ubuntu.com:80 (91.189.91.23). - connect (111: Connection refused) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to us.archive.ubuntu.com:80 (91.189.91.26). - connect (111: Connection refused) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
Err:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
Err:3 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
Err:4 http://dl.google.com/linux/chrome/deb stable InRelease
  Could not connect to dl.google.com:80 (172.217.6.238). - connect (111: Connection refused) Cannot initiate the connection to dl.google.com:80 (2607:f8b0:4006:80e::200e). - connect (101: Network is unreachable)
Err:5 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Could not connect to security.ubuntu.com:80 (91.189.88.162). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.152). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.26). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.161). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.23). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.149). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
Hit:6 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease
Reading package lists... Done                              
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to us.archive.ubuntu.com:80 (91.189.91.23). - connect (111: Connection refused) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to us.archive.ubuntu.com:80 (91.189.91.26). - connect (111: Connection refused) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Could not connect to security.ubuntu.com:80 (91.189.88.162). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.152). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.26). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.161). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.23). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.88.149). - connect (111: Connection refused) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable)
W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/InRelease  Could not connect to dl.google.com:80 (172.217.6.238). - connect (111: Connection refused) Cannot initiate the connection to dl.google.com:80 (2607:f8b0:4006:80e::200e). - connect (101: Network is unreachable)
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.15.1-3ubuntu2).
bison is already the newest version (2:3.0.4.dfsg-1build1).
cmake is already the newest version (3.10.2-1ubuntu2).
flex is already the newest version (2.6.4-6).
g++ is already the newest version (4:7.3.0-3ubuntu2).
libboost-dev is already the newest version (1.65.1.0ubuntu1).
libboost-filesystem-dev is already the newest version (1.65.1.0ubuntu1).
libboost-thread-dev is already the newest version (1.65.1.0ubuntu1).
libedit-dev is already the newest version (3.1-20170329-1).
libevent-dev is already the newest version (2.1.8-stable-4build1).
libffi-dev is already the newest version (3.2.1-8).
libffi6 is already the newest version (3.2.1-8).
libtool is already the newest version (2.4.6-2).
llvm-3.9 is already the newest version (1:3.9.1-19ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
postgresql-client is already the newest version (10+190).
unzip is already the newest version (6.0-21ubuntu1).
valgrind is already the newest version (1:3.13.0-2ubuntu2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
clang-3.9 is already the newest version (1:3.9.1-19ubuntu1).
lcov is already the newest version (1.13-3).
libeigen3-dev is already the newest version (3.3.4-4).
libgflags-dev is already the newest version (2.2.1-1).
libjemalloc-dev is already the newest version (3.6.0-11).
libpqxx-dev is already the newest version (4.0.1+dfsg3-8).
libtbb-dev is already the newest version (2017~U7-8).
curl is already the newest version (7.58.0-2ubuntu3.3).
git is already the newest version (1:2.17.1-1ubuntu0.1).
libssl-dev is already the newest version (1.1.0g-2ubuntu4.1).
ant is already the newest version (1.10.3-1ubuntu0.1).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libprotobuf-dev' is not installed, so not removed
Package 'protobuf-compiler' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
W: --force-yes is deprecated, use one of the options starting with --allow instead.
libprotoc 3.4.0
protobuf-3.4.0 already installed
` 

And when I tried to build and install with the make -j4 command, I found the following error:
`[  1%] Built target capnp

[  1%] Built target peloton-capnp

[  3%] Built target peloton-proto

[ 14%] Built target pg_query

[ 14%] Building CXX object src/CMakeFiles/peloton.dir/storage/tile_group_header.cpp.o

[ 14%] Building CXX object src/CMakeFiles/peloton.dir/tuning/clusterer.cpp.o

[ 14%] Building CXX object src/CMakeFiles/peloton.dir/traffic_cop/traffic_cop.cpp.o

[ 14%] Building CXX object src/CMakeFiles/peloton.dir/trigger/trigger.cpp.o

[ 14%] Building CXX object src/CMakeFiles/peloton.dir/tuning/index_tuner.cpp.o

/home/jialing/Documents/software/peloton/src/storage/tile_group_header.cpp: In constructor ‘peloton::storage::TileGroupHeader::TileGroupHeader(const peloton::BackendType&, const int&)’:

/home/jialing/Documents/software/peloton/src/storage/tile_group_header.cpp:40:51: error: ‘new’ of type ‘peloton::storage::TupleHeader’ with extended alignment 64 [-Werror=aligned-new=]
   tuple_headers_.reset(new TupleHeader[tuple_count]);
                                                   ^
/home/jialing/Documents/software/peloton/src/storage/tile_group_header.cpp:40:51: note: uses ‘void* operator new [](std::size_t)’, which does not have an alignment parameter
/home/jialing/Documents/software/peloton/src/storage/tile_group_header.cpp:40:51: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
[ 14%] Building CXX object src/CMakeFiles/peloton.dir/tuning/layout_tuner.cpp.o
cc1plus: all warnings being treated as errors
src/CMakeFiles/peloton.dir/build.make:8582: recipe for target 'src/CMakeFiles/peloton.dir/storage/tile_group_header.cpp.o' failed
make[2]: *** [src/CMakeFiles/peloton.dir/storage/tile_group_header.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1199: recipe for target 'src/CMakeFiles/peloton.dir/all' failed
make[1]: *** [src/CMakeFiles/peloton.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`
Make failed and I did not understand why.

**Comment by apavlo** [comment]
The network problem is at your end. We're just using `apt-get`.

We have not tried to compile Peloton with gcc C++17. Our target is C++11 with gcc5.
