### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by haocoder** [cmu-db/peloton#1487]
when I built by 
`cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_SANITIZER=Address -DCMAKE_CXX_FLAGS="-DLOG_LEVEL=LOG_LEVEL_TRACE" ..
make -j4` 
there is wrong with `/usr/include/llvm-3.9/llvm/Support/Compiler.h:389:39: fatal error: sanitizer/asan_interface.h: No such file or directory`

**Comment by apavlo** [comment]
I don't think your environment is setup correctly:

https://github.com/cmu-db/peloton/wiki/Installation#ubuntu-quick-setup

**Comment by haocoder** [comment]
thank you, I have fixed my problem, it's my environment incorrect
