### ISSUE TITLE
cannot build Peloton with GCC 7.0+

### ISSUE THREAD

**Issue by zgf** [cmu-db/peloton#1491]
When trying to build peloton:
`/home/guofzh/repos/peloton/src/storage/tile_group_header.cpp: In constructor ‘peloton::storage::TileGroupHeader::TileGroupHeader(const peloton::BackendType&, const int&)’:
/home/guofzh/repos/peloton/src/storage/tile_group_header.cpp:40:51: error: ‘new’ of type ‘peloton::storage::TupleHeader’ with extended alignment 64 [-Werror=aligned-new=]
   tuple_headers_.reset(new TupleHeader[tuple_count]);
                                                   ^
/home/guofzh/repos/peloton/src/storage/tile_group_header.cpp:40:51: note: uses ‘void* operator new [](std::size_t)’, which does not have an alignment parameter
/home/guofzh/repos/peloton/src/storage/tile_group_header.cpp:40:51: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
[ 92%] Building CXX object src/CMakeFiles/peloton.dir/threadpool/worker_pool.cpp.o`

gcc and OS version: gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

**Comment by apavlo** [comment]
We are not supporting this repo anymore. It won't work on newer versions of gcc.

**Comment by llvim** [comment]
@apavlo peloton is DEPRECATED?  is there any new project?

**Comment by apavlo** [comment]
@llvim Yes. Announcement coming later in 2019.

**Comment by rurban** [comment]
> @apavlo peloton is DEPRECATED? is there any new project?

He probably means Terrier

**Comment by baiwfg2** [comment]
@zgf  I built it successfully with gcc 7.2. You can see the details from https://docs.google.com/document/d/1SqHj82x7xRDvxjZS0c-Lf8JbWTSiFoNC1fPcL9GLIvU
