### ISSUE TITLE
Catalog::Manager is not scalable

### ISSUE THREAD

**Issue by ranxian** [cmu-db/peloton#155]
I'm profiling YCSB benchmark on a multicore system. On a system with 12 cores 24 threads, the throughput can't grow when more than 12 cores are used for read only workload. After profiling, I found that when using 24 cores, half of the cycles are spent in `_raw_spin_lock`, which is a linux syscall used by C++ `std::mutex`. The callgraph showed that in this workload it is mainly used by `Catalog::Manager#GetTileGroup()`, 

```
std::shared_ptr<storage::TileGroup> Manager::GetTileGroup(const oid_t oid) {
  std::shared_ptr<storage::TileGroup> location;

  {
    std::lock_guard<std::mutex> lock(locator_mutex);
    // Check if the tile group exists in the lookup directory
    if (locator.find(oid) != locator.end()) {
      location = locator.at(oid);
    }
  }

  return location;
}
``` 

Here `locator` is a `std::unordered_map`. I have tried that either use our own spinlock or replace `locator` with cuckoo hashmap will solve this problem.

![image](https://cloud.githubusercontent.com/assets/1311188/14937363/2fc87456-0ed3-11e6-9595-dbbf18bb026d.png)

**Comment by apavlo** [comment]
This is a big problem. I warned @jarulraj about this before. We should fix this.

**Comment by jarulraj** [comment]
Sure, replace it with a spinlock or go for a lockfree hash map. Make sure that correctness is not affected.

**Comment by pmenon** [comment]
Why are tiles owned by the singleton manager and not by the tables they belong to? Using a concurrent map will definitely help, but changing this architecture should help a great deal moving forward when we have concurrent queries and scans that touch all the tiles, no?

**Comment by yingjunwu** [comment]
Agree. Actually the initial design did not consider multi-tenancy problem. Multiple databases can collocate on the same machine. Currently, all the databases on a single machine are instantiated in the same process, and these databases will request tiles from the same tile_factory. This design is unscalable and cannot guarantee fair resource sharing. We may need to rewrite the storage layer in the future.

**Comment by jarulraj** [comment]
@pmenon Yes, we can add another layer of indirection, something like this (table id, tile group id). But, the high-level idea is that tile groups are large enough that the overhead of these table lookups get amortized across a lot of tuples.

@yingjunwu I don't really understand what you are suggesting. At the end of day, everything will hit `malloc`. If we allocate big chunks of memory (i.e. tiles), then we should not be bottlenecked by the allocator.

**Comment by yingjunwu** [comment]
We have fixed it.
