### ISSUE TITLE
tile group scalability

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#156]
when all the tuples in a tile group are allocated, a new tile group must be allocated by a certain thread. All the other threads must be busy waiting until the new tile group is allocated. This operation is not scalable.

probably we should maintain a tile group cache for each thread (core).

**Comment by yingjunwu** [comment]
Move data members from the executor nodes to the plan nodes to avoid initialization of executor nodes.

**Comment by jarulraj** [comment]
@saifalharthi finished moving data members from the executor nodes to the plan nodes.
