### ISSUE TITLE
boost bug

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#166]
Hi, boost lockfree queue has an unfixed bug which can result in valgrind error: https://svn.boost.org/trac/boost/ticket/8395. This bug has not been fixed (although identified) in the most recent library.

I am sorry for introducing the following two files to the master branch: https://github.com/cmu-db/peloton/blob/master/src/backend/common/lockfree_spsc_queue.h, https://github.com/cmu-db/peloton/blob/master/src/backend/common/lockfree_queue.h.

While the current master version is unaffected by this bug, I will remove these two lockfree queues later. Please do not use these two structures for now.

Thanks the concurrency control team @ranxian @jessesleeping @runshenzhu  for identifying this problem.

@saurabhkadekodi @dingty please mind this problem.

**Comment by jarulraj** [comment]
Maybe you can replace the `boost queue` with this one (with BSD license) : 
https://github.com/cameron314/concurrentqueue ?
http://moodycamel.com/blog/2013/a-fast-lock-free-queue-for-c++

**Comment by jarulraj** [comment]
Fixed this by replacing `boost` queue with `concurrentqueue`.
