### ISSUE TITLE
questions about tile based join operator

### ISSUE THREAD

**Issue by runshenzhu** [cmu-db/peloton#17]
This page: https://github.com/cmu-db/peloton/wiki/Tile-Based-Architecture describes the tile Based Architecture of peloton and provides some examples.

I have a question of last example (Join Operator in Logical Tile Algebra). Why the meta-data of logical tile Z are (TILE R ATTR B, TILE R ATTR C) and (TILE R ATTR B, TILE R ATTR C), instead of (TILE R ATTR B, TILE R ATTR C) and (TILE S ATTR Y, TILE S ATTR Z)?

**Comment by ranxian** [comment]
I agree with you, it should be a mistake in the writeup

**Comment by jarulraj** [comment]
You are right. I fixed the picture. Thanks for the heads up.
