### ISSUE TITLE
[Wiki] Installation script

### ISSUE THREAD

**Issue by chouclee** [cmu-db/peloton#18]
Running the dependency script will give me error message "There are problems and -y was used without --force-yes".

Adding --force-yes flag before -y can solve this error.

My OS: Ubuntu 14.04.3 desktop amd64bit

**Comment by jarulraj** [comment]
There might be problems in your installation. Quoting from http://manpages.ubuntu.com/manpages/raring/man8/apt-get.8.html :

> --force-yes is a dangerous option that will cause apt to continue without prompting if it is doing something potentially harmful. It should not be used except in very special situations.

So, I think it is a bad idea to add that flag.
