### ISSUE TITLE
temp table

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#183]
A transaction needs to create a temp table if an aggregation operator is performed. Our current implementation treats such a temp table equally as a regular database table, which means that every temp table has to be registered to the catalog, causing unnecessary synchronization overhead. Meanwhile, some aggregation operations, such as sum, count, max, min, generates only one output tuple. using a regular database table to maintain the query results wastes memory spaces, as every data table in our implementation has to have at least one tile group, which can maintain 1,000 tuples.

We should develop a new `temp_table` class to maintain results for aggregation queries.

**Comment by poojanilangekar** [comment]
Fixed in #409
