### ISSUE TITLE
gtest doesn't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#184]
I upgraded to Ubuntu 16.04. There were a few minor things that I had to fix to get it to compile, but the errors for gtest under `make check` are a bit much for me to fix:

http://pastebin.com/raw/4jq2PVLx

Here is my environment:
* Ubuntu 16.06
* 4.4.0-22-generic
* g++ (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413

**Comment by saifalharthi** [comment]
I setup a VM same as yours to check which files have this problem.
Only two files fail when doing `make check`
common/cache_test.cpp
language/namespace_test.cpp

I removed them from their "Makefile.am" and everything else compiled with no problems.
Every test passed expect for "recovery_test" , I don't know if there is a problem there.

I will try to check out the compilation messages as they seem similar.

**Comment by jarulraj** [comment]
Using `g++ 5.3` should no longer be a problem.
https://travis-ci.org/cmu-db/peloton/jobs/140169967

**Comment by apavlo** [comment]
Beautiful:

```
pavlo@trajan:/tmp/peloton/build$ make check
⋮
100% tests passed, 0 tests failed out of 70
```

Nice work!
