### ISSUE TITLE
Debugging logger

### ISSUE THREAD

**Issue by jarulraj** [cmu-db/peloton#19]
We rely on an ad-hoc macro based [logger](https://github.com/cmu-db/peloton/blob/master/src/backend/common/logger.h). 

1. We need to ensure that the default logging levels are sane. Right now, we default to `LOG_LEVEL_INFO` when DEBUG is not defined, and default to `LOG_LEVEL_OFF` when NDEBUG is defined.

2. We need to decide whether we would like to have a trailing newline  by default or not.

3. We need to inherit all printable objects from an abstract class, and force them to implement a `Debug` function. Then, we can overload the I/O operator just once for this class.

**Comment by wangziqi2013** [comment]
Bar.

**Comment by jarulraj** [comment]
That was a quick response :+1:

**Comment by wangziqi2013** [comment]
I will delete that

**Comment by jarulraj** [comment]
Fixed 1 and 2.

**Comment by jarulraj** [comment]
Added an abstract `Printable` class with a `GetInfo` function in afb253fe4a4f10bb4f778160f1f7a51a20466173.
