### ISSUE TITLE
super slow string comparison

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#192]
The string comparison in our btree index is (at least) one order of magnitude slower than int comparison. This is a major bottleneck in our TPC-C benchmark. I think we might borrow idea from masstree, which interprets a single string as multiple integers when performing comparison.

**Comment by apavlo** [comment]
You are talking about dictionary compression, which should be done at the
database level and not the index level.

**Comment by ranxian** [comment]
I think he's saying that one integer is 4 chars, so that number of
comparisons will be 4 times less

On Tuesday, June 14, 2016, Andy Pavlo <notifications@github.com> wrote:

> You are talking about dictionary compression, which should be done at the
> database level and not the index level.
> On Jun 13, 2016 11:30 PM, "Yingjun Wu" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > The string comparison in our btree index is one order of magnitude slower
> > than int comparison. This is a major bottleneck in our TPC-C benchmark. I
> > think we might borrow idea from masstree, which interprets a single
> string
> > as multiple integers when performing comparison.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/cmu-db/peloton/issues/192>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAr03Yalskl3PKI_dJASIbmKy4AYEuoEks5qLiA8gaJpZM4I07hw
> >
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmu-db/peloton/issues/192#issuecomment-225901476>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABQB1Nj8GKWmQefa2PdpgGBZXArMOWM7ks5qLrxegaJpZM4I07hw>
> .
>


-- 
Best regards,

Ran (Ryan) Xian
Master of Computational Data Science
School of Computer Science
Carnegie Mellon University

**Comment by yingjunwu** [comment]
yep @ranxian understood correctly. If we want to compare two strings, we can compare the first 4 bytes of two strings as integer comparison and then compare the second 4 bytes.

Masstree highly optimized its string operations and directly stores a string as an array of integers.

**Comment by pmenon** [comment]
I don't think the approach in Masstree will work for UTF/Unicode strings, since it doesn't do any form of collation.
