### ISSUE TITLE
Add TileGroup schema info into checkpoints

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#195]
For @pmenon's project, we need to make sure that we can reload a database from a checkpoint with the exact same schema.

I'm going to add a new `LogRecord` type and write it out when iterate over the `TileGroups` in `SimpleCheckpoint`.

https://www.youtube.com/watch?v=2Zm7qm51Rnk

**Comment by apavlo** [comment]
I've been poking at this for a while. There is some stuff in here about checking for torn writes so they deserialize things in two parts. I think that the correct approach is to use a checksum in the log record header to check for correctness. It's going to take me a while to refactor but I'm on it.

**Comment by poojanilangekar** [comment]
@ksaito7 would be working on Checkpoints next semester. Closing this issue.
