### ISSUE TITLE
Failing on TPC-C with OLTPBench

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#205]
For now, Peloton can successfully run the NewOrder transaction in TPC-C.

For Payment, the transaction fails to execute until customerByNameSQL. The query can be successfully executed on the Peloton side. But the OLTPBench side cannot read the result back:
15:26:21,203 (Worker.java:403) DEBUG - Payment/02 Bad value for type timestamp/date/time: {1} 0 - 22007

For OrderStatus, it fails on the same customerByNameSQL:
16:17:03,244 (Worker.java:403) DEBUG - OrderStatus/03 Bad value for type timestamp/date/time: {1} 0 - 22007

For Delivery, we actually can already run it without any debugging! Surprise:)

For StockLevel, if fails on stockGetCountStockSQL. We need to be able to handle alias:
16:19:06,238 (Worker.java:403) DEBUG - StockLevel/05 The column name STOCK_COUNT was not found in this ResultSet. 0 - 42703

**Comment by saifalharthi** [comment]
I pushed a commit to my fork for supporting aliases. Please pull the changes and test it on the last query.

**Comment by saifalharthi** [comment]
This is done , I pushed the fix for that and OrderStatus runs now and Payment should run as well.

**Comment by malin1993ml** [comment]
The two old issues on TPC-C was fixed by @saifalharthi, thanks!

Now we have some new issues since we can reach more queries after the above fixes.
StockLevel:
The query stockGetDistOrderIdSQL doesn't always retrieve correct the answer from Peloton. It will succeed on the first few queries and the return a random big number after that. Also, we seems to return NULL instead of 0 when there's no tuple satisfying the predicate of stockGetCountStockSQL. That should be fixed.

OrderStatus and Payment:
The transaction keeps retrying the execution for some reason.
19:41:10,583 (Worker.java:375) DEBUG - execute status: RETRY_DIFFERENT

**Comment by saifalharthi** [comment]
I am working on fixing this and pushed a commit to my repo that runs StockLevel successfully ( according to OLTPBecnhmark). However , there are still some problems.

In stockGetDistOrderId the query is correctly executed from Peloton side , yet OLTPBench seems to get and assign a different result. I made sure that the result left peloton (at least reached the function where it sends the results to he client) is correct. So I will try to use wireshark and see to determine if its still a problem from our wire protocol or from OLTPBench.

For stockGetCountStock, I hardcoded the input for O_ID to check if the query runs with no problems and it did. However , as Lin pointed out when there are no tuples to satisfy the predicates it returns NULL rather than 0. I will find a fix for that.

**Comment by malin1993ml** [comment]
The wrong answer problem of the StockLevel is already fixed in #284. Two things:
(1) In Postgres JDBC driver, transactions will first execute as unnamed prepared statement (got planned every time) until PrepareThreshold is reached:
https://jdbc.postgresql.org/documentation/81/server-prepare.html
The default PrepareThreshold is 5.
(2) Unmaned prepared statement and named ones are using different value format (text/binary). The correct format codes are specified by Bind (F) message before Execute (F) message:
https://www.postgresql.org/docs/9.1/static/protocol-message-formats.html

BTW, we were also getting wrong answer with NewOrder before, it's just we didn't check that. Now that's also fixed.

**Comment by malin1993ml** [comment]
Also, #284 and Matt's fix #273 fixed some of the retrying problem of Payment transaction. Now Payment sometimes can succeed:

> 16:16:57,597 (Worker.java:374) DEBUG - execute status: SUCCESS
> 16:16:57,597 (Worker.java:466) DEBUG - Executed a new invocation of Payment/02
> run time exception: java.lang.RuntimeException: C_LAST=ABLEPRESPRI C_D_ID=1 C_W_ID=1 not found!
> 16:16:57,671 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> 16:16:57,796 (Worker.java:374) DEBUG - execute status: SUCCESS
> 16:16:57,797 (Worker.java:466) DEBUG - Executed a new invocation of Payment/02
> run time exception: java.lang.RuntimeException: C_LAST=ABLEOUGHTPRES C_D_ID=2 C_W_ID=1 not found!
> 16:16:57,871 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> run time exception: java.lang.RuntimeException: C_LAST=PRESCALLYPRES C_D_ID=1 C_W_ID=1 not found!
> 16:16:57,972 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT

For OrderStatus, Peloton is still always retrying:

> 16:17:38,771 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> run time exception: java.lang.RuntimeException: C_LAST=ABLEPRIPRES C_D_ID=2 C_W_ID=1 not found!
> 16:17:38,871 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> run time exception: java.lang.RuntimeException: C_LAST=OUGHTPRIPRES C_D_ID=2 C_W_ID=1 not found!
> 16:17:38,971 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> run time exception: java.lang.RuntimeException: No orders for O_W_ID=1 O_D_ID=1 O_C_ID=487
> 16:17:40,372 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> run time exception: java.lang.RuntimeException: No orders for O_W_ID=1 O_D_ID=1 O_C_ID=739
> 16:17:39,072 (Worker.java:374) DEBUG - execute status: RETRY_DIFFERENT
> run time exception: java.lang.RuntimeException: C_LAST=EINGABLEANTI C_D_ID=2 C_W_ID=1 not found!

For both transaction types, Peloton sometimes cannot find the customer with specific last name. For OrderStatus, Peloton cannot find orders even the customer is found. I haven't checked whether we have inserted the customer with that last name in the first place, but we should have inserted orders for all customers with ID smaller than 1000. But we still couldn't get those orders in Peloton.

@sid1607 Can you have a look at this issue? Thanks!

**Comment by sid1607** [comment]
I'll look into it

**Comment by malin1993ml** [comment]
@sid1607 FYI, some constants in TPC-C are set here:
https://github.com/cmu-db/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/jTPCCConfig.java

I have decreased some numbers to make the test faster.

**Comment by sid1607** [comment]
OLTPBench retries ORDER_STATUS transactions because it receives empty result sets for two of the queries (ordStatGetNewestOrdSQL and customerByNameSQL). Running the same failing queries on PSQL returns the expected tuple. It seems like the problem is when the ORDER BY clause is used - I removed this clause from the two failing ORDER_STATUS  queries  and the benchmark is able to proceed. Debugging Peloton showed that in order_by_executor.cpp, when DoSort() is called, an index scan is performed as part of a child operator in the query plan. This index scan returns 0 tuples when we use OLTPBench and the required tuple when we run using PSQL.

**Comment by apavlo** [comment]
This is really bizarre. Is the result payload that gets sent back the same?

**Comment by sid1607** [comment]
Do you mean the result payload for the query with the ORDER BY clause? In case of OLTPBench, Peloton is not able to find the required row while executing the query's predicates. From PSQL, everything works fine.

**Comment by apavlo** [comment]
I mean whatever the query result is before we send it back to the client.

**Comment by sid1607** [comment]
No, the result we retrieve before sending it back to the client is different. We get 0 rows when we send the query from OLTPBench and the expected row when we send the row from PSQL. This doesn't seem to be wire protocol problem - in the sense that it is not like we are sending the required result data over the wire and JDBC isn't able to process it.

**Comment by malin1993ml** [comment]
Fixed by PR [#297].
