### ISSUE TITLE
Coverage Generation & Uploading Does Not Work

### ISSUE THREAD

**Issue by wangziqi2013** [cmu-db/peloton#212]
Description
=========
Coverage generation does not work in a sense that there is no .gcno AND/OR .gcda file generated from "make check" command even if we turn on the flag by "-DCOVERALLS=ON"

Also coverage data is not properly uploaded, either because of the data not being properly generated or because of other problems in the build system

Status
=====
Currently I have fixed the first one - gcda and gcno files are generated inside the build tree directories, by adjusting the order that we generate make file for "tests" folder and the materialization of compiler/linker flags

For the second issue, if I could not fix it tonight then probably I will switch to cpp-coverall which is another independent tool for uploading coverage data

**Comment by apavlo** [comment]
@jessesleeping Please check with @wangziqi2013 about this problem. This is something that we want to fix quickly so that we have it for the rest of the semester.

**Comment by jessesleeping** [comment]
Ok.

**Comment by jessesleeping** [comment]
I think I have fixed this issue. Basically we need to add the coverage CXX/C flag before we generate the configure file. For further test, @jarulraj can you grant me the permission to get the Travis repo token?

**Comment by jarulraj** [comment]
@jessesleeping has fixed this issue.
