### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#214]
jenkins performs tests under debug mode. However, when using release mode, `parser_test` and `create_index_test` will fail. Please fix it.

**Comment by malin1993ml** [comment]
The problem doesn't exist when building from a clean clone. It seems that CMake couldn't recognize the changes in some files (probably parser related files).

**Comment by yingjunwu** [comment]
Agreed. This problem disappeared after cleaning up all the files under `build` folder.

**Comment by jarulraj** [comment]
Then, let's close this issue.
