### ISSUE TITLE
Clean-up + Revive WAL Component

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#222]
The WAL code was abused this summer. Nobody is sure whether it is still working (but probably not). Since @MattPerron wrote a lot of it last semester, he should go through and tidy things up to start the semester.

I also have a branch that I started with some fixes that we should eventually merge in. Not all of these items have been implemented:

* Add BEGIN/END markers to each log record
* Record a checksum for each block of log records
* Move all the serialization code out of the worker thread

We are also going to need to switch the serialization code to use the original H-Store SerializeIO class. We will need to coordinate on this.

**Comment by yingjunwu** [comment]
Logging subsystem has already been revived. New logging subsystem is on the way.
