### ISSUE TITLE
SELECT * queries return only a single tuple on PSQL

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#229]
Despite creating and populating a table with multiple tuples on PSQL, a ``SELECT *`` query only returns a single tuple. The problem has been found to be associated with Query Plan Executor.

**Comment by apavlo** [comment]
This is something we should definitely fix.

**Comment by sid1607** [comment]
It seems like this no longer an issue. The current version runs these queries as expected. Perhaps we should add a test for this into Travis?
