### ISSUE TITLE
Failure of JOIN queries on PSQL

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#230]
Join queries on PSQL crash by throwing
``` 
throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```

**Comment by apavlo** [comment]
Is there a stack trace?

**Comment by saifalharthi** [comment]
I think Joins were not supported , I think we only created a hack join for TPCC and looking at the code here https://github.com/cmu-db/peloton/blob/master/src/optimizer/simple_optimizer.cpp#L98

You can see that if it the select statement has more than one table then it will go to the "CreateHackingJoinPlan" function and it will assume that the tables are the same tables in tpcc's StockLevel second query.

**Comment by apavlo** [comment]
Replaced by #243
