### ISSUE TITLE
LOG_LEVEL_TRACE broken due to new type/value system

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#236]
Because the new type/value system has a slightly different interface than then old one, some LOG_TRACE statements that use the old system interface are broken.

This will not be checked through either Travis or Jenkins. I'm thinking whether it's a good idea to check whether the system can be built successfully with LOG_TRACE on Jenkins.

**Comment by apavlo** [comment]
Maybe we should enable TRACE on Jenkins.

**Comment by malin1993ml** [comment]
I think we could build the system twice on Jenkins. First try to build with TRACE to see whether it succeeds. The second time build and run "make check" in release mode to avoid giant log output.

**Comment by ranxian** [comment]
@malin1993ml 

Is **broken** means compile error or something else? For me it is compile errors.

**Comment by malin1993ml** [comment]
Yes. It is compile error.

**Comment by apavlo** [comment]
I will update Jenkins tonight to do this.

**Comment by apavlo** [comment]
Jenkins now compiles both `TRACE` and `RELEASE` targets. But it only builds the test cases with `RELEASE`.

@jarulraj Is there a way to build the test cases without having to actually run them?

**Comment by sid1607** [comment]
@jessesleeping Could you look into this, so that the system can be prepared for the first public release.

**Comment by jessesleeping** [comment]
Ok, I will look at this issue.
