### ISSUE TITLE
No projects found when importing git project within eclipse

### ISSUE THREAD

**Issue by kreichek** [cmu-db/peloton#239]
I am following this guide (https://github.com/cmu-db/peloton/wiki/Eclipse) to set-up my eclipse environment for development. When I get to step 7 of setup Peloton, I get no projects found in the dialog box instead of seeing peloton. Any ideas what could possibly going wrong or what I could try to troubleshoot this?

**Comment by saifalharthi** [comment]
What I did was
1- clone peloton
2- open eclipse -> import -> C\C++ -> import code as Makefile project.
3- Go to the path of the project.

I used "Cross GCC" and the project source code will be indexed. However , I did all my tests at the terminal , not the IDE.

**Comment by apavlo** [comment]
Also, make sure that you are using a newer version of Eclipse. 

I've attached my .project + .cproject files. If you put them in the root dir then Eclipse should be able to find then.

[peloton-eclipse-project.zip](https://github.com/cmu-db/peloton/files/468663/peloton-eclipse-project.zip)

**Comment by kreichek** [comment]
Should I download Neon instead of Luna? I was worried about any compatibility issues so I stuck with Luna since that was in the guide.

**Comment by apavlo** [comment]
I use Eclipse 4.5.2 (Mars).

The default version that in Ubnuntu is too old.

**Comment by malin1993ml** [comment]
I'm using Neon. So far I have no problem indexing the code. Though I compile and test the code using command line.

**Comment by kreichek** [comment]
I managed to get the project indexed on Neon. Thanks for all the help!
