### ISSUE TITLE
JDBC segfaults while doing an index_scan

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#241]
Appears while using test_jdbc.sh

stacktrace 

`#0  0x00007ffff786912c in peloton::common::Type::GetTypeId (this=0x7fff00000005) at /home/siddharth/git/peloton/src/common/type.cpp:203
#1  0x00007ffff76bfd08 in peloton::common::Value::GetTypeId (this=0x7ffff1c1aaa0) at /home/siddharth/git/peloton/src/include/common/value.h:67
#2  0x00007ffff7771ba1 in peloton::expression::ConstantValueExpression::ConstantValueExpression (this=0x7ffff1c2fb00, value=...) at /home/siddharth/git/peloton/src/include/expression/constant_value_expression.h:32
#3  0x00007ffff7771cb2 in peloton::expression::ConstantValueExpression::Copy (this=0x7ffff1c2f800) at /home/siddharth/git/peloton/src/include/expression/constant_value_expression.h:45
#4  0x00007ffff7792b0f in peloton::expression::ComparisonExpression::Copy (this=0x7ffff1c2f980) at /home/siddharth/git/peloton/src/include/expression/comparison_expression.h:65
#5  0x00007ffff7783eed in peloton::planner::DeletePlan::DeletePlan (this=0x7ffff1cbe100, delete_statemenet=0x7ffff1c1aaa0) at /home/siddharth/git/peloton/src/planner/delete_plan.cpp:45
#6  0x00007ffff78cc762 in peloton::optimizer::SimpleOptimizer::BuildPelotonPlanTree (parse_tree=std::unique_ptr<peloton::parser::SQLStatementList> containing 0x7ffff1c1c180) at /home/siddharth/git/peloton/src/optimizer/simple_optimizer.cpp:385
#7  0x00007ffff792a4ea in peloton::tcop::TrafficCop::PrepareStatement (this=0x7ffff7dd9b28 <peloton::tcop::TrafficCop::GetInstance()::traffic_cop>, statement_name="", query_string="DELETE FROM A WHERE id = 1", error_message="") at /home/siddharth/git/peloton/src/tcop/tcop.cpp:108
#8  0x00007ffff78a04e7 in peloton::wire::PacketManager::ExecParseMessage (this=0x7ffff4448640, pkt=0x7ffff2bfb470, responses=std::vector of length 0, capacity 4) at /home/siddharth/git/peloton/src/networking/protocol.cpp:306
#9  0x00007ffff78a305c in peloton::wire::PacketManager::ProcessPacket (this=0x7ffff4448640, pkt=0x7ffff2bfb470, responses=std::vector of length 0, capacity 4) at /home/siddharth/git/peloton/src/networking/protocol.cpp:603
#10 0x00007ffff78a3741 in peloton::wire::PacketManager::ManagePacket (this=0x7ffff4448640) at /home/siddharth/git/peloton/src/networking/protocol.cpp:697
#11 0x00007ffff7906fe7 in peloton::wire::ManageRead (socket_manager=0x7ffff4480038) at /home/siddharth/git/peloton/src/wire/libevent_server.cpp:63
#12 0x00007ffff790a5fc in std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x7ffff2bfb7c0, __args=<unknown type in /home/siddharth/git/peloton/build/lib/libpeloton-d.so.0.0.3, CU 0x1203b94, DIE 0x1236bfc>) at /usr/include/c++/4.8/functional:1296
#13 0x00007ffff790a546 in std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>::operator()<, void>() (this=0x7ffff2bfb7c0) at /usr/include/c++/4.8/functional:1355
#14 0x00007ffff790a4aa in boost::asio::asio_handler_invoke<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >(std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#15 0x00007ffff790a3fa in boost_asio_handler_invoke_helpers::invoke<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>, std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >(std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>&, std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>&) (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#16 0x00007ffff790a2d9 in boost::asio::detail::completion_handler<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x7ffff4410240, base=0x7ffff44427c0) at /usr/include/boost/asio/detail/completion_handler.hpp:68
#17 0x00007ffff788a76a in boost::asio::detail::task_io_service_operation::complete (this=0x7ffff44427c0, owner=..., ec=..., bytes_transferred=0) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#18 0x00007ffff788b5ff in boost::asio::detail::task_io_service::do_run_one (this=0x7ffff4410240, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:384
#19 0x00007ffff788b33b in boost::asio::detail::task_io_service::run (this=0x7ffff4410240, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#20 0x00007ffff788b999 in boost::asio::io_service::run (this=0x7ffff7dd9540 <peloton::thread_pool+352>) at /usr/include/boost/asio/impl/io_service.ipp:59
#21 0x00007ffff7895c3b in boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator() (this=0x7ffff4415bb8, p=0x7ffff7dd9540 <peloton::thread_pool+352>) at /usr/include/boost/bind/mem_fn_template.hpp:49
#22 0x00007ffff7895b9f in boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0> (this=0x7ffff4415bc8, f=..., a=...) at /usr/include/boost/bind/bind.hpp:243
`

**Comment by MattPerron** [comment]
I believe this is now working so I'm closing the issue. Please reopen if there are further problems.
