### ISSUE TITLE
Aggregations crash with std::logic_error with JDBC

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#242]
Run Scan_Test() (including  aggregation queries) from test_jdbc.sh

Peloton crashes on running this test with std::logic_error.

stacktrace

`#0  0x00007ffff519ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff519e028 in __GI_abort () at abort.c:89
#2  0x00007ffff5aa5535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5aa36d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5aa3703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5aa3922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff5af51c7 in std::__throw_logic_error(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7945db1 in std::string::_S_construct<char const*> (__beg=0x0, __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, __a=...) at /usr/include/c++/4.8/bits/basic_string.tcc:133
#8  0x00007ffff5b00d88 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007ffff792ae14 in peloton::tcop::TrafficCop::GenerateTupleDescriptor (this=0x7ffff7dd9b28 <peloton::tcop::TrafficCop::GetInstance()::traffic_cop>, query="SELECT COUNT(*) FROM A") at /home/siddharth/git/peloton/src/tcop/tcop.cpp:204
#10 0x00007ffff792a547 in peloton::tcop::TrafficCop::PrepareStatement (this=0x7ffff7dd9b28 <peloton::tcop::TrafficCop::GetInstance()::traffic_cop>, statement_name="", query_string="SELECT COUNT(*) FROM A", error_message="") at /home/siddharth/git/peloton/src/tcop/tcop.cpp:112
#11 0x00007ffff78a0463 in peloton::wire::PacketManager::ExecParseMessage (this=0x7ffff4448640, pkt=0x7ffff2bfb470, responses=std::vector of length 0, capacity 4) at /home/siddharth/git/peloton/src/networking/protocol.cpp:306
#12 0x00007ffff78a2fd8 in peloton::wire::PacketManager::ProcessPacket (this=0x7ffff4448640, pkt=0x7ffff2bfb470, responses=std::vector of length 0, capacity 4) at /home/siddharth/git/peloton/src/networking/protocol.cpp:603
#13 0x00007ffff78a36bd in peloton::wire::PacketManager::ManagePacket (this=0x7ffff4448640) at /home/siddharth/git/peloton/src/networking/protocol.cpp:697
#14 0x00007ffff7906f63 in peloton::wire::ManageRead (socket_manager=0x7ffff4480038) at /home/siddharth/git/peloton/src/wire/libevent_server.cpp:63
#15 0x00007ffff790a578 in std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x7ffff2bfb7c0, __args=<unknown type in /home/siddharth/git/peloton/build/lib/libpeloton-d.so.0.0.3, CU 0x1203b24, DIE 0x1236b8c>) at /usr/include/c++/4.8/functional:1296
#16 0x00007ffff790a4c2 in std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>::operator()<, void>() (this=0x7ffff2bfb7c0) at /usr/include/c++/4.8/functional:1355
#17 0x00007ffff790a426 in boost::asio::asio_handler_invoke<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >(std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#18 0x00007ffff790a376 in boost_asio_handler_invoke_helpers::invoke<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>, std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >(std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>&, std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)>&) (function=..., context=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#19 0x00007ffff790a255 in boost::asio::detail::completion_handler<std::_Bind<void (*(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**))(peloton::wire::SocketManager<std::vector<unsigned char, std::allocator<unsigned char> > >**)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x7ffff4410240, base=0x7ffff44427c0) at /usr/include/boost/asio/detail/completion_handler.hpp:68
#20 0x00007ffff788a6e6 in boost::asio::detail::task_io_service_operation::complete (this=0x7ffff44427c0, owner=..., ec=..., bytes_transferred=0) at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#21 0x00007ffff788b57b in boost::asio::detail::task_io_service::do_run_one (this=0x7ffff4410240, lock=..., this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:384
#22 0x00007ffff788b2b7 in boost::asio::detail::task_io_service::run (this=0x7ffff4410240, ec=...) at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#23 0x00007ffff788b915 in boost::asio::io_service::run (this=0x7ffff7dd9540 <peloton::thread_pool+352>) at /usr/include/boost/asio/impl/io_service.ipp:59
#24 0x00007ffff7895bb7 in boost::_mfi::mf0<unsigned long, boost::asio::io_service>::operator() (this=0x7ffff4415bb8, p=0x7ffff7dd9540 <peloton::thread_pool+352>) at /usr/include/boost/bind/mem_fn_template.hpp:49
#25 0x00007ffff7895b1b in boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> >::operator()<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list0> (this=0x7ffff4415bc8, f=..., a=...) at /usr/include/boost/bind/bind.hpp:243
#26 0x00007ffff78957a1 in boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > >::operator() (this=0x7ffff4415bb8) at /usr/include/boost/bind/bind_template.hpp:20
#27 0x00007ffff78953ee in boost::detail::thread_data<boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_service>, boost::_bi::list1<boost::_bi::value<boost::asio::io_service*> > > >::run (this=0x7ffff4415a00) at /usr/include/boost/thread/detail/thread.hpp:117
#28 0x00007ffff66d8a4a in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#29 0x00007ffff64b7184 in start_thread (arg=0x7ffff2bfc700) at pthread_create.c:312
#30 0x00007ffff525e37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
`

Check frame no. 9. A std::string(0) allocation is being attempted, which throws the logic_error. This implies that func_expr->expr->GetName() in tcop.cpp:204 returns a null pointer.

Look for why this happens.

**Comment by MattPerron** [comment]
fixed with PR #248
