### ISSUE TITLE
Extend SimpleOptimizer to Support Equi-Join Queries

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#243]
Our current query planner is hardcoded by @jarulraj  to generate plans for the only join query in TPC-C:

https://github.com/cmu-db/peloton/blob/master/src/optimizer/simple_optimizer.cpp#L627

You can see what this particular query looks like here:

https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/procedures/StockLevel.java#L38

We want to extend code this to be able to work with any two table equi-join query. We are going to ignore computing an optimal join order for now and just get the predicates correct. The basic idea is that you are going to look for equality predicates where one of the operands is from one table and the other operand is from another table:

```
SELECT * FROM A JOIN B ON A.id = B.id
SELECT * FROM A, B WHERE A.id = B.id
```

You can just default to use the hash-join operator.

**Comment by haojin2** [comment]
Got the issue, not working on it

**Comment by apavlo** [comment]
> Got the issue, now working on it

I'm assuming that you meant that you are "now" working on it. You two guys should work together on this. Feel free to talk with @malin1993ml on your ideas on how to fix this.

**Comment by haojin2** [comment]
Yeah sorry that was a typo... I've been trying to get a general idea of the system and that optimizer part for the past day. I'll reach out to Lin as soon as I feel prepared with knowledge about that part. Probably later tomorrow. Thanks!

**Comment by apavlo** [comment]
You should work with @iwantcombo on this first task. The two of you should look at it together.

**Comment by haojin2** [comment]
Got it, I'll reach out to him. Thanks!

**Comment by iwantcombo** [comment]
Let's meet up sometime.

**Comment by pbhowmic** [comment]
Not sure where folks are with addressing this issue but it might be a good idea to clean up the SELECT case statement while tackling this issue, it is a bit long (300+ lines of code) with multiple if-then-else statements spanning the case. It hurts the readability of the code.

**Comment by luochenUmich** [comment]
I think this issue can be closed now. Both optimizer and LLVM supports this type of join

**Comment by apavlo** [comment]
@luochenUmich Thanks!
