### ISSUE TITLE
some expired wiki pages can be removed

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#250]
e.g., 
https://github.com/cmu-db/peloton/wiki/Postgres
https://github.com/cmu-db/peloton/wiki/Postgres-Modifications

**Comment by jarulraj** [comment]
I removed the https://github.com/cmu-db/peloton/wiki/Postgres-Modifications.

I think we can still keep the https://github.com/cmu-db/peloton/wiki/Postgres page around.

Any other pages that can be removed ?

**Comment by MattPerron** [comment]
These pages seem to be dead:
https://github.com/cmu-db/peloton/wiki/Notes-DDL
https://github.com/cmu-db/peloton/wiki/Postgres-Expression-System
https://github.com/cmu-db/peloton/wiki/Notes-Fork

These pages refer to the old postgres code and could be mostly removed or edited:
https://github.com/cmu-db/peloton/wiki/Architecture (should be edited to reflect current design)
https://github.com/cmu-db/peloton/wiki/Plan-Caching
https://github.com/cmu-db/peloton/wiki/Notes-Join
https://github.com/cmu-db/peloton/wiki/Query-Plan
https://github.com/cmu-db/peloton/wiki/Commands (should reflect the current way to start and stop peloton)
https://github.com/cmu-db/peloton/wiki/Valgrind (should reflect the current way to start and stop peloton)
https://github.com/cmu-db/peloton/wiki/GDB (should reflect the current way to start and stop peloton)

**Comment by jarulraj** [comment]
Cleaned up and removed some of the wiki pages suggested by @MattPerron.
