### ISSUE TITLE
Add SQL Function Catalog

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#261]
As @MattPerron mentioned in #248, right now our support for SQL functions is broken and ad-hoc. We support some of the string functions directly in the expressions API (e.g., [string fuctions](/cmu-db/peloton/blob/master/src/include/expression/string_expression.h)), but there is no easy way to extend the parse to support new ones. Postgres handles this by storing everything in the catalog. I like this model and we should try to follow it.

We are going to need this soon in order to add support date functions and other things for TPC-H, as well as UDFs (for the ISTC-VC). After we finish the first release, let's design what the new function API looks like.

**Comment by poojanilangekar** [comment]
Fixed.
