### ISSUE TITLE
update & delete not using index scan plan

### ISSUE THREAD

**Issue by eric-haibin-lin** [cmu-db/peloton#263]
Updating and deleting index searchable rows are using sequential scan instead of index scan, which is slow. 

https://github.com/cmu-db/peloton/blob/master/src/optimizer/simple_optimizer.cpp#L389
https://github.com/cmu-db/peloton/blob/master/src/planner/update_plan.cpp#L73

**Comment by MattPerron** [comment]
Fixed in #289
