### ISSUE TITLE
Hanging when handling partial writes in socket_base.cpp

### ISSUE THREAD

**Issue by MattPerron** [cmu-db/peloton#265]
The code to handle the case when `write` does not write a whole buffer causes a hang at https://github.com/cmu-db/peloton/blob/master/src/wire/socket_base.cpp#L185

**Comment by MattPerron** [comment]
Also, even though the sockets are non-blocking, the read and write functions in this file block until a buffer is written.

**Comment by sid1607** [comment]
Yes, it doesn't seem like this code uses all the non-blocking facilities that libevent has to offer. Any steps on how to reproduce this hang condition?

**Comment by MattPerron** [comment]
When peloton returns large amounts of data (around 8MB) this happens almost every time.
Also, I already have a solution (to it hanging), I created this issue for bookkeeping purposes.

**Comment by MattPerron** [comment]
Fixed with #266
