### ISSUE TITLE
Jenkins test broken

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#271]
Jenkins test was broken after the merge #260:
http://jenkins.db.cs.cmu.edu:8080/job/Peloton/101/

It failed when trying to build tests on release mode.

**Comment by MattPerron** [comment]
I believe @eric-haibin-lin is looking into this.

**Comment by malin1993ml** [comment]
Cool.

**Comment by apavlo** [comment]
The tests are running on jenkins but it is not generating the xml files for the results of the unit tests. So we are not able to see the test result history.
```
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing GoogleTest-1.6
[xUnit] [INFO] - [GoogleTest-1.6] - No test report file(s) were found with the pattern '**/tests/unit_*.xml' relative to '/var/lib/jenkins/jobs/Peloton/workspace' for the testing framework 'GoogleTest-1.6'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'GoogleTest-1.6'?
[xUnit] [WARNING] - No test reports found for the metric 'GoogleTest' with the resolved pattern '**/tests/unit_*.xml'.
[xUnit] [INFO] - Skipping the metric tool processing.
```

http://jenkins.db.cs.cmu.edu:8080/job/Peloton/100/console

How do I enable gtest to output xml files?
