### ISSUE TITLE
Revive the log manager

### ISSUE THREAD

**Issue by jessesleeping** [cmu-db/peloton#277]
Currently the log manager is disabled in the transaction manager. Also, since we are using our own catalog table now, the recovery logic should also handle the catalog table.

**Comment by jarulraj** [comment]
What's the current status of the log manager @jessesleeping  @yingjunwu @MattPerron ? Do we have test cases for the log manager ?

**Comment by apavlo** [comment]
@jessesleeping is going to port their latest logging + epoch + GC code from their paper branch to the master next week. Then @YingjunWu will work on the next paper in January. 

We want their optimized logging code in order to do real TPC-C benchmarking.
