### ISSUE TITLE
Reduce travis build time

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#278]
Travis team has agreed to extend our maximum build time to 90 minutes. But we also want to look into some methods to reduce the build time according to what they suggested in the email:

> We have increased the maximum build time for repository cmu-db/peloton to 90 minutes. That being said, I think we should look into how to decrease the build time in general.
> 
> We have the possibility to store build artifacts in a cache. This is intended for files that take long to build or install, but are relatively fast to download. The caching mechanism is rather basic: You tell which directory to cache, and an automated download at the start of the build, as well as an automated upload at the end, is being taken care of.
> 
> As it seems that the build artifacts you create are ending up in the source directory itself, some trickery is necessary to make this work for you.
> 
> If you would be able to make a magic `find` command that copies all artifacts to a specified directory, 
> 
> In pseudo code:
> 
> cache:
>   dir:
>     - artifacts
> before_install:
> - "[ -d artifacts ] && ( cp -a artifacts/\* . )"
> 
> after_script:
> - "cp --preserve=all $(find . $magic) ./artifacts/"
> 
> The time stamps of the code files in your repository, as well as the time stamps of the build artifacts, should guide `make` in what to build.
> 
> The problem here would be to arrive at the proper find command. The following possibly could get you started:
> 
> find . ( -name '_.o' -name '_.so' -o -name ./directory/linked_binary ) -o -not ( -path ./artifacts -prune )
> 
> If you would want to go this route, I guess you would want to get access to a debug build to fine tune the find command. 
> 
> Please do let us know if any questions would remain, or if you are having any doubt. We are happy to try and work them out.

**Comment by eric-haibin-lin** [comment]
I'm curious why we're not using `ctest -j4` to run 4 unit tests in parallel to reduce the time for unit tests? Does it not work for travis?

**Comment by malin1993ml** [comment]
I've tried -j2 but it didn't make any difference than -j1. I think travis doesn't support multi-thread building.

**Comment by apavlo** [comment]
We will eventually move over the Jenkins to speed things up.
