### ISSUE TITLE
StockLevel of TPC-C keeps retrying

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#279]
21:05:31,036 (DBWorkload.java:714) INFO  - Launching the tpcc Benchmark with 1 Phases...
21:05:31,038 (ThreadBench.java:319) INFO  - [Starting Phase] [Workload= tpcc] [Serial= false] [Time= 10] [Rate= 10] [Arrival= REGULAR] [Ratios= [0.0, 0.0, 0.0, 0.0, 100.0]] [Active Workers=1]
21:05:31,056 (Worker.java:402) DEBUG - StockLevel/05 Bad value for type int : integer_null 0 - 22003
21:05:31,058 (Worker.java:472) DEBUG - Retrying transaction...
21:05:31,068 (Worker.java:402) DEBUG - StockLevel/05 Bad value for type int : integer_null 0 - 22003
21:05:31,068 (Worker.java:472) DEBUG - Retrying transaction...
21:05:31,074 (Worker.java:402) DEBUG - StockLevel/05 Bad value for type int : integer_null 0 - 22003
21:05:31,074 (Worker.java:472) DEBUG - Retrying transaction...

**Comment by MattPerron** [comment]
should be fixed with #280
