### ISSUE TITLE
DROP Table segfaults

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#282]
When I was running basic1.sql on psql, peloton crashes with

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1ffc700 (LWP 24034)]
0x00007ffff76f6de9 in peloton::parser::DropStatement::GetTableName (this=0x7fffef016df0) at /home/siddharth/git/peloton/src/include/parser/statement_drop.h:45
45	  inline std::string GetTableName() { return std::string(table_name->name); }

I wonder how this didn't get caught by Travis' psql test.

EDIT: Even JDBC based operations fail on this.

**Comment by eric-haibin-lin** [comment]
let me take a look

**Comment by eric-haibin-lin** [comment]
Which version are you using?

I cannot reproduce it with the most recent version of master 9ddc7cb4a887a478045a9eb2aaa28d8402ef8753. 


> ➜  dml git:(pr) ✗ sudo -u postgres psql "sslmode=disable" postgres -h localhost -p 54321 < basic1.sql
> drop table if exists foo 0
> create table foo(id integer PRIMARY KEY, year integer) 0
> insert into foo values(1, 100) 1
> insert into foo values(1, 200) 0
> insert into foo values(2, 200) 1
> insert into foo values(3, 300) 1
> insert into foo values(4, 400) 1
> insert into foo values(5, 400) 1
> insert into foo values(5, 500) 0
>  id | year 
> ----+------
>   1 |  100
>   2 |  200
>   3 |  300
>   4 |  400
>   5 |  400
> (5 rows)
> 
>  id | year 
> ----+------
>   1 |  100
>   2 |  200
> (2 rows)
> 
>  id | year 
> ----+------
>   3 |  300
>   4 |  400
>   5 |  400
> (3 rows)
> 
> delete from foo where year = 200 1
>  id | year 
> ----+------
>   1 |  100
>   3 |  300
>   4 |  400
>   5 |  400
> (4 rows)
> 
> update foo set year = 3000 where id = 3 1
>  id | year 
> ----+------
>   1 |  100
>   4 |  400
>   5 |  400
>   3 | 3000
> (4 rows)
> 
> update foo set year = 1000 where year = 100 1
>  id | year 
> ----+------
>   4 |  400
>   5 |  400
>   3 | 3000
>   1 | 1000
> (4 rows)
> 
> update foo set id = 3 where year = 1000 1
>  id | year 
> ----+------
>   4 |  400
>   5 |  400
>   3 | 3000
>   3 | 1000
> (4 rows)
> 
> update foo set id= 10 where year = 1000 1
>  id | year 
> ----+------
>   4 |  400
>   5 |  400
>   3 | 3000
>  10 | 1000
> (4 rows)
> 
> insert into foo values (2, 2000) 1
>  id | year 
> ----+------
>   4 |  400
>   5 |  400
>   3 | 3000
>  10 | 1000
>   2 | 2000
> (5 rows)
> 
> insert into foo values (4, 4000) 0
>  id | year 
> ----+------
>   4 |  400
>   5 |  400
>   3 | 3000
>  10 | 1000
>   2 | 2000
> (5 rows)
> 
> insert into foo values (1, 1000) 0
>  id | year 
> ----+------
>   4 |  400
>   5 |  400
>   3 | 3000
>  10 | 1000
>   2 | 2000
> (5 rows)



- 

> ➜  build git:(master) bin/peloton -port 54321 -stats_mode 0
> [INFO ] [/home/yifan/upstream/src/wire/libevent_server.cpp:83:AcceptCallback()] 2016-09-23 23:09:34 - New connection on fd 7
> [INFO ] [/home/yifan/upstream/src/wire/libevent_server.cpp:52:ManageRead()] 2016-09-23 23:09:34 - New thread 140183366256384 started execution for socket manager 1
> [INFO ] [/home/yifan/upstream/src/planner/update_plan.cpp:40:UpdatePlan()] 2016-09-23 23:09:34 - Update database default_database table foo
> [INFO ] [/home/yifan/upstream/src/planner/update_plan.cpp:40:UpdatePlan()] 2016-09-23 23:09:34 - Update database default_database table foo
> [INFO ] [/home/yifan/upstream/src/planner/update_plan.cpp:40:UpdatePlan()] 2016-09-23 23:09:34 - Update database default_database table foo
> [INFO ] [/home/yifan/upstream/src/planner/update_plan.cpp:40:UpdatePlan()] 2016-09-23 23:09:34 - Update database default_database table foo
> [INFO ] [/home/yifan/upstream/src/wire/libevent_server.cpp:67:ManageRead()] 2016-09-23 23:09:34 - Thread 140183366256384 Executing for socket manager 1 failed to manage packet
> 
>

**Comment by eric-haibin-lin** [comment]
@sid1607 any more information about the failure?

**Comment by sid1607** [comment]
I guess there were some inconsistencies in my local build. This is not an issue anymore.
