### ISSUE TITLE
segfaults when querying a non-existent table

### ISSUE THREAD

**Issue by pbhowmic** [cmu-db/peloton#288]
> vagrant@vagrant:~$ psql "sslmode=disable" -U postgres -p 57721 -h 127.0.0.1
> psql (9.5.4, server 9.5devel)
> Type "help" for help.
> 
> postgres=# create table A(id INT PRIMARY KEY, data TEXT);
> create table A(id INT PRIMARY KEY, data TEXT) 0
> postgres=# select * from A;
>  id | data 
> ----+------
> (0 rows)
> 
> postgres=# DROP TABLE IF EXISTS A;
> DROP TABLE IF EXISTS A 0
> postgres=# select * from A;
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> The connection to the server was lost. Attempting reset: Failed.
> !> 
>

**Comment by eric-haibin-lin** [comment]
Fixed by PR #301
