### ISSUE TITLE
sdbench compilation failed

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#292]
the sdbench (https://github.com/cmu-db/peloton/tree/master/src/main/sdbench) in the master branch cannot pass compilation. I think it is because this benchmark is never updated after the introduce of the new type system.

**Comment by ranxian** [comment]
@yingjunwu You are correct, the code for sdbench in the master does not incorporate the new type system. 

@jarulraj I actually think it is a good idea to `embrace' the master branch, we can then get new GC and N2O for free.

**Comment by jarulraj** [comment]
@yingjunwu are the other benchmarks compiling and running?

**Comment by yingjunwu** [comment]
@jarulraj yes all the other benchmarks can compile.

**Comment by jarulraj** [comment]
This has been fixed. All benchmarks are now built on travis.
