### ISSUE TITLE
Handle binding correctly in join and other plans

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#299]
The default logic for binding the parameters of a stored procedure to plans is here:
https://github.com/cmu-db/peloton/blob/master/src/planner/abstract_plan.cpp#L65
Basically it just calls the binding function of all its children.

If there're certain fields in the plan that need to be bound, such as predicate expressions, we have to customize the binding function. We already have some overrode functions for InsertScanPlan, UpdatePlan, etc. However there're still some plans that need to be fixed. For example if there're some parameters in the join condition, then we cannot handle it (assuming we can generate a join plan).

**Comment by poojanilangekar** [comment]
Fixed by @hzxa21 and @chenboy
