### ISSUE TITLE
User defined functions

### ISSUE THREAD

**Issue by jarulraj** [cmu-db/peloton#30]
1. Add support for UDFs.

**Comment by tomasic** [comment]
definitely separate tickets ...

On Tue, Feb 9, 2016 at 12:27 PM, Joy Arulraj <notifications@github.com>
wrote:

>
>    1. Add support for UDFs and UDTs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-db/peloton/issues/30>.
>



-- 
Anthony Tomasic
Senior Systems Scientist
Language Technologies Institute
Carnegie Mellon University
http://ideate.cmu.edu/graduate-programs-research/emerging-media/
<http://ideate.cmu.edu/graduate-programs-research/emerging-media/>
http://www.tiramisutransit.com
*http://mcds.cs.cmu.edu <http://mcds.cs.cmu.edu>*
http://www.cs.cmu.edu/~tomasic
