### ISSUE TITLE
Server Scaling

### ISSUE THREAD

**Issue by aelroby** [cmu-db/peloton#300]
When any thread is executing, and for example needs to refill the read buffer, if the file descriptor is not ready for read, select() is called and the thread is blocked until it is notified that it can read from the file descriptor now. select() is implemented so that it iterates over the bits representing the file descriptors in the file descriptors set and notify the blocking thread whenever there is a change.
Read: https://github.com/cmu-db/peloton/blob/master/src/wire/socket_base.cpp#L90
Write: https://github.com/cmu-db/peloton/blob/master/src/wire/socket_base.cpp#L185

This should be working fine for peloton. But when we really want to scale up like high performance web servers, this needs to be changed and perhaps the logic of buffers needs to move up the stack.

**Comment by sid1607** [comment]
Implemented by #342
