### ISSUE TITLE
Abort rate is 99% for PCC under hyper-threading

### ISSUE THREAD

**Issue by Michael-Tieying-Zhang** [cmu-db/peloton#304]
A txn has two queries: SELECT and UPDATE, and they both operate the same table. The abort rate will be 99% when the total threads reach hyper-threading (for PCC). Before that, the abort rate is only around 20%. That is to say, the abort rate suddenly increases to 99% when # of threads exceeds # of physical cores.

**Comment by apavlo** [comment]
Do you have code that somebody can use to reproduce this? What is the access pattern distribution? How big is the table? How many tuples do they access? Does this happen on master?

Nobody else is going to know what you mean by "PCC" either.

**Comment by Michael-Tieying-Zhang** [comment]
Yes. I have code to reproduce this issue. The table has 10,000 tuples with 90% HotSpot accesses within [1, 50]

I didn't try that on master branch (I think it is "TO" as the default concurrency control protocol).

**Comment by apavlo** [comment]
By "PCC" do you mean 2PL?

**Comment by Michael-Tieying-Zhang** [comment]
Yes. "Pcc" is the command line parameter. It is actually 2PL.

**Comment by apavlo** [comment]
If it's 2PL (what variant?), then are you just experiencing lock thrashing? Why do you think it is something wrong with the system?

**Comment by Michael-Tieying-Zhang** [comment]
The abort rate increases sharply (it is 20% when # threads is 6 and 99% when # threads is 7). Can lock thrashing explain that? If so, pls close this issue.

**Comment by apavlo** [comment]
> Can lock thrashing explain that?

You have to measure this.

**Comment by apavlo** [comment]
Please also only post issues that are reproducible in the master branch.
