### ISSUE TITLE
Excessive buffer flush in wire protocol

### ISSUE THREAD

**Issue by eric-haibin-lin** [cmu-db/peloton#311]
For each message peloton receives, peloton processes it and flush the response buffer. To execute a query, JDBC sends over parse, bind, describe, execute and sync (5 messages) all together in one packet, and waits for response. Currently peloton flushes the buffer after processing each of these messages. Instead flushing 5 times, we should batch the 5 responses and just flush once. 

@sid1607 @malin1993ml

**Comment by malin1993ml** [comment]
That's a cool finding. Does that improve our networking performance?

**Comment by eric-haibin-lin** [comment]
Used no-op benchmark script to stress the networking in peloton, and got the following result (unit: queries / second). Batch flush is the improve version of peloton. 

We have significant improvement on local tests, but for remote(cross-machine) test the improvement is not as significant. 

| No-op query | Timesten | Peloton | Postgres | Peloton (Batch Flush) 
| --- | --- | --- | --- | --- | 
| Remote | 8554 | 8024 | 8906 | 10183 | 
| Local | 26455 | 26533 | 33858 | 51578 |

| Prep Stmt | Timesten | Peloton | Postgres | Peloton (Batch Flush) 
| --- | --- | --- | --- | --- | 
| Remote | 4827 | 4476 | 4245 | 4632 | 
| Local | 18158 | 12073 | 13896 | 17774 |

** No op query = “;”
** Prep stmt = “select * from A where id = ?”. Table A is empty. 
** Remote = JDBC on dev2, database on dev1
** Local = Both JDBC & database on dev1

**Comment by ranxian** [comment]
This is cool, I can run timesten ycsb+tpcc right after this is merged
