### ISSUE TITLE
OrderStatus fails with SQL parsing error

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#313]
I observed this while running the master branch with tpcc (configured as OrderStatus - 100 and all others 0) and I observe this from OltpBench

18:06:51,906 (Worker.java:402) DEBUG - OrderStatus/03 Error parsing SQL statement 0 - null
18:06:51,907 (Worker.java:472) DEBUG - Retrying transaction...
18:06:51,907 (Worker.java:402) DEBUG - OrderStatus/03 Error parsing SQL statement 0 - null
18:06:51,907 (Worker.java:472) DEBUG - Retrying transaction...
18:06:51,908 (Worker.java:402) DEBUG - OrderStatus/03 Error parsing SQL statement 0 - null
18:06:51,908 (Worker.java:472) DEBUG - Retrying transaction...

and this from Peloton 
[ERROR] [/home/siddharth/git/peloton/src/networking/protocol.cpp:676:ProcessPacket()] 2016-10-18 18:06:51 - Packet type not supported yet: 67 (C)
Exception Type :: Parser
Message :: Error parsing SQL statement
[ERROR] [/home/siddharth/git/peloton/src/networking/protocol.cpp:676:ProcessPacket()] 2016-10-18 18:06:51 - Packet type not supported yet: 67 (C)
Exception Type :: Parser
Message :: Error parsing SQL statement
[ERROR] [/home/siddharth/git/peloton/src/networking/protocol.cpp:676:ProcessPacket()] 2016-10-18 18:06:51 - Packet type not supported yet: 67 (C)
Exception Type :: Parser
Message :: Error parsing SQL statement
[ERROR] [/home/siddharth/git/peloton/src/networking/protocol.cpp:676:ProcessPacket()] 2016-10-18 18:06:51 - Packet type not supported yet: 67 (C)
Exception Type :: Parser

**Comment by malin1993ml** [comment]
I can run it on my machine. Can you try to make a clean build for both Peloton and OLTPBench?

**Comment by sid1607** [comment]
Yup, I had an outdated version of OLTPBench. Resolved.
