### ISSUE TITLE
Update Wiki please

### ISSUE THREAD

**Issue by pbhowmic** [cmu-db/peloton#324]
[https://github.com/cmu-db/peloton/wiki/Query-Plan](url) needs to be updated. For one, is there an `ExecInitNode()` or `ExecProcNode() `methods anymore? I tried grepping thru the code in `src/`
 and came up with no hits.

**Comment by apavlo** [comment]
We are working on a new query optimizer right now, so the wiki pages are out-of-date.

Is there something specific that you are trying to accomplish?

**Comment by pbhowmic** [comment]
Hi Professor Pavlo. First I would like to say thank you for making the 15-721 lectures available on YouTube, I have really enjoyed them and I they have helped plug a hole in my knowledge base. I am not a DB guy myself, in fact, I an MSCF grad from Tepper so in a past life, a lot of my work involved Monte-carlo scenario generation. In my limited off time, I have been trying to "bake" analytics  into open-source databases, the idea being certain classes of applications care more about the analysis and not so much about the data itself, so it's best to do the analysis _in situ_ in the database, thus utilizing any free cores the DBMS hardware might have. So, in the case of Peloton seems like a good candidate because of its tiled architecture, I can grab the data (which is frequently on hot data and not cold data), do the analysis, and send back only the post-analysis results. So at this point, having joins working is a bare-minimum requirement because in this case, I am looking at a portfolio of financial securities to determine the portfolio risk.

**Comment by apavlo** [comment]
@pbhowmic Email me. We should try to talk this week pavlo@cs.cmu.edu

**Comment by pbhowmic** [comment]
Hi Professor Pavlo,
Sure we can talk. Let me know a few dates/times and I will see which ones are workable.
Email me at p.s.bhowmick at gmail
