### ISSUE TITLE
GetMaxValue() and GetMinValue() on VARCHAR Does Not Create Correct Value

### ISSUE THREAD

**Issue by wangziqi2013** [cmu-db/peloton#331]
https://github.com/cmu-db/peloton/blob/master/src/common/type.cpp#L201
https://github.com/cmu-db/peloton/blob/master/src/common/type.cpp#L175

In the above two switch branches, they both pass length = 0 to class Value constructor,  which corresponds to:

https://github.com/cmu-db/peloton/blob/master/src/common/value.cpp#L198

In class Value constructor, argument "len" (which is both 0 for VARCHAR max and min value) is used to allocate a new array of length 0 (which causes undefined behavior, btw), and then used to memcpy() 0 bytes (which has no effect). Therefore, after the constructor both VARCHAR max and min are class Value objects with 0 length and undefined data array. This causes scan optimizer which relies on well-defined VARCHAR max and min to fail, which in turn fails index scan with partial string key.

**Comment by wangziqi2013** [comment]
@malin1993ml Not sure whether this has been fixed or not. Do we have test case for the type system? I could not find the source file for the type system unit test under /test directory

**Comment by malin1993ml** [comment]
@wangziqi2013 I'm not sure whether this is fixed, either. By type system, you mean the Value type system, right? The tests for them are here:
https://github.com/cmu-db/peloton/tree/master/test/common
They're not in the correct folder.

**Comment by poojanilangekar** [comment]
This is now being addressed in #850
