### ISSUE TITLE
NestedLoopIndexJoin Executor

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#343]
We need the `NestedLoopIndexJoin` executor for TPC-C StockLevel. The current implementation is a regular dirty nested-loop without the join probe. You are also going to need to fix up `SimpleOptimizer::CreateHackingJoinPlan` to use the new executor instead of the hash join:

https://github.com/cmu-db/peloton/blob/master/src/optimizer/simple_optimizer.cpp#L764

**Comment by domino-succ** [comment]
Yes. We need to replace HashJoin in current simple_optimizer.cpp with the fixed nested-loop join.
