### ISSUE TITLE
inlined varchar

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#349]
Neither the new nor the old type system supports inlined varchar. It only supports storing varchar in varlenpool.

**Comment by jessesleeping** [comment]
Please refer to #396 after we can support inlined varchar.

**Comment by poojanilangekar** [comment]
@pmenon Do we have plans of supporting inline varchar in the codegen engine?

**Comment by poojanilangekar** [comment]
Need to create a new project idea for 15721 spring 2018.
