### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by jarulraj** [cmu-db/peloton#35]
1. Add support for views, both static and dynamic views.

**Comment by tomasic** [comment]
I've worked on view updates - in short, there is no good solution and no
one uses them. Triggers seems to be the best work around.

On Wed, Feb 17, 2016 at 12:32 PM, Joy Arulraj <notifications@github.com>
wrote:

>
>    1.
>
>    Add support for views, both static and dynamic views.
>    2.
>
>    Figure out how to handle view updates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-db/peloton/issues/35>.
>



-- 
Anthony Tomasic
Senior Systems Scientist
Language Technologies Institute
Carnegie Mellon University
http://ideate.cmu.edu/graduate-programs-research/emerging-media/
<http://ideate.cmu.edu/graduate-programs-research/emerging-media/>
http://www.tiramisutransit.com
*http://mcds.cs.cmu.edu <http://mcds.cs.cmu.edu>*
http://www.cs.cmu.edu/~tomasic

**Comment by jarulraj** [comment]
Yes, not all views are updatable. https://msdn.microsoft.com/en-us/library/ms187956.aspx#Anchor_2
I have removed it from the list for now.
