### ISSUE TITLE
Pre-declared read only transaction support

### ISSUE THREAD

**Issue by jessesleeping** [cmu-db/peloton#358]
We need the following functionality to support pre-declared read only transaction

- The **epoch manager** should assign a proper timestamp to the read-only transaction to ensure that this transaction reads a consistent read-only snapshot of the database.
- The **transaction manager** should ignore all the read performed by a read-only transaction. Since the transaction is read-only and it's running on a consistent read-only snapshot, there is no rw conflicts or ww conflicts.
- The **garbage collection manager** should coordinate with the epoch manager to ensure that there is always an available read only snapshot for incoming read only transactions.

**Comment by apavlo** [comment]
Merged with #359
