### ISSUE TITLE
EXTRACT Placeholder Function

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#361]
Can you add back the `EXTRACT`function? Except that I don't want you to actually implement it. I just need you to add in the function and hook it up into the system so that it gets invoked when it is used in a SQL query. But then it will just return `INT32_NULL` for now.

I am going use this for the first programming project in the spring semester. I will create a hardcoded version that returns the correct answer for some subset of test inputs. This will act as the oracle function that the students can compare their implementation against.

**Comment by MattPerron** [comment]
Sure. By when do you want this completed?

**Comment by apavlo** [comment]
Dec 15th

**Comment by apavlo** [comment]
If this requires you to modify the parser to add support for `EXTRACT`, can you add a page on the wiki that gives walkthrough on files you need to edit. This will make it easier for others to add new things later.

**Comment by MattPerron** [comment]
See #407. According to the postgres documentation "The extract function returns values of type double precision" So I matched their behavior and the placeholder implementation returns the null double type.

>If this requires you to modify the parser to add support for EXTRACT, can you add a page on the wiki that provides a walkthrough on files you need to edit. 
I will add documentation about adding new functions to the wiki.

One concern I have is that string to timestamp casting does not exactly match the behavior of postgres and its a bit hard to understand. This might be a pain for students when they go to implement it.

We probably want to have them only implement a subset of the total EXTRACT functionality as there are 21 different cases, and some are a bit complicated without a library. We can talk about this at tomorrow's meeting.

**Comment by apavlo** [comment]
Did we ever merge this?

**Comment by MattPerron** [comment]
Yes. See #407
