### ISSUE TITLE
`psql_test.sh` is Non-Deterministic / Wrong

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#383]
I have no idea how the `psql_test.sh` script works at all on Travis. When I tried to run it on Jenkins, it fails because Peloton is producing a result that is different than the expected output. Upon inspection of the test queries, it appears that we are assuming the output is ordered from the DBMS (which it's not because it's unordered). When you try to add in an `ORDER BY` to make sure that the order is correct, the system crashes :-(

There are also queries that should fail (duplicate pkey) but Peloton allows that to go through.

https://github.com/cmu-db/peloton/blob/master/script/testing/dml/basic1.sql#L43
https://github.com/cmu-db/peloton/blob/master/script/testing/psql/psql_ref_out.txt#L59

So we're testing for the same output, but that output is just plain wrong. This whole test is fucked.

**Comment by apavlo** [comment]
@Michael-Tieying-Zhang Since #395 is merged, can you fix this? It should be really easy. You have to update the expected output file:

https://github.com/cmu-db/peloton/blob/master/script/testing/psql/psql_ref_out.txt

I have already updated the ORDER BY queries in [basic1.sql](https://github.com/cmu-db/peloton/blob/master/script/testing/dml/basic1.sql) to make them work.

Once the script works, re-enable the test in travis.yml:

https://github.com/cmu-db/peloton/blob/master/.travis.yml#L46

**Comment by Michael-Tieying-Zhang** [comment]
@apavlo Sure. I'll take care of it.

**Comment by Michael-Tieying-Zhang** [comment]
@apavlo Are you sure the script can work? The script has a lot of problems running on my desktop, such as the parameter PELOTON_ARGS, and the file path for output and input.

**Comment by apavlo** [comment]
Give me 10 minutes and I will check.

**Comment by apavlo** [comment]
@Michael-Tieying-Zhang What's the error message that you are getting?

**Comment by Michael-Tieying-Zhang** [comment]
There is no any output message when I run the script. After I removed the parameter PELOTON_ARGS from psql command, it (psql) can run but there is no output file. Then I removed delete output file command, and there is output file but it said there is no REF_OUT_FILE:

> ***FAIL***
> diff: ./psql_ref_out.txt: No such file or directory

**Comment by apavlo** [comment]
@Michael-Tieying-Zhang Looking into it...

**Comment by Michael-Tieying-Zhang** [comment]
@apavlo Take it easy ：)

**Comment by apavlo** [comment]
@Michael-Tieying-Zhang I'm on it. Easy fix.
