### ISSUE TITLE
UPDATE allows you to violate primary key constraint

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#384]
We don't let you INSERT a duplicate key:
```
postgres=# create table foo(id integer PRIMARY KEY, year integer);
create table foo(id integer PRIMARY KEY, year integer) 0
postgres=# insert into foo values(1, 100);
insert into foo values(1, 100) 1
postgres=# insert into foo values(1, 100);
insert into foo values(1, 100) 0
postgres=# SELECT * FROM foo;
 id | year 
----+------
  1 |  100
(1 row)
```

Well now that's good. But you better believe that we let you update an existing tuple with a duplicate primary key:
```
postgres=# insert into foo values(2, 200);
insert into foo values(2, 200) 1
postgres=# SELECT * FROM foo;
 id | year 
----+------
  1 |  100
  2 |  200
(2 rows)

postgres=# UPDATE foo SET id = 1 WHERE year = 200;
UPDATE foo SET id = 1 WHERE year = 200 1
postgres=# SELECT * FROM foo;
 id | year 
----+------
  1 |  100
  1 |  200
(2 rows)
```
In the above example, we should not allow you to have two of the same ids.

**Comment by Michael-Tieying-Zhang** [comment]
Do we support UNIQUE INDEX now?

**Comment by apavlo** [comment]
Yes. See the first example above where I try to INSERT the same key twice and it fails on the second one (as expected).

**Comment by Michael-Tieying-Zhang** [comment]
Got you. In that case, it's easy to fix.

**Comment by Michael-Tieying-Zhang** [comment]
The problem also exists for UNIQUE SECONDARY INDEX: 

`michael=# UPDATE foo SET age = 1000 WHERE year = 100;
UPDATE foo SET age = 1000 WHERE year = 100 1
michael=# select * from foo;
 id | age  | year 
----+------+------
  2 |   20 |  200
  1 | 1000 |  100
(2 rows)
`
The code should examine UNIQUE INDEX, but it did nothing: 
[https://github.com/cmu-db/peloton/blob/master/src/storage/data_table.cpp#L439](https://github.com/cmu-db/peloton/blob/master/src/storage/data_table.cpp#L439)
