### ISSUE TITLE
BeginTransaction is called for every query that is executed

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#394]
To execute a query, protocol.cpp invokes tcop.ExecuteStatement(). 

TrafficCop::ExecuteStatement in-turn invokes PlanExecutor::ExecutePlan

PlanExecutor::ExecutePlan calls txn_manager.BeginTransaction().

The current implementation is not aware of when a BEGIN/COMMIT query is received and creates transactions for individual queries.

**Comment by MattPerron** [comment]
closed with #400
