### ISSUE TITLE
Support reference count for varlen columns

### ISSUE THREAD

**Issue by jessesleeping** [cmu-db/peloton#396]
When creating a new version of a tuple in the update executor, if a column:
- is of VARCHAR or VARBINARY type
- and is not inlined
- and is not updated
then, instead of allocating a copy of the varlen value, we can add to its reference count in the varlen pool.

To support this, we need to
- support reference count in the varlen pool
- support copy by reference in update executor/project info
- (maybe) make garbage collection manager aware of the reference count

Related issues: 
- #349. After we have inlined varchar, extra check needs to be done in the executor to determine whether we should copy by reference or not.
- #395. When primary key is of varlen type, we need to modify its update logic too.

**Comment by jessesleeping** [comment]
While implementing this feature, I had a feeling that we need to rethink our design of the type system.

In order to copy

@MattPerron @apavlo

**Comment by apavlo** [comment]
Why do you think we need to re-implement our type system?

**Comment by jessesleeping** [comment]
I think we may need to rewrite the code for varlen type. 

Currently, we memcpy the varlen value whenever we call GetValue. I think what we can do is to copy varlen value by reference and make it as our default setting. Whenever we do need a physical copy of it, we can use something like a deep copy method.

In my local branch, I have partially supported this feature. Now the update executor will not memcpy a varlen value when projecting it directly. I will send a PR once I have fully tested it.

**Comment by jessesleeping** [comment]
As stated in the PR, now we can fully support reference count in varlen type. However, it's kind of hacking the type system to support the shallow copy feature we want.

I have profiled the performance gain from this feature with the YCSB micro-benchmark. Here is the [result](https://docs.google.com/spreadsheets/d/1nL0-rUCTE_niGRLvMt3paW1RZruc_Cavblno98sG99o/edit#gid=0).

Basically, we get 10x throughput at 10 thread compared to the original varlen pool. The performance is closed to the YCSB using integer instead of string. Compared to our old varlen pool, the new one is way too slow and not scalable.
