### ISSUE TITLE
Need to handle NULLs in JDBC

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#415]
If you load the TPC-C database with oltpbench and execute the following query the TPC-C OrderStatus txn from psql, you can see that we are returning the string "integer_null" for the `O_CARRIER_ID` field:

```
postgres=# SELECT O_ID, O_CARRIER_ID, O_ENTRY_D FROM OORDER WHERE O_W_ID = 1 AND O_D_ID = 1 AND O_ID = 2389;
 o_id | o_carrier_id |           o_entry_d           
------+--------------+-------------------------------
 2389 | integer_null | 2016-12-21 16:38:42.834000-05
(1 row)
```

But if you execute this this query in Java (by executing the OrderStatus txn), JDBC throughs an exception:

```
     [java] 16:55:24,246 (OrderStatus.java:171) ERROR - SELECT O_ID, O_CARRIER_ID, O_ENTRY_D   FROM OORDER WHERE O_W_ID = ?    AND O_D_ID = ?    AND O_C_ID = ?  ORDER BY O_ID DESC LIMIT 1
     [java] Invalid query result [W_ID=1, D_ID=1, C_ID=1553]
     [java] org.postgresql.util.PSQLException: Bad value for type int : integer_null
     [java]     at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2834)
     [java]     at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2060)
     [java]     at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2495)
     [java]     at com.oltpbenchmark.benchmarks.tpcc.procedures.OrderStatus.orderStatusTransaction(OrderStatus.java:167)
     [java]     at com.oltpbenchmark.benchmarks.tpcc.procedures.OrderStatus.run(OrderStatus.java:104)
     [java]     at com.oltpbenchmark.benchmarks.tpcc.TPCCWorker.executeWork(TPCCWorker.java:74)
     [java]     at com.oltpbenchmark.api.Worker.doWork(Worker.java:381)
     [java]     at com.oltpbenchmark.api.Worker.run(Worker.java:291)
     [java]     at java.lang.Thread.run(Thread.java:745)
```

**Comment by sid1607** [comment]
I checked it against Postgres. The correct psql output is -

```
tpcc=> SELECT O_ID, O_CARRIER_ID, O_ENTRY_D FROM OORDER WHERE O_W_ID = 1 AND O_D_ID = 1 AND O_ID = 2389;
 o_id | o_carrier_id |        o_entry_d        
------+--------------+-------------------------
 2389 |              | 2016-12-21 22:18:17.247
(1 row)
```
We shouldn't be sending 'integer_null' from the frontend. Instead, the protocol should send -1 as value length (which postgres does). While handling the absolute string 'integer_null' can fix this issue, how do we handle null values of all data types, considering that the null placeholder seems to be arbitrary?

**Comment by apavlo** [comment]
When you say "handle null values of all data types", do you mean internally in the system or for the network code?

It seems like we should just follow the postgres wire protocol.

**Comment by sid1607** [comment]
The wire protocol specification is simple and should be easy to implement. In peloton, it looks like null integers are materialized as 'integer_null' in the output. Similarly, null strings, null timestamps, etc will have their own way of getting materialized. The question is given a tuple and a column, how do I know if the value stored is the null value for that data type or not?

**Comment by apavlo** [comment]
Not sure what you're asking. This is what `Value::IsNul()` does

**Comment by sid1607** [comment]
For 32-bit Int, Value::IsNull() checks if the Value is INT_MIN. But we don't see INT_MIN in psql output; we see a string 'integer_null' which is generated by ToString. Do I have to modify ToString to return INT_MIN instead?

**Comment by apavlo** [comment]
Where else is ToString called? I think that we use it for GetInfo in a lot of places. You may want to make a ToPostgresString() method and handle it in there.
