### ISSUE TITLE
Peloton cannot support multi-statement queries from JDBC

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#422]
A JDBC client can send multiple queries together in a single "Parse" packet, separated by semicolons. While the parser can handle such requests, the frontend code for PSQL manually splits strings on ';' and processes them as separate queries and the frontend code for JDBC assumes single query strings everywhere. This portion of the protocol needs to be fixed.

**Comment by apavlo** [comment]
Replaced with #681
