### ISSUE TITLE
Send error code for Aborted Txns

### ISSUE THREAD

**Issue by sid1607** [cmu-db/peloton#425]
Rejected txns are happening because the server is aborting them when there is a conflict. The number is likely high for us because we are reading more tuples than we need to without that CUSTOMER index.

Send back a SQL State code when this occurs so that we know it's because of a conflict. Postgres sends status code "40001" which is defined as "serialization failure".

**Comment by sid1607** [comment]
@apavlo - With this commit Oltpbench for tpcc now catches the conflict aborts as an **expected** error -

````
22:08:47,606 (NewOrder.java:397) DEBUG - Caught an expected error in New Order
org.postgresql.util.PSQLException: 
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:778)
	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:811)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCWorker.executeWork(TPCCWorker.java:81)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:381)
	at com.oltpbenchmark.api.Worker.run(Worker.java:291)
	at java.lang.Thread.run(Thread.java:745)
22:08:47,607 (Worker.java:412) DEBUG - NewOrder/02  0 - 40001
22:08:47,607 (Worker.java:438) DEBUG - Postgres serialization
````

However, YCSB with Read-Update workload fails because the benchmark simply throws every Exception, unlike the TPCC implementation - https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/ycsb/procedures/ReadRecord.java#L34

Should I modify YCSB to handle aborts?

**Comment by apavlo** [comment]
What kind of abort do you mean?

I would probably focus on the things that we need to fix in the network layer.

**Comment by sid1607** [comment]
I mean conflicting aborts - if read and update occur simultaneously over common records then the transaction manager might abort one of them. While TPCC-oltpbench can handle such serialization failures (error code: '40001'), the YCSB-oltpbench code has no mechanism of catching and handling such failures.
Does this mean that such conflict aborts shouldn't happen in YCSB?

And by focusing on things to fix in network layer, do you mean that I should move on to the multiple-queries-separated-by-semicolons stuff?

**Comment by apavlo** [comment]
No need to change YCSB. 

Yes, proceed with the semi-colon fix.

**Comment by sid1607** [comment]
Should I issue a PR for these changes?

**Comment by apavlo** [comment]
Yes.

**Comment by sid1607** [comment]
Also - Even though https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/procedures/NewOrder.java#L397 considers this Exception as an expected error, it is logged as an unexpected error in the histograms - https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/api/Worker.java#L415

**Comment by apavlo** [comment]
Ok I can fix that.

**Comment by apavlo** [comment]
I think this has been fixed with the new networking layer rewrite.
