### ISSUE TITLE
Proposal on Changing IntsKey Design To Accelerate Key Comparison and Creation

### ISSUE THREAD

**Issue by wangziqi2013** [cmu-db/peloton#434]
Motivation
=======

Currently IntsKey are represented using an array of uint64_t. When a value is inserted or extracted, an inter-word and intra-word offset must be maintained to extract bytes from the source using bitwise shift and bitwise OR. Comparison and equality checking relies on word-wise comparison using a hand written tight loop.

This design has few deficiencies:

1. Inserting and Extracting a byte from a 64 bit word does excessively unnecessary jobs to extract a single byte. 
2. Comparison is not in the most efficient form because hand written loop does not utilize potentially faster SIMD extension
3. Tight loops may penalize branch prediction as is the case with current implementation

Proposed Design
===========

IntsKey is represented using an array of 8 byte char, the length of which is still specified by the template argument (and is maintained to be backward compatible with the current one). This makes state maintenance easier because for external routines only one variable is needed. Also, an array of char type enables byte aligned addressing which makes data access simpler (not necessarily faster, because internally the processor could not perform byte addressing)

Endianess
------------
 All integers are stored in **BIG-ENDIAN** form, to facilitate comparison as we will see later. Integral keys of any length could be supported.

When a key is inserted, it is first of all converted into **BIG-ENDIAN** by swapping bytes between two ends. After that the resulting big-endian is directly copied into the array using memcpy to avoid any loop (compiler knows the semantics of memcpy() and could optimize it into a single instruction for most of the time).

Sign Bit
---------
To accommodate for negative numbers, all integers are stored in a **modified SIGN-MAGNITUTE** format, which flips the sign bit of the classical 2's complement representation. This is justified by the static nature of IntsKey - no modification is allowed on IntsKey directly. The **SIGN-MAGNITUTE** format enables us to compare the magnitude of two numbers based purely on binary comparison. If this is yet not clear, please refer to how radix tree alters its signed integer key to match the goal.

For example, assume we have two 1 byte integer 127 and -1, with classical binary representation 0x7F and 0xFF. Binary comparison would yield -1 > 127 because 0xFF > 0x7F. If we adopt sign magnitude format, then the high bit will be flipped, and now 127 and -1 are represented respectively as 0xFF and 0x7F which yields the correct result. For multi-byte integers in big-endian this is always true.

Comparison
--------------
The comparison of IntsKey represented in big-endian and sign-magnitute format is a straightforward memcpy() on binary representation. As we have proved above the result of binary representation is sufficient for determining relationship between two IntsKey. The same applies for equality checking.

The best with memcpy() is that since compiler knows its semantics, there are chances that the compiler could optimize memcpy() into SIMD instructions, or reorder some instruction to favor super-scalar pipelines for potential intra-instruction parallelism. In addition, unrolling of tight loops avoids penalizing branch prediction.

Other Changes
-----------------
**Enabling direct access to class Tuple data**
This is desired because currently when we construct an IntsKey using class Tuple object, each field is examined and then a class Value object is constructed. This is a waste of cycles because we merely want the bit representation of integers stored inside class Tuple's data array, other than benefits brought by class Value object. Therefore, an interface must be added in class Tuple to allow direct access to its data members on a certain offset (could be obtained from schema)

Compatibility
-----------------
All member functions could be made back-ward compatible with the current implementation. However special care needs to be taken with the size of IntsKey, since currently the KeySize argument speficies key size in a unit of uint64_t rather than a single byte.

Review
--------
@apavlo @malin1993ml 

Reference
======
**On how ART transform its key**

a)  Unsigned  Integers:
The  binary  representation  of  unsigned  integers  already  has  the  desired  order.  However,  the endianness  of  the  machine  must  be  taken  into  account  when storing the value into main memory. On little endian machines, the  byte  order  must  be  swapped  to  ensure  that  the  result  is ordered from most to least significant byte.

b)  Signed   Integers:
Signed   two-complement   integers must  be  reordered  because  negative  integers  are  ordered  de-
scending  and  are  greater  than  the  positive  values.  An b bit integer x is  transformed  very  efficiently by  flipping  the  sign bit (using x XOR 2^b)

**Comment by tomasic** [comment]
I think -1 in signed magnitude format is 0x81. That is the high order bit
is 1 for negative numbers and zero for positive numbers and the lower seven
bits are simply the number without the sign.  Could I have a few more
examples as I don't quite understand what you want to do here.

Also - I don't quite understand instakey template. Is this a variable
length key? I think it is so I am not sure how to get SIMD to work on that.

For memcpy I didn't quite understand since you're discussing comparisons in
that paragraph. Could your provide an example?

**Comment by wangziqi2013** [comment]
@tomasic 

The sign-magnitude thing is my problem. I forgot to mention that it is not the standard one, but rather based on 2's complement. Just think of it as flipping the sign bit of 2's complement representation of integers. The intention is to make positive numbers always larger than negative numbers in binary representation, while maintaining their relative order . I will change this in the proposal to clarify. (think of how radix tree handles signed integers)

For the last two questions, I would say that IntsKey is a template with fixed length like this:

template<size_t KeySize> class IntsKey { ... };

KeySize is a compile time constant and the compiler could make use of it to either unroll tight loops or to issue SIMD for, say, 128 bit operation using SSE or 512 bit operation using AVX512.

memcpy() is just like strcpy() except that it does not treat 0x00 as the terminating byte. Since it is a library function, and KeySize is a compile time constant, it is possible that compiler optimize the routine using all these details.

Example: We compare IntsKey with three rows of int16_t

|   ID   | column 1  | column 2 |
|-------|------------|------------|
|row 1  |   123      |    456 |
row 2   |  123      |     -1 |
row 3   |  100      |     888 |

They will be represented in IntsKey like this (low byte to high byte):

row1: 0x80 0x7B 0x81 0xC8
row2: 0x80 0x7B 0x7F 0xFF
row3: 0x80 0x64 0X83 0X78

Binary comparison tells us that on the 3rd byte, 0x81 > 0x7F and thus row 1 > row2; 0x64 < 0x7B so row3 < row1 and row3 < row2

**Comment by malin1993ml** [comment]
This looks reasonable to me. My question is not directly related to the IntsKey, but related to how index scan works in general and how your optimized key fit into the whole workflow. So right now when executing an index scan, we first call index::Scan with the conjunction list we get from IndexScanPredicate (assuming it's not a full scan). Then secondly, for each tuple we got above, we call index::Compare to evaluate required predicate expressions.

That code might be from an ancient time. And to me it seems those two steps are redundant. What do you guys think? Also, if we keep that index::Compare call in the index scan execution, then as Andy mentioned, we have to iterate over the columns in the key and calls Tuple::GetValue to convert the index key data back into a Value and then do the comparison for each column. So if we do that, then we have to pay for the expensive comparison no matter how we optimize the IntsKey, right?

**Comment by wangziqi2013** [comment]
@malin1993ml Currently it is the case. We have to do one comparison for each key being scanned. This is necessary because the low key and high key might now be exact (e.g. a > 5 could not be represented as a lower bound, since we can only search for a >= 5, get back an iterator, and jump over the part where a = 5). This is true in any B+Tree based index because the partial ordering does not define what is the next element that is larger than 5.

However currently the Compare() function converts back every field in IntsKey to a class Value object, and then compare using these Value objects. This step is super inefficient since constructing a class Value object could be avoided, by directly comparing the field stored in compact form.

**Comment by malin1993ml** [comment]
@wangziqi2013 Thanks for explanation. I agree with that we should avoid constructing Value objects in Compare() by directly comparing the compact form for IntsKey. But it seems that we need to modify the interface for Compare() as well? Right now the Compare() function takes in a list of expressions and values for each column in the key. If we still use that interface, how could we apply those information on a compact form of IntsKey?

I understand the example you gave on IndexScanPredicate might not be exact. It seems to me that the only circumstances that we may return irrelevant keys are on the two boundaries of the scan range, right? If that is true, then I'm thinking of two optimization:
(1) I'm wondering given that we already have the scan conditions in the IndexScanPredicate, can we add some extra flags there to indicate whether we should include the two boundaries, and **only** check the two boundaries of the list of tuples returned by the index, instead of scanning all tuples again to check the condition for the second time?
(2) If we do the above checking, it seems that we no longer need those arguments with the Compare() function? We just need to compare the low key with the beginning of the returned list (or high key with the end of the returned list) in the compact/generic form again for correctness.

**Comment by wangziqi2013** [comment]
@malin1993ml What you said is actually partially being done by me right now. According to what @apavlo has expressed over this issue via email, it is more desirable to have Compare() function inside each key type (i.e. as a member function of class IntsKey, class GenericKey and class TupleKey), such that this function could have direct access to compact key internals. 

As for the Compare() argument I would prefer to make it another pull request since these two are not very must relevant. But indeed optimizing Scan() by only pruning the boundaries is what we are looking for.

After Andy is back let's have a meeting on issues like this.

**Comment by malin1993ml** [comment]
The comparator operator we have right now is doing the compare function
inside each key class. I guess we just need to modify that according to
your proposal.

What I described above is just for solving the un-exact tuples returned by
index scan. I agree that should be in a separate PR, and we can discuss
that with Andy.
