### ISSUE TITLE
DBMS Memory Usage Always Increases

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#442]
The DBMS process keeps growing in memory even if the logical database size does not increase.

For this test, I first loaded a 1GB YCSB database (scalefactor=1000) with OLTP-Bench. This was the size of the peloton process in htop before I started executing txns (yes I know there are better ways to get this measurement):
```
VIRT: 3708M
RES:  2227M
```

I then had a single worker thread execute only the `UpdateRecord` transaction for 20 minutes. The throughput was 11440 txn/sec. Afterwards, the DBMS size was this:
```
VIRT: 22.9G
RES:  21.4G
```

This should not happen since `UpdateRecord` never inserts or deletes a tuple. To make sure that the database was the same size, I ran a simple count query and it matched what should be there:

```
postgres=# SELECT COUNT(*) FROM USERTABLE;
 count(*) 
----------
  1000000
(1 row)
```

Something is obviously not right.

**Comment by apavlo** [comment]
@yingjunwu  - Latest version is still not reclaiming memory. CPU is not spiked at 100% anymore. Tested with 1fc29ad10ac86b7abaf3493a9ed24122e596189b 

**BEFORE**
```
VIRT: 3628M
RES:  3140M
```

**AFTER:***
```
VIRT: 20.6G
RES:  20.2G
```

AFAIK, the GC is supposed to be turned on:

https://github.com/cmu-db/peloton/blob/master/src/gc/gc_manager_factory.cpp#L19

**Comment by yingjunwu** [comment]
I'll take a look at it.
