### ISSUE TITLE
temporarily disable jdbc validator

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#447]
Our GC manager does not support dynamically creating/removing tables. This is because the GC manager requires the DBMS to register all the tables before execution. I am off campus so I cannot fix this problem for now. Since the jdbc validator has the logic of dynamically creating tables, I have to disable it temporarily and I will handle it later.

**Comment by apavlo** [comment]
I don't think that this should be marked as an issue. I don't think we should be in the habit of turning off tests.
