### ISSUE TITLE
Re-enable Index Test Cases for Bw-Tree

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#448]
There are a bunch of test cases that are currently disabled for the Bw-Tree. We need to turn them back on:

**IndexPerformanceTests**
This test only uses `INDEX_TYPE_BWTREE` as the input types, but then the code only does something if it's _not_ a BwTree: 
https://github.com/cmu-db/peloton/blob/master/test/performance/index_performance_test.cpp#L297

**IndexTests**
There are two test cases that are simply just turned off and not even compiled:
https://github.com/cmu-db/peloton/blob/master/test/index/index_test.cpp#L354
https://github.com/cmu-db/peloton/blob/master/test/index/index_test.cpp#L486

**Comment by apavlo** [comment]
Fixing `IndexPerformanceTests` was easy. Everything works for the BwTree but not the B+Tree.

**Comment by jarulraj** [comment]
#454 resolves this issue.
