### ISSUE TITLE
Adding Scan Limit Support

### ISSUE THREAD

**Issue by wangziqi2013** [cmu-db/peloton#457]
This proposal adds an extra interface to the index class called ScanLimit()

ScanLimit() takes the same set of argument as Scan(), with the addition of another argument called limit. The index is responsible for identifying whether ScanLimit() has the semantics of max() or min().

**Comment by apavlo** [comment]
@wangziqi2013 I think this is complete, right?

**Comment by wangziqi2013** [comment]
@apavlo Yes. I will close this.
