### ISSUE TITLE
Peloton crashes when run oltpbench for the second time

### ISSUE THREAD

**Issue by Michael-Tieying-Zhang** [cmu-db/peloton#474]
First start peloton,
Then run oltpbench. After oltpbench finishes, do not stop peloton, 
Then run oltpbench again.
Peloton will crash.

The failure is this: 
> peloton: /home/michael/peloton/src/gc/transaction_level_gc_manager.cpp:208: void peloton::gc::TransactionLevelGCManager::AddToRecycleMap(std::shared_ptr<peloton::gc::GarbageContext>): Assertion `(recycle_queue_map_.find(table_id) != recycle_queue_map_.end())' failed.

**Comment by poojanilangekar** [comment]
@aaron-tian Please check if this issue still exists. If yes, it can be assigned to somebody else. If not, please comment here and close the issue.

**Comment by pervazea** [comment]
First, this issue lacks sufficient detail. It should include:

- which benchmark? Oltpbench can run one of many benchmarks
- Specifics of the benchmark. The benchmarks have a number of parameters specified in the configuration file. Was the default used? Were specific parameters set?
- There is more than one way to run oltpbench. How was it run

In short, it lacks the detail required to reproduce the issue.

However:
- I ran tpcc, ycsb multiple times without shutting down peloton, without any failures
- Following on with TATP, ran fine first time, failed second time.
- Restarted peloton, ran TATP, seg faulted almost immediately
- Restarted peloton, ran TATP multiple times with no issues

No diagnostic information, as this was run on a release build. 

Conclusion: We don't have a simple, run twice and it fails issue.
We do have an issue with extended operation. The characteristics and reproducibility of which, remain to be determined. I'm closing this issue. We can open a new issue when we have a recipe for reproducing the failure.
