### ISSUE TITLE
bug under high-contention workloads

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#484]
I confronted a bug under high-contention workload. My script is as follows:

<?xml version="1.0"?>
<parameters>

    
    <driver>org.postgresql.Driver</driver>
    <dbtype>peloton</dbtype>
    <DBUrl>jdbc:postgresql://localhost:15721/ycsb</DBUrl>
    <username>postgres</username>
    <password>postgres</password>
    <isolation>TRANSACTION_READ_COMMITTED</isolation>
    
    
    <scalefactor>10</scalefactor>
    
    
    <terminals>20</terminals>
     <works>
        <work>
          <time>1200</time>
          <rate>unlimited</rate>
          <weights>0,0,0,100,0,0</weights>
        </work>
    </works>

    
    <transactiontypes>
        <transactiontype>
                <name>ReadRecord</name>
        </transactiontype>
        <transactiontype>
                <name>InsertRecord</name>
        </transactiontype>
        <transactiontype>
                <name>ScanRecord</name>
        </transactiontype>
        <transactiontype>
                <name>UpdateRecord</name>
        </transactiontype>
        <transactiontype>
                <name>DeleteRecord</name>
        </transactiontype>
        <transactiontype>
                <name>ReadModifyWriteRecord</name>
        </transactiontype>
    </transactiontypes>
</parameters>

When running this workload, we may confront two problems:

1. some transactions never terminate, which causes the GC bug observed previously;

2. assertion failure: 
`peloton: /home/yingjun/peloton/src/concurrency/timestamp_ordering_transaction_manager.cpp:528: virtual void peloton::concurrency::TimestampOrderingTransactionManager::PerformUpdate(peloton::concurrency::Transaction*, const peloton::ItemPointer&, const peloton::ItemPointer&): Assertion (new_tile_group_header->GetTransactionId(new_location.offset) == INVALID_TXN_ID) failed.
`

**Comment by jarulraj** [comment]
@yingjunwu @jessesleeping what's the status of this issue?

**Comment by apavlo** [comment]
I think that this was fixed in #672
