### ISSUE TITLE
Make source_validator.py a real pre-commit hook

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#498]
This one should be easy to do:

http://codeinthehole.com/writing/tips-for-using-a-git-pre-commit-hook/

**Comment by AngLi-Leon** [comment]
I think the pre-commit hook have to be installed locally. Do I need to add an installation instruction under wiki?

**Comment by apavlo** [comment]
Hmmm... I guess we can't just include the symlink in the repo since git doesn't do that.

Yes, I think that we should add it to the repo instructions.

**Comment by apavlo** [comment]
Fixed in #499
