### ISSUE TITLE
ORDER BY is incorrect for derived values

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#517]
ORDER BY is still broken. It does not work correctly if we have values that are computed from expressions:

Let's first create a table with a single column:
```
postgres=# CREATE TABLE foo (val INTEGER PRIMARY KEY);
CREATE TABLE foo (val INTEGER PRIMARY KEY) 0
postgres=# INSERT INTO foo VALUES (10);
INSERT INTO foo VALUES (10) 1
postgres=# INSERT INTO foo VALUES (20);
INSERT INTO foo VALUES (20) 1
```

We then need to set one of the values to be negative. We have to do it this way because we don't support inserting negative values directly:
```
postgres=# UPDATE foo SET val = val - 20 WHERE val = 10;
UPDATE foo SET val = val - 20 WHERE val = 10 1

postgres=# SELECT * FROM foo ORDER BY val;
 val 
-----
 -10
  20
(2 rows)
```

Now we will have a query that computes an expression on the `val` column but also has an `ORDER BY` clause on the `val` column:
```
postgres=# SELECT (val * -1) AS newVal FROM foo ORDER BY val ASC;
 newval 
--------
    -20
     10
(2 rows)
``` 

The above result is incorrect. It is sorting on `newVal` instead of `val`. If you add back `val` in the SELECT output, you get a correct sort order:
```
postgres=# SELECT val, (val * -1) AS newVal FROM foo ORDER BY val ASC;
 val | newval 
-----+--------
 -10 |     10
  20 |    -20
(2 rows)
```

**[SQL script is available here](https://github.com/cmu-db/peloton/files/728065/orderby-bug.txt)**

**Comment by PauloAmora** [comment]
I'll take a look into it.

**Comment by PauloAmora** [comment]
@apavlo  -- Is this correct?
```sql
postgres=# UPDATE foo SET val = val - 20 WHERE val = 10;
UPDATE foo SET val = val - 20 WHERE val = 10 1

postgres=# SELECT * FROM foo ORDER BY val;
 val 
-----
 -10
  20
(2 rows)
```

**Comment by apavlo** [comment]
@PauloAmora Yes, that's correct. It turns out you can actually just insert negatives if you put them in quotes:

```
INSERT INTO foo VALUES ('-10');
```

**Comment by PauloAmora** [comment]
I misunderstood, sorry about that.

As for the bug, it looks like a operation order problem. The projection plan is being put in the plan tree before the order by plan. Is it safe to move it to afterwards?

**Comment by apavlo** [comment]
@PauloAmora Add a test case for this problem. See that it fails. Then make your suggested change and see whether that fixes it. Then see whether it breaks any of the other tests.
