### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cmu-db/peloton#523]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like [the destructor for the class “UpdateClause”](https://github.com/cmu-db/peloton/blob/6b154b312e57aa10b573ce596ed95c3b51c566a2/src/include/parser/update_statement.h#L32 "Destructor for UpdateClause").

**Comment by apavlo** [comment]
Can you send a PR?

**Comment by elfring** [comment]
How do you think about to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")"?

**Comment by apavlo** [comment]
@elfring Yes, we should be using `unique_ptr` for these classes.

**Comment by apavlo** [comment]
We still haven't fixed this. We still should do this.

**Comment by poojanilangekar** [comment]
@apavlo I looked through all the files where there were nullptr checks, there are no check just before a delete. It is usually in an if statement where it combines other function calls. So I am closing this issue.

**Comment by elfring** [comment]
[How do you think about](https://github.com/cmu-db/peloton/blob/8a41d7c53a1543d546733a4a67a4e22f75fec64e/src/catalog/system_catalogs.cpp#L70 "Update candidate: Destructor for SystemCatalogs") to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
