### ISSUE TITLE
Secondary index creation does not index existing values

### ISSUE THREAD

**Issue by PauloAmora** [cmu-db/peloton#529]
The index scan only retrieves values added AFTER index creation.

Start by creating a table and inserting some data:
```sql
paulo=# create table foo (a integer, b integer);
create table foo (a integer, b integer) 0
paulo=# insert into foo values (1, 200);
insert into foo values (1, 200) 1
paulo=# insert into foo values (2, 300);
insert into foo values (2, 300) 1
paulo=# insert into foo values (3, 400);
insert into foo values (3, 400) 1
paulo=# insert into foo values (4, 800);
insert into foo values (4, 800) 1
```
Without indexes, data is retrieved fine (through `SeqScan`)
```sql
paulo=# select b from foo where a < 10;
  b  
-----
 200
 400
 300
 800
(4 rows)
```
Then, we create the index on column `a`
```sql
paulo=# create index i1 on foo(a);
create index i1 on foo(a) 0
```
When we try to retrieve data again:
```sql
paulo=# select b from foo where a < 10;
 b 
---
(0 rows)
```
If we add new data after index creation, it shows up fine
```sql
paulo=# insert into foo values (5, 600);
insert into foo values (5, 600) 1
paulo=# select b from foo where a < 10;
  b  
-----
 600
(1 row)
```

Script is located here:
http://pastebin.com/9GjbiUfm

**Comment by apavlo** [comment]
Oh this a good one

**Comment by apavlo** [comment]
We talked about this today at the team meeting. I think the right approach is to add a new executor called `PopulateIndex` that is able to take the output of a `SeqScanExecutor` and insert the tuples into the index. There are a bunch of corner cases that we are going to have to handle (e.g., keys that get deleted after the scan starts) but this will be a good first step for adding support for DDL changes.

**Comment by PauloAmora** [comment]
I can take a look at this

**Comment by PauloAmora** [comment]
So, I managed to get this fixed, will submit a PR tomorrow, after more comprehensive tests

**Comment by PauloAmora** [comment]
@apavlo 
Is it possible to have an executor without a corresponding plan? I am failing `seq_scan_test` because one of the test cases creates a `MockExecutor` and does not add a corresponding plan to it.

**Comment by apavlo** [comment]
@jarulraj Can you look into this?
