### ISSUE TITLE
Test Travis fast fail for 

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#538]
Can someone modify `.travis.yml` to have it fail right away when `source_validator.py` fails?
We still want to run all the other builds and tests though to the very end even if they fail.

https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/

**Comment by danielcompton** [comment]
I've started working on this, but am having trouble making fast_finish actually finish any faster. https://travis-ci.org/danielcompton/peloton/builds/201264982. Just leaving a note here so work isn't duplicated.

**Comment by tcm-marcel** [comment]
Implemented in #989
