### ISSUE TITLE
Revive CASE code + tests

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#548]
We use to support `CASE` but then it got removed by accident over the summer. The original commit is here:

https://github.com/cmu-db/peloton/commit/c537df4a016920fbd4b2fda3b12da4c82e5f34c0

There are additional commits made afterwards for fixing the test cases:

https://github.com/cmu-db/peloton/commit/a2307f7cc5df3043acebed0e2c1625b61f96989f

Somebody needs to dig through the history and find the latest version of `CaseExpression` and restore it. You're not going to be able to just copy the old file into the codebase because we rewrote the type system and expression interface, but it should be a relatively easy task.

There is going to be a bunch of bridge code that we used to have for converting the Postgres plan to a Peloton plan. We may also want to bring this back later (for #521) but for now we don't need it. Note also that the parser does not support `CASE` so all the testing will have to be done procedurally for now.

**Comment by apavlo** [comment]
FYI, @thejdeep is working on this. I can't assign him officially without adding him to the team.

**Comment by IanQS** [comment]
Not sure if this helps but the last place that case_expression.h existed is

https://github.com/cmu-db/peloton/commit/d0c1e97530ec49cd251f1d3a1ff3c7e37f5b886c

**Comment by seojungmin** [comment]
Fixed in #559
