### ISSUE TITLE
configurations

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#557]
We should determine where to put all kinds of configuration variables and magic numbers. Now these variables are maintained mainly in two different files: [configuration.h](https://github.com/cmu-db/peloton/blob/master/src/include/configuration/configuration.h) and [types.h](https://github.com/cmu-db/peloton/blob/master/src/include/type/types.h). It's confusing, and we should solve this problem.

**Comment by seojungmin** [comment]
There are typically two kinds of configurations: one that a user could set and the others that are normally set by developers.  Could we keep all the user-setting ones in configuration.h and the others in types.h for example?  This may have been the original intention of configuration.h and types.h, and I may be repeating it again here.

**Comment by apavlo** [comment]
See #494

**Comment by poojanilangekar** [comment]
Fixed in #736
