### ISSUE TITLE
CMake Warnings for Postgres client libs

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#595]
@hanli32 - I am able to build the new test cases that use `libpqxx` but cmake is not finding the library.

@jarulraj - Why is this a warning and not an error?

```
$ cmake -DCMAKE_BUILD_TYPE=RELEASE ..
<SNIP>
CMake Warning at cmake/Dependencies.cmake:49 (find_package):
  By not providing "FindLIBPQXX.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LIBPQXX", but
  CMake did not find one.

  Could not find a package configuration file provided by "LIBPQXX" with any
  of the following names:

    LIBPQXXConfig.cmake
    libpqxx-config.cmake

  Add the installation prefix of "LIBPQXX" to CMAKE_PREFIX_PATH or set
  "LIBPQXX_DIR" to a directory containing one of the above files.  If
  "LIBPQXX" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:41 (include)
<SNIP>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pavlo/Documents/Peloton/Github/peloton/build
```

I installed the packages using the new version of `scripts/installation/packages.sh`:
```
$ dpkg -l | grep libpqxx
ii  libpqxx-4.0     4.0.1+dfsg-3ubuntu2  amd64  C++ library to connect to PostgreSQL
ii  libpqxx-dev     4.0.1+dfsg-3ubuntu2  amd64  C++ library to connect to PostgreSQL (development files)
```

**Comment by CHUYilei** [comment]
Hi, I have an assumption: in peloton/cmake/Dependencies.cmake, only this line "list(APPEND Peloton_LINKER_LIBS "-lpqxx -lpq")" works.
I tried on my own machine with build directory removed: 

(1) I delete
 `find_package(LIBPQXX)` 
`include_directories(${LIBPQXX_INCLUDE_DIRS})`
`link_directories(${LIBPQXX_LIBRARY_DIRS})` in [peloton/cmake/Dependencies.cmake](https://github.com/cmu-db/peloton/blob/master/cmake/Dependencies.cmake).
Only `list(APPEND Peloton_LINKER_LIBS "-lpqxx -lpq")` remains.
(2) I remove [peloton/cmake/Modules/FindLibPQXX.cmake](https://github.com/cmu-db/peloton/blob/master/cmake/Modules/FindLibPQXX.cmake)

Then I run 
`mkdir -p build`
`cd build`
`cmake -DCMAKE_BUILD_TYPE=Release ..`
`make -j4`
`make install`
`make packet_manager_test`
`./test/packet_manager_test`
There seems no problem in compiling/running.

Should we send a new PR for this change?

**Comment by apavlo** [comment]
@CHUYilei I don't think you want to remove the dependency check. You want it to throw an error if it can't find the packages (which it doesn't do right now).

Try removing the libpqxx packages from your machine. Then run `cmake`. It should fail.

**Comment by CHUYilei** [comment]
I see. My confusion is [FindLIBPQXX.cmake](https://github.com/cmu-db/peloton/blob/master/cmake/Modules/FindLibPQXX.cmake) file is in the correct location: under cmake/Modules, which should be in CMAKE_MODULE_PATH according to [this.](https://github.com/cmu-db/peloton/blob/master/CMakeLists.txt#L26) I still don't understand the cause of the warning 

> By not providing "FindLIBPQXX.cmake" in CMAKE_MODULE_PATH

**Comment by apavlo** [comment]
It doesn't work. You can run cmake and have it pass without the libpqxx

```
[100%] Linking CXX shared library ../lib/libpeloton.so
/usr/bin/ld: cannot find -lpqxx
/usr/bin/ld: cannot find -lpqxx
collect2: error: ld returned 1 exit status
src/CMakeFiles/peloton.dir/build.make:5129: recipe for target 'lib/libpeloton.so.0.0.5' failed
make[2]: *** [lib/libpeloton.so.0.0.5] Error 1
CMakeFiles/Makefile2:1158: recipe for target 'src/CMakeFiles/peloton.dir/all' failed
make[1]: *** [src/CMakeFiles/peloton.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jarulraj** [comment]
diff --git a/cmake/Dependencies.cmake b/cmake/Dependencies.cmake
index 1eac403..6e9a74e 100644
--- a/cmake/Dependencies.cmake
+++ b/cmake/Dependencies.cmake
@@ -46,10 +46,9 @@ set(MEMORYCHECK_COMMAND_OPTIONS "--trace-children=yes --leak-check=full")
 set(MEMORYCHECK_SUPPRESSIONS_FILE "${PROJECT_SOURCE_DIR}/third_party/valgrind/valgrind.supp")
 
 # --[ LibPQXX
-find_package(LIBPQXX)
-include_directories(${LIBPQXX_INCLUDE_DIRS})
-link_directories(${LIBPQXX_LIBRARY_DIRS})
-list(APPEND Peloton_LINKER_LIBS "-lpqxx -lpq")
+find_package(LibPQXX)
+include_directories(SYSTEM ${LIBPQXX_INCLUDE_DIRS})
+list(APPEND Peloton_LINKER_LIBS ${LIBPQXX_LIBRARIES})

**Comment by jarulraj** [comment]
Can you make this change in the Cmake file?

**Comment by pmenon** [comment]
You also need change `find_package(LibPQXX)` to `find_package(LibPQXX REQUIRED)` to get CMake to throw an error if you don't have the library.

**Comment by CHUYilei** [comment]
@jarulraj Only `-lpqxx` is needed. `-lpq` can be removed. 
However, using 
`find_package(LibPQXX)`
`include_directories(SYSTEM ${LIBPQXX_INCLUDE_DIRS})`
`list(APPEND Peloton_LINKER_LIBS ${LIBPQXX_LIBRARIES})`
always provide `undefined reference to pqxx` error. 

My question here is where did you define **`LIBPQXX_LIBRARIES`**?

Do you think a combination like 
`find_package(LibPQXX)`
`include_directories(SYSTEM ${LIBPQXX_INCLUDE_DIRS})`
`list(APPEND Peloton_LINKER_LIBS "-lpqxx")`
would be better? Both check the lib installation and do the linking.

**Comment by jarulraj** [comment]
It's defined here: https://github.com/cmu-db/peloton/blob/master/cmake/Modules/FindLibPQXX.cmake

No, you will only need to use `${LIBPQXX_LIBRARIES}`. You don't have to hard-code them. Try using this: `find_package(LibPQXX REQUIRED)` instead of `find_package(LibPQXX)`.

**Comment by CHUYilei** [comment]
@jarulraj I did exactly as you mentioned above, and FindLibPQXX.cmake is in right place. However, `FindLibPQXX.cmake` doesn't raise warning/error. The `undefined reference to pqxx` error occurs when I run `make packet_manager_test` at the last step. May I know did you successfully make packet_manager_test using the above configuration?

**Comment by jarulraj** [comment]
Yes. Can you run `make packet_manager_test VERBOSE=1` and share the output?

**Comment by apavlo** [comment]
@CHUYilei Send a PR so that we can see your latest version.

**Comment by CHUYilei** [comment]
@jarulraj Here is the output file.
[output.txt](https://github.com/cmu-db/peloton/files/891891/output.txt)

**Comment by CHUYilei** [comment]
@apavlo I haven't succeeded using Joy's method. I think my original method is hardcoding and is still not the correct standard version we want. I prefer sending a PR when Joy's method works on my machine, is that OK?

**Comment by apavlo** [comment]
@CHUYilei Send the PR anyway so that we can try to help. It's easier that way to see what you have and then we can work together to fix it.

**Comment by jarulraj** [comment]
@CHUYilei Let's give it a final shot.

+# --[ PQXX
+find_package(PQXX REQUIRED)
+include_directories(SYSTEM ${PQXX_INCLUDE_DIRECTORIES})
+list(APPEND Peloton_LINKER_LIBS ${PQXX_LIBRARIES})

**Comment by CHUYilei** [comment]
@jarulraj This final shot works well! I will send a PR for it

**Comment by CHUYilei** [comment]
@jarulraj The PR's [travis](https://travis-ci.org/cmu-db/peloton/jobs/218321546) build crashes when running `make check -j4`. I tried this command locally with current configuration, and it worked well with no error like below. I wonder what might be the reason.

> [ 68%] Building CXX object test/CMakeFiles/storage_manager_test.dir/storage/storage_manager_test.cpp.o
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
