### ISSUE TITLE
No "kind" information in AExprTransform

### ISSUE THREAD

**Issue by nblintao** [cmu-db/peloton#607]
For the function `AExprTransform` in `postgrespaser.cpp`, it gets the type of the expression from the `name` field. But this is not enough for some kinds of expressions like `AEXPR_DISTINCT` (whose `name` is `=`, but has nothing to do with `COMPARE_EQUAL` actually). So now `IS DISTINCT FROM` will be considered as `=`, which is not true.

A fix of this is inducting the `target_type` from the `kind` field in `A_Expr`, instead of from the `name` field.

I am currently developing triggers for Peloton, where many SQLs has expressions like `IS DISTINCT FROM`. It would be great if we could support types like this. Hope someone experienced could help fix that. (`AExprTransform` function is highly shared, so I am afraid that changing it by myself may mess up the system 😂)

Thanks!

**Comment by apavlo** [comment]
@nblintao FYI, Hao is going to look at this now for you.

**Comment by haojin2** [comment]
Hi Tao,
Would you please provide some example queries so that I can add support for them?
Hao

**Comment by nblintao** [comment]
Thanks, @apavlo @haojin2 !
```sql
CREATE TRIGGER check_update
    BEFORE UPDATE ON accounts
    FOR EACH ROW
    WHEN (OLD.balance IS DISTINCT FROM NEW.balance)
    EXECUTE PROCEDURE check_account_update();
```
This is one example from [Postgres doc](https://www.postgresql.org/docs/9.1/static/sql-createtrigger.html).

Another thing is the current type does not handle `<>` correctly. This could be easily resolved by my changes to types.cpp at https://github.com/cmu-db/peloton/pull/613/commits/19b3f4d76677dc74a7945dd1b647bc9baa2f2227

**Comment by luochenUmich** [comment]
@nblintao Is this still an issue? If not, we can help you

**Comment by haojin2** [comment]
This is handled already in Issue #624

**Comment by nblintao** [comment]
LGTM. Thank you!
