### ISSUE TITLE
Moving transaction starting point in tcop from executing phase to preparing phase

### ISSUE THREAD

**Issue by AngLi-Leon** [cmu-db/peloton#623]
Currently, transaction begins (see [single statement transaction](https://github.com/AngLi-Leon/peloton/blob/master/src/tcop/tcop.cpp#L227) / [explicitly call "begin" transaction](https://github.com/AngLi-Leon/peloton/blob/master/src/tcop/tcop.cpp#L93)) at the point of [executing statements](https://github.com/AngLi-Leon/peloton/blob/master/src/tcop/tcop.cpp#L160). 

The new catalog system enables binder to check table existence and visibility from catalog tables, which requires transactions when [preparing statements](https://github.com/AngLi-Leon/peloton/blob/master/src/tcop/tcop.cpp#L149)

This way, binder can use catalog's GetXXXWithName methods to check database/table/index visibility (with transaction) and executor can use catalog's GetXXXWithOid methods to get database/table/index directly from storage layer (without checking existence again).

**Comment by apavlo** [comment]
Was this fixed for #592?

**Comment by AngLi-Leon** [comment]
Yes.

**Comment by apavlo** [comment]
Correction. This is not fixed.

@yingjunwu We still need this.

**Comment by yingjunwu** [comment]
I'll take a look at it.

**Comment by yingjunwu** [comment]
@hanli32 @CHUYilei This is related to the single statement transaction we are currently working on. Let's have a discussion on it.

**Comment by yingjunwu** [comment]
@hanli32 I think this is fixed, right?

**Comment by apavlo** [comment]
@ChTimTsubasa This is fixed now, right?

**Comment by ChTimTsubasa** [comment]
Yes, @haoxianghua fixed this in the summer.

**Comment by haoxianghua** [comment]
Yes, I fixed this summer.
