### ISSUE TITLE
Add support for CHECK in CREATE TABLE

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#625]
The "Constraints" team (@vittvolt, @xinzhang1234, +1) have added support for `CHECK` constraints in the `DataTable`. They currently can only test this if they programmatically create the tables. This is because `CREATE TABLE (...)` does not support the `CHECK` keyword in column definitions.

The steps to complete this task are as follows:

1. Add support for extracting the `CHECK` metadata in the `PostgresParser`. 
2. Modify the planner/optimizer to add this metadata to the `CreatePlan` object. We will need to convert this metadata into the necessary `AbstractExpression` tree.
3. Add support in the `CreateExecutor` to install this constraint into the `DataTable`.
4. Make sure that we store this constraint information in the new catalog (#592)

Here is the simple table that we want to support:

```sql
CREATE TABLE foo (
  id INT CHECK (id > 0)
);
```

**Comment by luochenUmich** [comment]
@vittvolt @xinzhang1234  I am modifying parser to support this. However, I need to know where to store this parsed data. I looked at your Constraint PR and didn't see you guys changing the create_statement. CreateStatement is the place where this parsed data should be stored. Probably you guys should add a vector<Constraint> member variable in ColumnDefinition. Let me know when you guys add that. Once that's merged, I can start adding parser support.
