### ISSUE TITLE
BigInt serialization mistakenly writes int32

### ISSUE THREAD

**Issue by phisiart** [cmu-db/peloton#629]
In `BigintType::SerializeTo()`:
https://github.com/cmu-db/peloton/blob/master/src/type/bigint_type.cpp#L292
The code writes a `int32_t` instead of `int64_t`.

In `BigintType::DeserializeFrom()`:
https://github.com/cmu-db/peloton/blob/master/src/type/bigint_type.cpp#L299
The code reads a `int64_t` correctly.

**Comment by apavlo** [comment]
This should be an easy fix. Can you submit a PR?

**Comment by phisiart** [comment]
Okay, wait a min.
