### ISSUE TITLE
Implement Sqrt operator

### ISSUE THREAD

**Issue by hzxa21** [cmu-db/peloton#638]
"|/" operator to compute the sqrt root of the value is not supported for now although we already have the Sqrt functions implemented for different value types.

``` sql
postgres=# create table test(a decimal(5,2));
create table test(a decimal(5,2)) 0
postgres=# insert into test values(2.5);
insert into test values(2.5) 1
postgres=# select sqrt(a) from test;
function sqrt not found.
postgres=# select |/ a from test;
No ExpressionType conversion from string '|/'
```

See
https://www.postgresql.org/docs/9.4/static/functions-math.html
https://github.com/cmu-db/peloton/blob/7a3483e137f454602bda918d3932604f1f34bf77/src/type/decimal_type.cpp#L182
https://github.com/cmu-db/peloton/blob/7a3483e137f454602bda918d3932604f1f34bf77/src/type/integer_type.cpp#L161

**Comment by mrmiywj** [comment]
Hi, is this issue available for in-coming CMU student? I am a MS student in INI 17 fall and find this project interesting. Could I pick this up?

**Comment by apavlo** [comment]
@mrmiywj Yes! Go for it. Let me know if you need more guidance.
