### ISSUE TITLE
Create separate fast/full check targets in Cmake

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#639]
**This is blocking us from merging the LLVM engine so we need to do this immediately.**

The new LLVM engine code (#612) takes too long to execute all of the tests using Valgrind on gcc4. We are timing out on Travis. Switching to the '-fsanitize' flag in gcc greatly speeds up the build time and will provide us with a basic sanity check. But we obviously want to still execute the full tests with Valgrind.

Thus, I propose that we need do the following:

1. Switch the `check` target in Cmake  to use '-fsanitize' instead of Valgrind. The tricky thing is that we are going to need to still support the same [suppressions](https://github.com/cmu-db/peloton/blob/master/third_party/valgrind/valgrind.supp) that we have defined for Valgrind. I poked around on the Internet for a bit and didn't see any obvious way to do this.

2. Add a new Cmake target called `check-full` that does what `check` currently does now (i.e., use Valgrind to run all the unit tests).

3. Parameterize the Travis build script to take in a build target. This way we can set what kind of tests we want to run on Travis and Jenkins but then still use the same travis.yml file. I started doing something similar this last week to support different `CMAKE_BUILD_TYPE` flags but I never finished ( https://github.com/apavlo/peloton/commit/399ae884595fbf33382443b5bbc3dfeb5946f18b).

4. Once we have the build parameters working, change Travis to do the fast tests on each PR and then setup Jenkins to perform nightly build tests with the full valgrind tests.

**Comment by pmenon** [comment]
I attempted this on Friday, it isn't hard to do.

**Comment by apavlo** [comment]
@pmenon What part was easy to do?

**Comment by seojungmin** [comment]
https://github.com/google/sanitizers/wiki/AddressSanitizer#turning-off-instrumentation <https://github.com/google/sanitizers/wiki/AddressSanitizer#turning-off-instrumentation>

__attribute__((no_sanitize_address)) is found to be working and is the only way with gcc4.  And, “-fsanitize_blacklist” option, analogous to the suppression feature from Valgrind, does not work with gcc4.

Since this sanitizer feature may not produce the same false positives, I think we better try it out.

**Comment by apavlo** [comment]
Do we have a compelling reason to still support gcc4.9?

**Comment by jarulraj** [comment]
Sure, I will add this asap. @pmenon Do all the tests pass with `-fsanitize`?

**Comment by pmenon** [comment]
@apavlo Adding the new targets wasn't difficult. The one tricky thing is that `-fsanitize` flags and Valgrind dont' work together (i.e., Valgrind won't work on tests compiled with sanitization flags).

@jarulraj 11/112 tests fail when using `-fsanitize=address -fsanitize=leak`. I haven't tried the memory or thread sanitizers.

**Comment by apavlo** [comment]
@pmenon Do the failures match up with the things that we're suppressing in valgrind? How much work would it be for us to switch to clang?

**Comment by pmenon** [comment]
When using address/leak sanitizers, the failures aren't anything in the suppressions. The majority are from peloton::GenericArray, and the transaction GC test seg faults.

When using the thread sanitizer, the index performance tests (specifically BWTree) throws many many errors. I'll take a deeper look later today.
