### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by mrmiywj** [cmu-db/peloton#642]
I found that the urls in the wiki are out of date. I will update them in soon days. It is a track issue.

**Comment by mrmiywj** [comment]
Update the urls in [Adding an SQL operator](https://github.com/cmu-db/peloton/wiki/Adding-an-SQL-Operator) except the `plan map` and `example operator`

- Questions:
Where are `plan map` code located now.. It seems they have been removed...

- Next:
Update the out-dated content, such as namespace hierarchies.

**Comment by apavlo** [comment]
Was there something that we needed to fix with this issue?
