### ISSUE TITLE
Need a compilation flag to disable LLVM

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#654]
Students in the class need to turn off the LLVM for their projects. We need a compile time flag or something for them to use.

This is urgent.

**Comment by apavlo** [comment]
@rohit-cmu @poojanilangekar A short term fix is to change this function to always return false:

https://github.com/cmu-db/peloton/blob/master/src/codegen/query_compiler.cpp#L43

**Comment by seojungmin** [comment]
We have a flag for turning the codegen off.  See below:

jungmin@ubuntu:~/w/work/peloton-tony/build$ ./bin/peloton -h
peloton: Usage Info: 

  Flags from /home/jungmin/w/work/peloton-tony/src/configuration/configuration.cpp:
    **-codegen (Enable code-generation for query execution (default: true))
      type: bool default: true**
    -display_configuration (Display configuration (default: false)) type: bool
      default: false
    -h (Show help) type: bool default: false currently: true
  ...

**Comment by apavlo** [comment]
@seojungmin I think they need to be able turn it off programmatically from the unit tests.

**Comment by pmenon** [comment]
I **think** they should just be able to do `FLAGS_codegen = false;` to disable codegen.

**Comment by pmenon** [comment]
We can close this. Codegen can be programmatically turned off by setting `FLAGS_codegen = false`.

**Comment by apavlo** [comment]
Can you please add documentation to the wiki?
