### ISSUE TITLE
select clause cause crushes 

### ISSUE THREAD

**Issue by lishuomountain** [cmu-db/peloton#663]
After installing peloton, I follow the instructios in Terminal wiki (https://github.com/cmu-db/peloton/wiki/Terminal). When I execute "select * from foo;", the peloton crashes with the following info:

postgres=# select id from foo;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

and 

peloton: /home/lsh/Downloads/llvm-3.7.0/lib/IR/Instructions.cpp:957: llvm::LoadInst::LoadInst(llvm::Type*, llvm::Value*, const char*, bool, llvm::Instruction*): Assertion `Ty == cast<PointerType>(Ptr->getType())->getElementType()' failed.
Aborted (core dumped)

There is no llvm 3.7 in the repositories of ubuntu 14.04, so I installed llvm 3.7.0 from source files.

Ubuntu 14.04, gcc 4.8.5

**Comment by apavlo** [comment]
@lishuomountain Can you also provide the schema and data that you were testing?

You can install llvm-3.7 from packages on 14.04. We will update the installation instructions.

**Comment by pmenon** [comment]
I just tested this on master with GCC 4.8.5, 4.9.4 and 5.4.1 on Ubuntu 14.04 and it all works.

@lishuomountain please use the llvm-3.7 packages for ubuntu 14.04. Also, attach the output from the peloton process.

**Comment by lishuomountain** [comment]
It's OK. Thank you!
