### ISSUE TITLE
Installation page in wiki has a broken link to vagrant setup on OSX

### ISSUE THREAD

**Issue by bitmybytes** [cmu-db/peloton#673]
Installation page in wiki has a broken link to vagrant setup on OSX.

I have a fix here at https://github.com/bitmybytes/peloton-wiki/pull/1

Thanks,
Arun

**Comment by apavlo** [comment]
Can you send a PR?

**Comment by bitmybytes** [comment]
Hi @apavlo, I can but looks like Github doesn't support an easy way for non-collaborators to do PR on wiki.

**Comment by apavlo** [comment]
Got it. I will fix tomorrow.

**Comment by apavlo** [comment]
Fixed! 

https://github.com/cmu-db/peloton/wiki/Installation
