### ISSUE TITLE
code from libpmem was stripped of its license, and it is out of date

### ISSUE THREAD

**Issue by andyrudoff** [cmu-db/peloton#677]
Hi folks,

We (the NVML team) were happy to discover pelotondb with support for persistent memory built in.  We noticed code from libpmem was used and you nicely referenced the original source file here:

https://github.com/cmu-db/peloton/blob/master/src/storage/storage_manager.cpp#L57

But you pulled in the code without pulling in the associated license.  I know it is a bit of a pain, but we respectfully request you include the license along side the code, as required by the license terms.

We're very happy the code is useful to you, and very happy to have you using it.  We encourage its use either by linking with the library, copying the library into your tree, or copying whatever code fragments you need.  We just ask that the license follow the code.

As a side note, the code you have is out of date and still refers to a deprecated instruction, as explained here:

https://software.intel.com/en-us/blogs/2016/09/12/deprecate-pcommit-instruction

Also, I noticed that your code does not do the "is_pmem" checks, so if you use it on a DAX-capable file system, like ext4 or XFS, you will not be guaranteed that the flushing calls will work correctly with the current state of the Linux kernel.  It is up to you of course, but you may find it easier to just use libpmem directly, since we are committed to keeping it up to date and validated.

Thanks.

-andy

**Comment by apavlo** [comment]
@jarulraj This is urgent. Please fix *immediately*

**Comment by jarulraj** [comment]
@andyrudoff Thanks for the helpful feedback. I have added the NVML license, and will refactor the code to directly make use of `libpmem`.

**Comment by apavlo** [comment]
@andyrudoff This has been fixed during the summer.
