### ISSUE TITLE
Compile Issue on Ubuntu (destructor and nonnull compare)

### ISSUE THREAD

**Issue by ChTimTsubasa** [cmu-db/peloton#678]
Hi,

**I am following the installation guide in https://github.com/cmu-db/peloton/wiki/Installation.
At the 'Build and install Peloton' step, after typing 'make -j4', I got the following error message:**

/home/tim/Documents/project/peloton/src/codegen/function_builder.cpp: In destructor ‘peloton::codegen::FunctionBuilder::~FunctionBuilder()’:
/home/tim/Documents/project/peloton/src/codegen/function_builder.cpp:67:64: error: throw will always call terminate() [-Werror=terminate]
     throw Exception{"FunctionBuilder::Finish() was not called!"};
                                                                ^

**After commenting out this line and another line with similar problem(/src/codegen/vectorized_loop.cpp:36), I got another compile error:**

/home/tim/Documents/project/peloton/src/include/optimizer/property.h:52:25: error: nonnull argument ‘this’ compared to NULL [-Werror=nonnull-compare]
     if (this != nullptr && typeid(*this) == typeid(T)) {

**My OS is Ubuntu 16.10 and my compiler is gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)**

**Comment by apavlo** [comment]
I don't think we've tried on gcc6. Can you try on gcc5?

**Comment by ChTimTsubasa** [comment]
It works on gcc5
