### ISSUE TITLE
keyword case-insensitive

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#688]
According to Postgres' document (https://www.postgresql.org/docs/current/static/plpgsql-structure.html), all the keywords, including `BEGIN` and `END`, must be case-insensitive.

**Comment by apavlo** [comment]
Is it just a matter of fixing all of the hardcoded string matches in the `PacketManager`?

https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L281
https://github.com/cmu-db/peloton/blob/master/src/wire/packet_manager.cpp#L245

Also, why is the `query_type` a string here? That makes it slower to pattern match. It should be an `enum class`.

@dengyuchenkit Can you fix this? This is part of the larger overhaul of the networking code that we want to do this sumer.

**Comment by yingjunwu** [comment]
Yes it's an easy fix. Just fixing all the hardcoded string matches would be enough.

**Comment by dengyuchenkit** [comment]
Just want to make sure first that should I change the type of query_type or just fix the hard-coded string matches? Fixing the hard-coded string matches seems straightforward.

**Comment by apavlo** [comment]
Yes, start with fixing the case. Send a PR for that. Then work making it
not be a string.

**Comment by dengyuchenkit** [comment]
#694

**Comment by apavlo** [comment]
Fixed in #694
