### ISSUE TITLE
Move codegen translators to sub-directory

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#690]
Right now `src/include/codegen` has almost all of the code for the codegen component. I think that we should move the translators to `src/include/codegen/translators` to clean up this directory at bit.

I can do this tomorrow on my train ride up to MIT.

@pmenon @seojungmin -- Thoughts?

**Comment by seojungmin** [comment]
@apavlo  I agree that it is an issue, and moving translators into a subdirectory would be a good, first move.

There are other potential candidate files to think about moving into a subdirectory, such as LLVM utility class header files(If/Loop/FunctionBuilder) and maybe proxies, later on. @pmenon What were the other candidates you mentioned last time?

**Comment by pmenon** [comment]
@apavlo Yea, I think that makes sense, especially as we continue to add more stuff.

I was thinking of having a subdirectory for `operator`, `expression`, and `proxy` for operator translators, expression translators, and all the proxy classes, respectively.

**Comment by apavlo** [comment]
I'll take care of this. I'm trying to get started on understanding the LLVM engine.
