### ISSUE TITLE
Compile Error with LOG_LEVEL lower than LOG_INFO

### ISSUE THREAD

**Issue by ChTimTsubasa** [cmu-db/peloton#692]
I encountered an unused variable error when trying to compile with LOG_LEVEL_WARNING flag.

The bug comes from(https://github.com/cmu-db/peloton/blob/6b154b312e57aa10b573ce596ed95c3b51c566a2/src/brain/index_tuner.cpp#L438), where the _valid_index_count_ is used only to print the log. When LOG_LEVEL is lower, it becomes useless.

The whole error is:
```
/home/tianyic1/peloton/src/brain/index_tuner.cpp: In function ‘void peloton::brain::PrintIndexInformation(peloton::storage::DataTable*)’:
/home/tianyic1/peloton/src/brain/index_tuner.cpp:438:9: error: unused variable ‘valid_index_count’ [-Werror=unused-variable]
   oid_t valid_index_count = table->GetValidIndexCount();
```

**Comment by pmenon** [comment]
This was fixed in #693.
