### ISSUE TITLE
Linker Error on gcc 4.8

### ISSUE THREAD

**Issue by SurajGoel** [cmu-db/peloton#704]
Getting build error on fresh vagrant box provided in this repo.

![error](https://user-images.githubusercontent.com/11015169/27551435-0764f22e-5ac1-11e7-9af4-db6769b4f712.png)

**Comment by apavlo** [comment]
This is a problem with gcc4.8. Can you try it with gcc 5?

**Comment by SurajGoel** [comment]
@apavlo Same error using gcc-5.4.1

**Comment by SurajGoel** [comment]
@apavlo Any idea ?

**Comment by pmenon** [comment]
Which version of binutils are you using? What does `ld --version` print out?

**Comment by pmenon** [comment]
The Vagrant file works for me. I just tried both release and debug builds. Ubuntu Trusty 14.04, GCC 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3), binutils 2.24, gold linker 1.11 (GNU gold (GNU Binutils for Ubuntu 2.24) 1.11).

**Comment by SurajGoel** [comment]
Hmm Strange the same box is not working for me.... What could be the problem ? Virtual Box ?

**Comment by pmenon** [comment]
Did you [try out the suggestions?](https://github.com/cmu-db/peloton/issues/704#issuecomment-311651871)
