### ISSUE TITLE
Txn Manager Crashes on UPDATE without WHERE

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#712]
The system crashes when you try to execute an `UPDATE` query that does not have a `WHERE` clause in it. This fails regardless whether the codegen feature is enabled. I only tried running this with the new optimizer enabled.
```
postgres=# CREATE TABLE foo (id INT PRIMARY KEY);
CREATE TABLE foo (id INT PRIMARY KEY) 0
postgres=# INSERT INTO foo VALUES (123);
INSERT INTO foo VALUES (123) 1
postgres=# INSERT INTO foo VALUES (456);
INSERT INTO foo VALUES (456) 1
postgres=# UPDATE foo SET id = id + 1;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Here is the server's assert message:
```
peloton: /home/pavlo/Documents/Peloton/Github/peloton-master/src/concurrency/timestamp_ordering_transaction_manager.cpp:656: \
virtual void peloton::concurrency::TimestampOrderingTransactionManager::PerformDelete(peloton::concurrency::Transaction*, const peloton::ItemPointer&, const peloton::ItemPointer&): \
Assertion `(GetLastReaderCommitId(tile_group_header, old_location.offset) == current_txn->GetCommitId())' failed.
```

The backtrace is attached.
[backtrace.txt](https://github.com/cmu-db/peloton/files/1117905/backtrace.txt)

**Comment by PauloAmora** [comment]
Wasn't this fixed in #558 ?

**Comment by apavlo** [comment]
@PauloAmora I think that this problem is different. It definitely works correctly if you include the WHERE clause:
```
postgres=# CREATE TABLE foo (id INT PRIMARY KEY);                                                                                                                 
CREATE TABLE foo (id INT PRIMARY KEY) 0                                                                                                                                               
postgres=# INSERT INTO foo VALUES (123);                                                                                 
INSERT INTO foo VALUES (123) 1                                                                                                                                                        
postgres=# INSERT INTO foo VALUES (456);                                                           
INSERT INTO foo VALUES (456) 1                                                                                                                                                        
postgres=# UPDATE foo SET id = id + 1 WHERE id > 0;                                                
UPDATE foo SET id = id + 1 WHERE id > 0 2                                                                                                                                             
postgres=# SELECT * FROM foo;                                                                                                                                                         
 id                                                                                                                                                                                   
-----                                                                                                                                                                                 
 124                                                                                                                                                                                  
 457                                                                                                                                                                                  
(2 rows)
```

**Comment by yingjunwu** [comment]
The system crashes because each tuple can be updated two or more times when performing update without `where`. 

When processing a query like `UPDATE foo SET id = id + 1`, the DBMS connects the update executor (parent executor) to a sequential scan executor (child executor). It scans the table and then updates each accessed tuple version. Every time the DBMS updates a tuple version in the table, a new tuple version will be inserted into the table. This newly inserted version can also be visited by the sequential scan executor, and subsequentally updated by the update executor. Hence, we may observe that a tuple is updated multiple times. The DBMS can keep running when performing update on a table without primary index. However, the DBMS crashes when updating a table with primary index.

**Comment by yingjunwu** [comment]
This problem is related to #106

**Comment by yingjunwu** [comment]
There are two possible solutions to address this problem.

1. Record the read/write set for each operation. Every time the DBMS finds that a single operation is trying to modify (update/insert/delete) a version that it just created, then the DBMS should directly ignore this version. However, maintaining operation-level read/write set can bring certain performance overhead, especially when a single operation reads/updates lots of tuples (e.g., update table).

2. Switch from append-only storage to time-travel storage. The disadvantage is that it can bring additional pointer-chasing overhead when visiting older versions.
