### ISSUE TITLE
release mode crashed

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#715]
Peloton does not work when built with release mode.

simply build the system using `cmake .., make -j`. Then use `psql` to issue some queries like:

```
create table foo(a int)
select * from foo
```

The system will crash, complaining that 
```
LLVM ERROR: Program used external function '_ZNK7peloton7storage9TileGroup14GetTileGroupIdEv' which could not be resolved!
terminate called without an active exception
```

**Comment by pmenon** [comment]
Looks like name mangling changes in release mode. I knew this would come back to bite us. I'll take a look.

**Comment by pmenon** [comment]
So, I can't reproduce this on my machine. What GCC version are you using? 

`storage::TileGroup::GetTileGroupId` is defined in the header. In release mode, I suspect it's getting inlined into all call-sites, doesn't make it into the binary, and, hence, isn't resolvable by LLVM. This doesn't occur in GCC 5.4, but may happen in 4.8 or 6.

**Comment by yingjunwu** [comment]
In fact, I reproduced it in a machine with GCC 5.4 (an NUS machine) and one with GCC 4.8 (CMUDB dev2). Can you try dev2 or any other machine?
