### ISSUE TITLE
New optimizer might not build plan tree for case sql

### ISSUE THREAD

**Issue by haoxianghua** [cmu-db/peloton#732]
I ran case_sql_test and find new optimizer might not support "SELECT a, case when a=1 then 2 else 0 end from test" query

**Comment by apavlo** [comment]
@hzxa21 We want to remove the old optimizer and switch over to the new one next week.

**Comment by chenboy** [comment]
This query passes the test on my machine, @haoxianghua could you provide me the log?
I will work on tearing down the SimpleOptimizer this weekend.

**Comment by apavlo** [comment]
@haoxianghua I am assuming that this is no longer a problem?
