### ISSUE TITLE
Remove print statements from ParserUtils

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#736]
Somebody added many of the parser files to the [source_validator.py](https://github.com/cmu-db/peloton/blob/master/script/validators/source_validator.py) script:

https://github.com/cmu-db/peloton/blob/master/script/validators/source_validator.py#L71

The purpose of this script is to help make sure that we don't do anything stupid in our code.

It looks like the biggest offender is ParserUtils:

https://github.com/cmu-db/peloton/blob/master/src/parser/parser_utils.cpp#L198

------------------

Here is what we need to do:

* Remove the parser files from the validator's white list.
* Move all of the functions from 'parser_utils.cpp' into a helper class called `ParserUtils` as static methods.
* All of the "Print" or "Get" methods should return strings and not print output.

**Comment by vipuldcoder** [comment]
Online 132  parser = argparse.ArgumentParser(description='Check for some strings')
So here Ones now what?

**Comment by apavlo** [comment]
@vipuldcoder I don't understand what you are asking?
