### ISSUE TITLE
CHAR and VARCHAR seem to require strlen+1

### ISSUE THREAD

**Issue by mrks** [cmu-db/peloton#744]
When creating a table, it appears as if the size for CHAR and VARCHAR have to be one larger than the actual strings:

```
postgres=# CREATE TABLE TMP(X CHAR(2));
CREATE TABLE
postgres=# INSERT INTO TMP VALUES ('A');
INSERT 0 1
postgres=# INSERT INTO TMP VALUES ('AA');
The value is too long to fit into type VARCHAR(2)
```

We found this to be an issue when running the TPC-C benchmark. After increasing the size of all CHARs in https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/ddls/tpcc-peloton-ddl.sql by 1, we were able to run the benchmark.

**Comment by apavlo** [comment]
Fixed in #745
