### ISSUE TITLE
Peloton's YCSB Benchmark  is lower than Postgresql

### ISSUE THREAD

**Issue by nshigit** [cmu-db/peloton#752]
Schema
----------------------------------------------------------
CREATE TABLE USERTABLE(
  YCSB_KEY VARCHAR(255) NOT NULL,
  FIELD0 VARCHAR(100),
  FIELD1 VARCHAR(100), FIELD2 VARCHAR(100),
  FIELD3 VARCHAR(100), FIELD4 VARCHAR(100),
  FIELD5 VARCHAR(100), FIELD6 VARCHAR(100),
  FIELD7 VARCHAR(100), FIELD8 VARCHAR(100),
  FIELD9 VARCHAR(100),
  CONSTRAINT YCSB_KEY_KEY PRIMARY KEY (YCSB_KEY)
);
----------------------------------------------------------

ycsb-jdbc-binding-0.12.0 config
----------------------------------------------------------
db.driver=org.postgresql.Driver
# jdbc.fetchsize=20
db.url=jdbc:postgresql://192.168.3.83:15721/postgres
db.user=nshi
db.passwd=
db.autocommit=1
----------------------------------------------------------
* jdbc driver -- postgresql-9.4.1207.jar

ycsb-jdbc-binding-0.12.0 workload
----------------------------------------------------------
recordcount=100000
operationcount=100000
fieldlength=10
workload=com.yahoo.ycsb.workloads.CoreWorkload

readallfields=true

readproportion=1
updateproportion=0
scanproportion=0
insertproportion=0

requestdistribution=zipfian
----------------------------------------------------------

Postgresql 9.6.3 -- Thread 4
----------------------------------------------------------
[OVERALL], RunTime(ms), 1872.0
[OVERALL], Throughput(ops/sec), 53418.80341880342
[TOTAL_GCS_PS_Scavenge], Count, 2.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 5.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.2670940170940171
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 2.0
[TOTAL_GC_TIME], Time(ms), 5.0
[TOTAL_GC_TIME_%], Time(%), 0.2670940170940171
[CLEANUP], Operations, 4.0
[CLEANUP], AverageLatency(us), 86.75
[CLEANUP], MinLatency(us), 40.0
[CLEANUP], MaxLatency(us), 186.0
[CLEANUP], 95thPercentileLatency(us), 186.0
[CLEANUP], 99thPercentileLatency(us), 186.0
[READ], Operations, 100000.0
[READ], AverageLatency(us), 63.31066
[READ], MinLatency(us), 35.0
[READ], MaxLatency(us), 15679.0
[READ], 95thPercentileLatency(us), 106.0
[READ], 99thPercentileLatency(us), 119.0
[READ], Return=OK, 100000
----------------------------------------------------------

Peloton Thread-4
----------------------------------------------------------
[OVERALL], RunTime(ms), 1895.0
[OVERALL], Throughput(ops/sec), 52770.44854881267
[TOTAL_GCS_PS_Scavenge], Count, 2.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 5.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.2638522427440633
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 2.0
[TOTAL_GC_TIME], Time(ms), 5.0
[TOTAL_GC_TIME_%], Time(%), 0.2638522427440633
[CLEANUP], Operations, 4.0
[CLEANUP], AverageLatency(us), 74.25
[CLEANUP], MinLatency(us), 35.0
[CLEANUP], MaxLatency(us), 150.0
[CLEANUP], 95thPercentileLatency(us), 150.0
[CLEANUP], 99thPercentileLatency(us), 150.0
[READ], Operations, 100000.0
[READ], AverageLatency(us), 63.77598
[READ], MinLatency(us), 32.0
[READ], MaxLatency(us), 24575.0
[READ], 95thPercentileLatency(us), 130.0
[READ], 99thPercentileLatency(us), 226.0
[READ], Return=OK, 100000
----------------------------------------------------------

![peloton-ycsb](https://user-images.githubusercontent.com/8710627/28263466-6f2a21d2-6b19-11e7-8935-f4a6ed629b25.png)

**Comment by apavlo** [comment]
@nshigit Thanks for the numbers. We're still working on rewriting/optimizing a bunch of components this summer to speed things up. This is why we haven't announced our "first release" yet. Let us look this over and get back to you.
