### ISSUE TITLE
Concurrency issue for delete operation

### ISSUE THREAD

**Issue by mengranwo** [cmu-db/peloton#756]
Let's say I've already created a table foo by executing query **CREATE TABLE foo(a int)** and then insert several tuples. 
```
postgres=# select * from foo;
 a 
---
 1
 2
 3
(3 rows)
```
The first transaction (begin early) delete tuple 1 from table foo, does not commit. And the second transaction, select * from foo using sequential scan. The correct result should return 3 rows instead of 2 since the first transaction has no committed yet, all the delete or insert operations should remain visible only within the same transaction. 
```
TXN 1                            
postgres=# BEGIN;                                                
BEGIN                                                                            
postgres=# delete from foo where A = 1;                          
delete from foo where A = 1 1                                        
postgres=# select * from foo;                                            
 a                                                                                      
---                                                                                      
 2                                                                                       
 3                                                                                        
(2 rows)

TXN 2 (begin after TXN 1)
postgres=# BEGIN;                                                
BEGIN                                                                                                              
postgres=# select * from foo;                                            
 a                                                                                      
---                                                                                      
 2                                                                                       
 3                                                                                        
(2 rows)
```
My preliminary thought after taking a brief look at the logic within delete_executor.cpp is that when deleting a tuple, transaction first inserts a tombstone in the storage level table and also grabs the deleted tuple's write lock(by setting this tuple's transaction-id metadata). If current transaction does not commit, the write lock will not be released, thus other concurrent transactions can't see the deleted tuple.

**Comment by yingjunwu** [comment]
#712 #652 

all these problems are related to the tuple-level visibility. We should carefully design it after fixing #753.
