### ISSUE TITLE
Additional Static Source Code Checks

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#770]
We should add the following checks to `scripts/formatting/formatter.py`

1. Make sure that the namespace is properly commented (#768) 
2. Make sure that testing utility files follow the proper naming convention
3. Make sure that we don't have the prefix "include/" in our own `#include`'s

**Comment by tcm-marcel** [comment]
1. and 3. were added in #968 and #991, 2. is still missing.

**Comment by tcm-marcel** [comment]
Remaining part moved to #1192.
