### ISSUE TITLE
String functions not running

### ISSUE THREAD

**Issue by fadgan** [cmu-db/peloton#777]
Currently, string functions seem to be not running.
`postgresql=# create table blah (k integer primary key, v varchar(20));`
`CREATE TABLE`
`postgresql=# insert into blah values(1, 'blah1');`
`INSERT 0 0`
`postgresql=# select concat(v, v) from blah;`
`We don't have a translator for expression type: FUNCTION`

**Comment by pmenon** [comment]
It looks like we're not checking target expressions in non-trivial projections [here](https://github.com/cmu-db/peloton/blob/master/src/codegen/query_compiler.cpp#L58). I can fix it.
