### ISSUE TITLE
Use BloomFilter during HashJoin

### ISSUE THREAD

**Issue by pmenon** [cmu-db/peloton#798]
This feature looks to potentially improve HashJoin performance by constructing and using a light-weight BloomFilter. It requires building a BloomFilter (alongside the hashtable) during the build-phase of the join, and querying the filter **before** probing the hashtable during the probe-phase. When the hashtable is larger than cache and when the join selectivity is low, the filter avoids incurring a cache-miss for every probe tuple, with some configurable false-positive rate.

For now, we'll build this on the codegen side. There are several flavors of BloomFilters, but the important feature is a configurable false-positive rate and constrained memory budget.

**Comment by luochenUmich** [comment]
I will work on implementing this as part of my capstone project.

**Comment by tcm-marcel** [comment]
Hey @luochenUmich, I got this task from @apavlo and @pmenon, but I didn't figure out how to self-assign it to me yet. (I think there are rights missing) So I will work on this, sorry for leaving this task open.

**Comment by luochenUmich** [comment]
Already finished it. https://github.com/cmu-db/peloton/pull/815

**Comment by seojungmin** [comment]
Can we have a vectorized bloom filter? This would be another task.
