### ISSUE TITLE
Running the index test suite for SkipLists

### ISSUE THREAD

**Issue by fadgan** [cmu-db/peloton#800]
Hello friends,
I'm currently trying to test a SkipList implementation on peloton.

For the uncommented code from skiplist_index_test.cpp
```
class SkipListIndexTests : public PelotonTest {};

TEST_F(SkipListIndexTests, BasicTest) {
  TestingIndexUtil::BasicTest(IndexType::SKIPLIST);
  //EXPECT_EQ(2, 1+1); 
}
```

the index testing suite not running for it (neither OK nor FAIL)

peloton@ubuntu1:/home/gitrep/peloton/build$ sudo ./test/skiplist_index_test
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SkipListIndexTests
[ RUN      ] SkipListIndexTests.BasicTest
peloton@ubuntu1:/home/gitrep/peloton/build$ 

Can anyone please hint on it?
Thanks.

**Comment by apavlo** [comment]
What happens if you modify 'bwtree_index_test.cpp' and replace `IndexType::BWTREE` with `IndexType::SKIPLIST`?

https://github.com/cmu-db/peloton/blob/master/test/index/bwtree_index_test.cpp

**Comment by fadgan** [comment]
I think it's clearer now. The code segfaults but here it doesn't show that.
When running through ctest it blames segfault.
