### ISSUE TITLE
Running peloton with skiplisted indexes

### ISSUE THREAD

**Issue by fadgan** [cmu-db/peloton#803]
Dear friends,

 I'm about to finish skiplist based index implementation in Peloton and afterwards I'm planning to do some  benchmarking to test the performance of it.
I was wondering about the procedures that would help me to make the peloton use skiplist files instead of BwTree i.e. some drop-in steps. Is there a switch that will make skiplist  .cpp files to be the default index types for the database? I'm aware that there is a corresponding tester but want to have the database build with it and use it i.e. CREATE INDEX .... let it use skiplist indexes.

 Thanks beforehand.

**Comment by apavlo** [comment]
There is no easy way to do this from SQL. You can change `IndexFactory::GetIndex()` to override the `index_type` to always use `IndexType::SKIPLIST`

https://github.com/cmu-db/peloton/blob/master/src/index/index_factory.cpp#L62
