### ISSUE TITLE
build error: No rule to make target `../third_party/libpg_query/libpg_query.a'

### ISSUE THREAD

**Issue by bluealert** [cmu-db/peloton#809]
I run the following commands:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug .. 
make
```
the output is as follows
```
[ 95%] Building CXX object src/CMakeFiles/peloton.dir/type/varlen_type.cpp.o
[ 95%] Building CXX object src/CMakeFiles/peloton.dir/util/string_util.cpp.o
[ 95%] Building CXX object src/CMakeFiles/peloton.dir/util/stringbox_util.cpp.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/murmur3/MurmurHash3.cpp.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/empirical_data.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/hll.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/hll_data.cc.o
[ 97%] Building CXX object src/CMakeFiles/peloton.dir/__/third_party/libcount/utility.cc.o
make[2]: *** No rule to make target `../third_party/libpg_query/libpg_query.a', needed by `lib/libpeloton-d.0.0.5.dylib'.  Stop.
make[1]: *** [src/CMakeFiles/peloton.dir/all] Error 2
make: *** [all] Error 2
```
I don't know how to solve this problem.

**Comment by apavlo** [comment]
I've seen this weird error too. It seems only happen when you *don't* run make in parallel.

Try `make -j 2`

**Comment by bluealert** [comment]
@apavlo 
Thank you very much! Professor.

**Comment by pranavk** [comment]
#921 should fix this issue.

See: https://github.com/cmu-db/peloton/pull/921/commits/9f36c0520146687fad35638846b5c6ba7c9eb5fb

**Comment by pranavk** [comment]
Atleast for me, it's quite easy to reproduce. I do a `make clean` in third_party/libpg_query/ and then `make` (without parallelism) in my builddir and this error will popup all the time.

**Comment by tcm-marcel** [comment]
Currently cmakebuilds libpg_query from scratch, but places the resulting binary in `third_party/libpg_query/libpg_query.a` instead of the build folder. Maybe we should change this?

**Comment by pranavk** [comment]
Is there be any benefit of moving that to the build folder? Is there any bug we are trying to fix here?

I feel it more natural that the third party static library is not in the builddir of another project, i.e., peloton.

**Comment by tcm-marcel** [comment]
There is no bug, I just thought all created files should be placed in the build folder. So let's keep it that way.

**Comment by apavlo** [comment]
@tcm-marcel You are correct. It should be in the build folder.
