### ISSUE TITLE
make -j4  compiling problems

### ISSUE THREAD

**Issue by edalmeida** [cmu-db/peloton#828]
Dear all,

following your installation procedure, in particular after "make -j4", I got this error:
Building CXX object src/CMakeFiles/peloton.dir/type/integer_type.cpp.o
/peloton/src/threadpool/worker.cpp: In constructor ‘peloton::threadpool::WorkerPool::WorkerPool(size_t, peloton::threadpool::TaskQueue*)’:
/peloton/src/threadpool/worker.cpp:56:38: error: ‘make_unique’ is not a member of ‘std’
     std::unique_ptr<Worker> worker = std::make_unique<Worker>();
                                      ^
/peloton/src/threadpool/worker.cpp:56:61: error: expected primary-expression before ‘>’ token
     std::unique_ptr<Worker> worker = std::make_unique<Worker>();
                                                             ^
/peloton/src/threadpool/worker.cpp:56:63: error: expected primary-expression before ‘)’ token
     std::unique_ptr<Worker> worker = std::make_unique<Worker>();
                                                               ^
make[2]: *** [src/CMakeFiles/peloton.dir/threadpool/worker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/peloton.dir/all] Error 2
make: *** [all] Error 2

My environment:
- Darwin asterix.local 16.7.0 Darwin Kernel Version 16.7.0:
- Apple LLVM version 9.0.0 (clang-900.0.37)
- 8GB RAM
- Core I5 1.6 Ghz
- MacOS 10.12.6

cheers,
eduardo

**Comment by apavlo** [comment]
See #824

**Comment by apavlo** [comment]
Actually, check out these instructions. You need to have the right version of the LLVM:

https://github.com/cmu-db/peloton/wiki/Installation#osx-installation-without-vagrant
