### ISSUE TITLE
Building on FreeBSD 11.1

### ISSUE THREAD

**Issue by udgw** [cmu-db/peloton#841]
Hi.
I am trying to build peloton on FreeBSD 11.1
I changed code a bit Then It has passed compiling,
However, linker print error shown below. 
[this is the log](https://gist.github.com/udgw/5486f0c4999c13dec0a46eaadfbb782f)

What makes this happen? 
Thanks.

**Comment by pmenon** [comment]
@udgw It looks like you're using gcc and not g++ for compilation. Install g++ and try to compile again.

**Comment by udgw** [comment]
Thank you very much for your advise and the error was dissapeared.

BTW, I got another error like [this](https://gist.github.com/udgw/a112e84105933a48d8e74c71b6264603)
About AbstractTable's Constructor Prptotype error. 
It says:
/home/bcen/peloton/src/storage/abstract_table.cpp:27:1: 
error: prototype for 'peloton::storage::AbstractTable::AbstractTable(id_t, peloton::catalog::Schema*, bool)'
does not match any in class 'peloton::storage::AbstractTable'

Thank you.
** I Changed Issue Name **

**Comment by apavlo** [comment]
What version of g++ are you using?

**Comment by udgw** [comment]
Thank you for your asking.
I use g++ 6.4.

Here is my current cofiguration [https://gist.github.com/udgw/1d9c99c4fbacbada44670e9cf420361f](url)
I've got same problem with clang.

**Comment by apavlo** [comment]
We definitely don't support g++6. We only target g++4 + g++5 at this point.

If you are able to fix things for g++6, please send us a PR.

**Comment by udgw** [comment]
Thank you so much.
