### ISSUE TITLE
Parser does not handle SELECT without FROM clause

### ISSUE THREAD

**Issue by prashasthip** [cmu-db/peloton#854]
For the UDF case and for built-in functions, we need the parser to support the following:

SELECT INCREMENT(1);

where INCREMENT is a function. Currently, the parser throws an error in SelectTransform, after successfully completing TargetTransform. 

SELECT INCREMENT(1) from Foo;  -> Works
We need to support SELECTs without the FROM clause as well.

**Comment by haojin2** [comment]
This is interesting issue, I think this needs a bit discussion on how we want to partition the responsibility of handling different kinds of "special" queries. I'll do some discussions with related persons and get back to your issue.

**Comment by prashasthip** [comment]
Thanks @haojin2!

**Comment by haojin2** [comment]
I've talked to the optimizer guys and am working on a quick fix for this today.

**Comment by prashasthip** [comment]
@haojin2 - Have you merged the fix?

**Comment by haojin2** [comment]
Please refer to PR #886.
