### ISSUE TITLE
Fix the access pattern for catalog objects

### ISSUE THREAD

**Issue by malin1993ml** [cmu-db/peloton#859]
Currently catalog objects are immutable snapshots of the database catalog tables. They way to access them is to directly access the public const member variables of these objects:
https://github.com/cmu-db/peloton/blob/master/src/include/catalog/index_catalog.h#L45

However, this is not safe when we're going to support virtual catalog and "what-if" optimizer API. The correct way to do this is to make them private members, and only provide public Getters for those immutable fields. For the fields that do need to be mutable, we should provide protected/private Setters and set the classes who need those Setters friend classes.

So what need to fix now is:
(1) Change all the direct accesses to the fields in catalog objects to public Getters.
(2) Change all the public const fields in catalog objects to mutable private fields.

The refactor tool in Eclipse may be able to help with this process.

**Comment by camellyx** [comment]
@malin1993ml We thought about this during the design process, since you mentioned it earlier. For "what-if" optimizer, do you need to create fake indexes or change the property of an existing index?

**Comment by malin1993ml** [comment]
Yes. We need both of them.

**Comment by malin1993ml** [comment]
And actually remove existing indexes as well.

**Comment by malin1993ml** [comment]
Fixed in #919.
