### ISSUE TITLE
Compilation error with LOG_LEVEL_TRACE

### ISSUE THREAD

**Issue by JinHai-CN** [cmu-db/peloton#869]
There are some print string without c_str() method faults. I want to fix it, I don't if I have rights to push the code. So, please help fix it.

**Comment by apavlo** [comment]
Fork the code in your own repo. Make the changes. Then send us a pull request with the fixes.

**Comment by apavlo** [comment]
@crd477 @tli2 We definitely need to run at least one build in Jenkins with `TRACE` enabled. The test output will be huge so we could pipe it to /dev/null

**Comment by crd477** [comment]
On 2017-10-30 23:22, Andy Pavlo wrote:
> @crd477 <https://github.com/crd477> @tli2 <https://github.com/tli2> We 
> definitely need to run at least one build in Jenkins with |TRACE| 
> enabled. The test output will be huge so we could pipe it to /dev/null
> 

Got it.  Testing now.

-- 
     -Chad

**Comment by hemanthmalla** [comment]
Created a PR that fixes this https://github.com/cmu-db/peloton/pull/872
