### ISSUE TITLE
Question on configuration of pelotonDB

### ISSUE THREAD

**Issue by JinHai-CN** [cmu-db/peloton#870]
I find there is a config file: configuration/peloton.conf. Is this file still used by the db server?
There is --data-directory option in the file, which seems indicating the storage path of the db file. But after I created the table, insert the data, I can't find any file or directory to store the db. Would you please help indicate this?

**Comment by apavlo** [comment]
Right now it is only in-memory. We are working on logging and checkpoints in#792

**Comment by poojanilangekar** [comment]
Will be fixed in #885

**Comment by apavlo** [comment]
The sample "peloton.conf" was removed in #1033. We're still working on adding logging support.
