### ISSUE TITLE
Does the nested_loop_join_executor really support nest loop + index scan?

### ISSUE THREAD

**Issue by kamelzcs** [cmu-db/peloton#88]
I suppose it does not work when `nl != nullptr` and I think the relevant part is wrong.
For the following relevant part code to deal with `nest loop + index scan`, I think there are several problems,

1. it is an independent part, `children_[1]->SetContext(value, 1);` would only take the value relate to the last `left_tile_row_itr`  part.
2. It does not run `Executor()` of  `index scan` for each `left_tile_row_itr`at all.

    /*
     * Go over every pair of tuples in left (outer plan)
     * and pass the joinkey to the executor and inner plan (right)
     */
    if (nl != nullptr && !left_result_tiles_.empty()) {
      // nl is supposed to be set but here is for the original version
      left_tile = left_result_tiles_.back().get();
      for (auto left_tile_row_itr : *left_tile) {
        expression::ContainerTuple<executor::LogicalTile> left_tuple(
            left_tile, left_tile_row_itr);
        ListCell *lc = nullptr;
        foreach (lc, nl->nestParams) {
          NestLoopParam *nlp = (NestLoopParam *)lfirst(lc);
          // int			paramno = nlp->paramno;
          // Var		   *paramval = nlp->paramval;

          /*
           * pass the joinkeys to executor params and set the flag = 1
           */
          Value value = left_tuple.GetValue(nlp->paramval->varattno - 1);
          executor_context_->ClearParams();
          executor_context_->SetParams(value);
          executor_context_->SetParamsExec(1);
          children_[1]->ClearContext();
          children_[1]->SetContext(value, 1);

          /* Flag parameter value as changed */
          // innerPlan->chgParam = bms_add_member(innerPlan->chgParam, paramno);
        }  // end foreach
      }    // end for
    }      // end if

**Comment by jarulraj** [comment]
@eric-haibin-lin can you take a look at this ?

**Comment by eric-haibin-lin** [comment]
@jarulraj  I noticed that we have a dummy class NestedLoopIndexJoinPlan. I guess we do not plan to use that class?

@Michael-Tieying-Zhang  It looks like the executor_context is eventually set according to the last row in left tile. I think the right way to do it is to call Execute() on right child every time context is updated?

**Comment by domino-succ** [comment]
@eric-haibin-lin You can try that and test whether IN+subquery can work after then. 

Executor_context is used when executing IN+subquery. For example,  select * from Foo1 where age IN (select id from Foo2 where name='mike'); Here "select id from Foo2 where name='mike'" is a subquery and is transformed as left child. We put the results of left child in executor_context, and the right child can execute using this context.

**Comment by jarulraj** [comment]
@kamelzcs  thanks for reporting this. we have removed the associated code from the executor, because the design was not generic. we will add support for subqueries with IN by modifying the transformer rather than the executors.

**Comment by kamelzcs** [comment]
If it is a pure nested loop executor, why is it in a incremental way as the whole logic is in a `for(;;)` loop? 
Why not just do something as below?

```
children_[0]->Execute()
BufferLeftTile(children_[0]->GetOutput());
children_[1]->Execute()
BufferRightTile(children_[1]->GetOutput());

some empty judge logic here

then
    //===--------------------------------------------------------------------===//
    // Build Join Tile
    //===--------------------------------------------------------------------===//
```

**Comment by jarulraj** [comment]
It is incremental because we do not do table-at-a-time processing. We process the data **logical-tile-at-a-time**. Here's more information on the architecture : https://github.com/cmu-db/peloton/wiki/Tile-Based-Architecture#join-operator-in-logical-tile-algebra

**Comment by jarulraj** [comment]
@Michael-Tieying-Zhang Can you send a PR based on the updated code ?

**Comment by Michael-Tieying-Zhang** [comment]
Sure. Let's review it first. Normally, the right child has a complete 
query that can execute without the executor_context, and it uses 
predicate_ to join the left and right results.

But for IN+NestLoop, there is no predicate_. We had to put the results 
of left child in executor_context, and the right child can execute using 
this context. Otherwise, the right child can't execute.

For example: select * from Foo1 where age IN (select id from Foo2 where 
name='mike');

Here:
  "select id from Foo2 where name='mike'" is transformed as left child.
  "select * from Foo1 where age " is the right child.
  "IN" is transformed as a execute context, in NestLoop Structure

So this is the refactor code :
https://github.com/Michael-Tieying-Zhang/peloton/blob/master/src/backend/executor/nested_loop_join_executor.cpp#L144 


I put the context setting code before right child executing. I think 
that makes sense. What do you think.

**Comment by jarulraj** [comment]
Can we move this logic out to the transformer instead of doing it in the executor ?

**Comment by Michael-Tieying-Zhang** [comment]
In transformer, we don't perform executing so we can't get the result of the left sub-plan. But the right sub-plan need the result of the left. The result can only be obtained inside the executor. So we can't move it to the transformer. 




tieyingz@cs.cmu.edu

From: Joy Arulraj
Date: 2016-04-04 20:05
To: cmu-db/peloton
CC: Michael
Subject: Re: [cmu-db/peloton] Does the nested_loop_join_executor really support nest loop + index scan? (#88)
Can we move this logic out to the transformer instead of doing it in the executor ?

**Comment by jarulraj** [comment]
Can we check for this case in the nested loop plan node 
https://github.com/cmu-db/peloton/blob/master/src/backend/bridge/dml/mapper/mapper_nested_loop_join.cpp#L29

And add a left plan node as the child of this node ?

**Comment by Michael-Tieying-Zhang** [comment]
The left plan is already added as the child in the nested loop transform. All the static parameters are added (transformed) in the nested loop transform. What the right plan needs is the execution result of the left plan. So we can only pass the result to the right plan when executing. 




tieyingz@cs.cmu.edu

From: Joy Arulraj
Date: 2016-04-04 20:24
To: cmu-db/peloton
CC: Michael
Subject: Re: [cmu-db/peloton] Does the nested_loop_join_executor really support nest loop + index scan? (#88)
Can we check for this case in the nested loop plan node 
https://github.com/cmu-db/peloton/blob/master/src/backend/bridge/dml/mapper/mapper_nested_loop_join.cpp#L29
And add a left plan node as the child of this node ?

**Comment by kamelzcs** [comment]
> We process the data logical-tile-at-a-time. Here's more information on the architecture

1. Do you mean `children_[0]->Execute()` and `children_[1]->Execute()` would generate a pair of logical tiles those would be passed to the join operator?
2. The current nested join looks like simulation some coroutine  feature, which I think is unnecessary complex, as the join operator should always be driven by the outer plan(right child). Once the right child finished, there is no need to consider left child any more.

**Comment by jarulraj** [comment]
1. Yes, that is correct.
2. We need to support LEFT OUTER JOIN. If the execution is completely driven by the RIGHT child, then it won't work correctly.
