### ISSUE TITLE
Exhaustive Generic Join Test Cases

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#9]
We need to test all the different combinations of tile groups, value types, join types, and join algorithms. This needs to be generic so that we can easily re-use the code whenever we add a new join executor.

**Comment by jarulraj** [comment]
Added a generic join test suite in 97a5dcc233f7c20dd55e41317d0d3ee1a459faf0. It evaluates different join types (Inner, Left outer, Right outer, Full outer) and join algorithms (Nested loop join, Merge join, Hash join). We deal with logical tiles here, so we don't worry about tile group layout in this test suite. We do value type testing in another test suite.
