### ISSUE TITLE
fix T_ResultState problem.

### ISSUE THREAD

**Issue by yingjunwu** [cmu-db/peloton#90]
@YangMann dml_utils.cpp

**Comment by jarulraj** [comment]
@yingjunwu  Add more information on the problem. @YangMann any updates ?

**Comment by YangMann** [comment]
@jarulraj `T_ResultState` is an empty switch case. It's a node type and is used for some optimizations. 
Currently it's an empty switch case. It is causing Peloton to report "not supported operation" error when calling functions like `avg`, `max` on primary key columns.

**Comment by normanyahq** [comment]
I fixed it in this PR: https://github.com/cmu-db/peloton/pull/167

**Comment by yingjunwu** [comment]
@normanyahq that's great! thanks!
