### ISSUE TITLE
Add type cast to peloton

### ISSUE THREAD

**Issue by tli2** [cmu-db/peloton#909]
Already done:

Added parse tree / plan tree / translator

Need to:

1. Add check before invoking implicit cast in LLVM (probably in the binder)
2. Add non-implicit cast (String to everything, date, etc.)
3. Test cases

**Comment by apavlo** [comment]
I think that this was added in #975

**Comment by tcm-marcel** [comment]
@apavlo I think #975 only adds the cast for dates. Nevertheless, we can continue with this code. @tli2 and I had other things to do, so we didn't continue here.
