### ISSUE TITLE
{seq,index}_scan_executor should fail when operation failed

### ISSUE THREAD

**Issue by ranxian** [cmu-db/peloton#91]
In https://github.com/cmu-db/peloton/blob/master/src/backend/executor/seq_scan_executor.cpp#L141 and https://github.com/cmu-db/peloton/blob/master/src/backend/executor/index_scan_executor.cpp#L182, when the executor uses the txn manager to perform read, the txn manager may return false (e.g. 2PL txn manager may fail to acquire read lock). If so, the executor should check the result of `PerformRead` and also report failure

**Comment by yingjunwu** [comment]
@ranxian issue solved?

**Comment by ranxian** [comment]
Solved in this commit:
https://github.com/cmu-db/peloton/pull/96/commits/e2fbb9e0668d12f3302e3457809f166e5c3a17d3
