### ISSUE TITLE
Changes needed in floor SQL function

### ISSUE THREAD

**Issue by saatviks** [cmu-db/peloton#927]
Some changes are needed in the `floor` function implementation/tests added via PR #889  as are being suggested in the `ceiling` function PR #898 .

**Comment by poojanilangekar** [comment]
@saatviks What is the status on this? Both the PRs have been merged? Do we still need changes or can this issue be closed?

**Comment by saatviks** [comment]
Although the `floor` PR was merged in, there were some changes needed which came out when the `ceil` function went through a more thorough review. I'll finish this by next week.

**Comment by poojanilangekar** [comment]
Cool, please make sure you close this issue when the changes go through.

**Comment by apavlo** [comment]
What happened with this issue?

**Comment by saatviks** [comment]
Apologies for the delay - I'll submit the PR today itself.
