### ISSUE TITLE
Update README.md for new Jenkins badge location

### ISSUE THREAD

**Issue by crd477** [cmu-db/peloton#929]
Since the Jenkins project page has changed, the badge location has also changed as follows:
-[![Jenkins Status](http://jenkins.db.cs.cmu.edu:8080/job/Peloton/badge/icon)](http://jenkins.db.cs.cmu.edu:8080/job/Peloton/)
+[![Jenkins Status](http://jenkins.db.cs.cmu.edu:8080/job/peloton/job/master/badge/icon)](http://jenkins.db.cs.cmu.edu:8080/job/peloton/)

This is solely a textual change so I'm not submitting it as a PR to avoid CI churn; someone with permissions can just edit it in the web page.

**Comment by apavlo** [comment]
I will take care of this. Thanks!
