### ISSUE TITLE
state of third party code in peloton

### ISSUE THREAD

**Issue by pranavk** [cmu-db/peloton#957]
Managing the third_party modules in a way such that we are able to update them nicely with new releases/security fixes upstream seems an ideal way to go. Do we have something like this in mind?

Or do we just want to fork them (as we have already) and make modifications to them gradually making it impossible/difficult to get any new features from upstream?

Ideal way to go might be to download the tarball from upstream and them apply patches on top of them during build time. Any thoughts?

**Comment by schedutron** [comment]
Seems right, but won't there be difficult merge conflicts between custom features we add and new releases from upstream if the pace of pulling from upstream is low?

**Comment by phisiart** [comment]
We should do this:

For modules we don't want to modify, use git submodule.
For modules we want to modify, fork a custom version and use git submodule.
