### ISSUE TITLE
Codegen'ing log records

### ISSUE THREAD

**Issue by seojungmin** [cmu-db/peloton#963]
This issue may be _stupid_, but I thought it would be worth posting it.

While I was looking at @PauloAmora's logging PR, I wondered whether we could generate code for creating the logging records.  If we could assume most of the transactions will succeed after all, creating log records while we create the tuples is not a big burden because most of the values are already known at the time of insert/updates.  This will definitely reduce the resource used in re-serializaing the values for the log records.

Comments are welcome.

**Comment by pmenon** [comment]
This is something we’ve already discussed before. Let’s hold off for now.
