### ISSUE TITLE
Use of c++14 in bloom_filter_test.cpp

### ISSUE THREAD

**Issue by poojanilangekar** [cmu-db/peloton#964]
[Line 339](https://github.com/cmu-db/peloton/blob/f329366cdc687a1aad1ca272e46d11595370d093/test/codegen/bloom_filter_test.cpp#L339) uses [make_unique](http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique) which is a c++14 feature, causing make check on vagrant to fail.

The solution would be to replace the make_unique call with `std::unique_ptr<catalog::Schema>(new catalog::Schema(cols))`

I have made that change locally and it does not break any tests, but I am not sure if I am missing something. Can someone please check and confirm?

**Comment by seojungmin** [comment]
@poojanilangekar Your changes should work.

**Comment by poojanilangekar** [comment]
Thanks! I have raised a PR.

**Comment by poojanilangekar** [comment]
Fixed in #966
