### ISSUE TITLE
Postgres Executor Link Not Working

### ISSUE THREAD

**Issue by schedutron** [cmu-db/peloton#967]
In the Architecture wiki, under the [Peloton Query Processing](https://github.com/cmu-db/peloton/wiki/Architecture#peloton-query-processing) section, the links are no longer working. The current links are, respectively:

https://github.com/cmu-db/peloton/blob/master/src/postgres/backend/executor/execMain.cpp.
https://github.com/cmu-db/peloton/blob/master/src/postgres/backend/tcop/utility.cpp

**Comment by schedutron** [comment]
The following link seems to work: https://github.com/cmu-db/peloton/blob/5b69e27785b5be1dd7edaf1205f2e6dd87b66404/src/postgres/backend/executor/execMain.cpp (dates back to 2015, when the wiki was last edited).

**Comment by apavlo** [comment]
All of that is old. I am going to just delete the page. We don't use Postgres at all anymore.
