### ISSUE TITLE
Installed Peloton on MAC 10.13.2 and couldn't execute Peloton

### ISSUE THREAD

**Issue by adityafeb22** [cmu-db/peloton#976]
Hi guys,

I am beginner here and I am sure I should be asking a very basic question. I have installed Peloton using vagrant..

Linking CXX executable ../bin/peloton
[100%] Built target peloton-bin
➜  build make install
[  0%] Original libpg makefile target
[  0%] Built target libpg_query
[  0%] Built target peloton-proto
[ 98%] Built target peloton
[100%] Built target peloton-bin
Install the project...
-- Install configuration: "Release"
-- Installing: /home/vagrant/build/install/share/Peloton/PelotonConfig.cmake

I am done installing and adding the path..

But when I am trying to start executing "peloton" I get this command not found error.

➜  bin peloton
zsh: command not found: peloton

Not sure where things went wrong, any help here is greatly appreciated!

Thanks,
Aditya B

**Comment by apavlo** [comment]
What's in your 'build/bin' directory?

**Comment by adityafeb22** [comment]
➜  build cd bin
➜  bin ls
peloton

Thanks Professor for the reply,, Above is the output of ls in the bin folder...
I have peloton in the bin folder,, nothing apart from that..

**Comment by schedutron** [comment]
Are you able to start the server by typing `./peloton` while in the `bin` folder?

**Comment by adityafeb22** [comment]
I could start peloton as suggested, but while it is running I tried opening psql which says pstgre is not running

➜  bin psql "sslmode=disable" -U postgres
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
I am running on the default port 15721

**Comment by poojanilangekar** [comment]
To start your psql client use the following:

 psql "sslmode=disable" -U postgres -p 15721

**Comment by adityafeb22** [comment]
psql "sslmode=disable" -U postgres -h vagrant-ubuntu-trusty-64 -p 15721

I had to use my hostname instead... to get this worked

So excited to start this stuff with you guys. Thanks a lot for all the help
