### ISSUE TITLE
Change Travis to use gcc 4.8

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#978]
* Change travis.yml to enforce gcc version 4.8. 
* Add new travis target for clang builds on Ubuntu

This may fix @crd477's docker build problem.

**Comment by crd477** [comment]
On 2017-12-20 13:18, Andy Pavlo wrote:
>   * Change travis.yml to enforce gcc version 4.8.
>   * Add new travis target for clang builds on Ubuntu
> 
> This may fix @crd477 <https://github.com/crd477>'s docker build problem.
> 

That problem was already fixed by 
4399ebf99c7553741f7bbbdf3170fa583ff8a7ee.  I'm not aware of any 
outstanding Docker build problems.

The Jenkins gcc builds for Ubuntu Trusty use 4.8 and are currently working.


-- 
     -Chad

**Comment by crd477** [comment]
Just to clarify, I'm not aware of any outstanding problems with the Docker build **mechanism**.  There are still some build failures in Jenkins but they are genuine compilation or linking problems not to do with Docker.

**Comment by tcm-marcel** [comment]
The error is Jenkins is following:
```
/usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
```
It may happen because of clang using the wrong `libc++`. 

Comment from https://stackoverflow.com/questions/24342312/clang-seems-to-use-the-gcc-libraries:
>I had similar issue: GCC (g++) already was installed on my LinuxMint (Ubuntu base) so when compile with clang, was getting an " error: no member named 'gets' in the global namespace using ::gets ".
>
>resolved by installing libc++-dev (sudo apt-get install libc++-dev) and compiling with -stdlib++ (clang++ -g -std=c++1y -stdlib=libc++ helloworld.cpp -o helloworld)

**Comment by crd477** [comment]
Nice find.  libc++-dev is already installed on the Jenkins Trusty image but -stdlib=libc++ is not being passed on the command line.  I can test this fix if you're not already down that path.

**Comment by crd477** [comment]
I take that back - libc++-dev is not installed, only libstdc++-4.8-dev.  I'll add it.

**Comment by tcm-marcel** [comment]
1. done in #989 
2. WIP in #1052

**Comment by pervazea** [comment]
So... is this OK to close now? #1052 remains to track clang work.
