### ISSUE TITLE
TileGroupLayoutTests Doesn't Test Layouts

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#983]
I switched `LayoutType` to be an `enum class` in #982. This caused a compilation error in  `TileGroupLayoutTests`. It turns out that we were passing in a `LayoutType` to `TableFactory::GetDataTable()` but it was being cast to a bool that had nothing to do with layout. So the flag wasn't being used and this this test case doesn't actually different layouts in the system. 

We need to rewrite this test so that it actually tests what it is supposed to test. I think it needs to change the layout on TileGroups manually.

**Comment by rohit-cmu** [comment]
I will try to fix this.
