### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [cmu-db/peloton#998]
Would you like to wrap more pointer data members with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [PelotonClient](https://github.com/cmu-db/peloton/blob/a51ccc3669568fa99eda32cb1a9c1f172ef4b101/src/include/network/service/peloton_client.h#L26)
- [RpcClient](https://github.com/cmu-db/peloton/blob/a51ccc3669568fa99eda32cb1a9c1f172ef4b101/src/network/service/rpc_client.cpp#L25)

**Comment by tli2** [comment]
I don't think the Rpc code is being used at all and will probably get scrapped soon for a new one.
